import { MapAlert, JobPost, UNIFIED_CATEGORIES } from '../types';
import { MASSIVE_SERVICES_DATABASE } from './massiveServicesDatabase';
import { JOB_SOURCES_DATABASE } from './jobSourcesDatabase';

export { JOB_SOURCES_DATABASE };

export const PROTECTED_SERVICES: MapAlert[] = [
    ...MASSIVE_SERVICES_DATABASE,
    {
        id: 'p-serv-irn-nacional',
        title: "IRN – Instituto dos Registos e do Notariado (Portal Oficial)",
        category: "Residência & Vistos",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de São Bento, 148, 1200-821 Lisboa",
        city: "Lisboa / Nacional",
        website: "https://irn.justica.gov.pt/",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-iefp-nacional',
        title: "IEFP – Instituto do Emprego e Formação Profissional (Portal Oficial)",
        category: "Trabalho & Carreira",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Xabregas, 52, 1949-003 Lisboa",
        city: "Lisboa / Nacional",
        website: "https://www.iefp.pt/",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-ss-nacional',
        title: "Segurança Social Direta (Portal Oficial)",
        category: "Finanças & Impostos",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Rosa Araújo, 43, 1250-194 Lisboa",
        city: "Lisboa / Nacional",
        website: "https://www.seg-social.pt/",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-financas-nacional',
        title: "Portal das Finanças (Autoridade Tributária)",
        category: "Finanças & Impostos",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua do Comércio, 49, 1100-150 Lisboa",
        city: "Lisboa / Nacional",
        website: "https://www.portaldasfinancas.gov.pt/",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-loja-cidadao-laranjeiras',
        title: "Loja do Cidadão das Laranjeiras",
        category: "Residência & Vistos",
        lat: 38.7495,
        lng: -9.1678,
        distance: 'N/A',
        address: "Rua Abranches Ferrão, 10, 1600-001 Lisboa",
        city: "Lisboa",
        website: "https://www.gov.pt/contactos/loja-de-cidadao-das-laranjeiras",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: '917e2978-831e-4537-8e6f-fb9f8e438e3e',
        title: "Cruz Vermelha Portuguesa – Delegação de Braga",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Bernardo Sequeira, 247, 4715-017 Braga",
        city: "Braga",
        website: "https://www.cruzvermelha.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-aaeif',
        title: "AAEIF – Associação de Apoio a Emigrantes, Imigrantes e Famílias",
        category: "Comunidade & Apoio",
        lat: 0,
        lng: 0,
        distance: 'Online',
        address: "Apenas Online – www.aaeif.pt",
        city: "Online",
        website: "https://www.aaeif.pt/",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-portuando',
        title: "Portuando Brasil",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Online / Blogspot",
        city: "Online",
        website: "https://portuando-brasil.blogspot.com/",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: '25b306ac-7422-4a0b-93df-5ae666993130',
        title: "SEIVA – Associação ao Serviço da Vida",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Vilar, 130, 4050-625 Porto",
        city: "Porto",
        website: "https://seiva.co.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-3',
        title: "ASI – Associação Solidariedade Internacional",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua das Pedras nº 307 e Rua Diogo Cão nº 257",
        city: "Vila Nova de Gaia",
        website: "https://www.asigv.org",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-4',
        title: "UNIVERA – Centro Social e Paroquial da Vera Cruz",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Campeão das Províncias, 1º andar, 3800-124 Aveiro",
        city: "Aveiro",
        website: "https://www.cspveracruz.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-5',
        title: "Casa Lusófona ONGD",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida Sá da Bandeira 115, 4º piso, Loja 37/38, 3004-515 Coimbra",
        city: "Coimbra",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-6',
        title: "InPulsar – Associação para o Desenvolvimento Comunitário",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Dr. José Gonçalves, nº 55, Loja 3, Piso -1, 2410-121 Leiria",
        city: "Leiria",
        website: "http://www.inpulsar.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-7',
        title: "Centro Social e Paroquial Costa da Caparica",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida 1º de Maio, nº 4, R/C, 2825-395 Costa da Caparica",
        city: "Almada",
        website: "https://www.cspcostacap.org",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-8',
        title: "Centro Cultural Moldavo",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua José Malhoa, nº 11, Trajouce, 2785-657 São Domingos de Rana",
        city: "Cascais",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-9',
        title: "BYP – Batoto Yetu Portugal",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida João de Freitas Branco, nº 12, 2760-073 Caxias",
        city: "Oeiras",
        website: "https://batotoyetu.org",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-10',
        title: "AGUINENSO – Associação Guineense de Solidariedade Social",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida João Paulo II, Lote 528, 2A, Bairro do Condado, 1950-430 Lisboa",
        city: "Lisboa",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-11',
        title: "Município de Odivelas – Serviço de Apoio ao Imigrante",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Alfredo Roque Gameiro, nº 18B, 2675-277 Odivelas",
        city: "Odivelas",
        website: "https://www.cm-odivelas.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-12',
        title: "Associação ProAbraçar",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praceta do Chapim, nº 26, R/C, 2080-048 Almeirim",
        city: "Almeirim",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-13',
        title: "Fábrica da Igreja de Nossa Senhora da Conceição",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida Bento de Jesus Caraça, nº 77, 2910-430 Setúbal",
        city: "Setúbal",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-14',
        title: "Câmara Municipal de Beja – Divisão de Desenvolvimento Social",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Angola, nº 5, 7800-468 Beja",
        city: "Beja",
        website: "https://www.cm-beja.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-15',
        title: "Associação Caboverdiana de Sines e Santiago do Cacém",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua João Doroteia, Lote LE1, 7520-109 Sines",
        city: "Sines",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-16',
        title: "DOINA – Associação de Imigrantes Romenos e Moldavos do Algarve",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida 5 de Outubro, Porta 76, 8135-100 Almancil",
        city: "Loulé",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-17',
        title: "GRATO – Grupo de Apoio a Toxicodependentes",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida Guanaré (Pavilhão), 8500-507 Portimão",
        city: "Portimão",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-jrs',
        title: "JRS Portugal – Serviço Jesuíta aos Refugiados",
        category: "Comunidade & Apoio",
        lat: 38.7742,
        lng: -9.1558,
        distance: 'N/A',
        address: "Rua Rogério de Moura, Lote 59, Alto do Lumiar, 1750-342 Lisboa",
        city: "Lisboa",
        website: "https://jrsportugal.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-cpr',
        title: "Conselho Português para os Refugiados (CPR)",
        category: "Residência e Legalização",
        lat: 38.7061,
        lng: -9.4184,
        distance: 'N/A',
        address: "Estrada da Costa, nº 1359, 2750-642 Cascais",
        city: "Cascais",
        website: "https://www.cpr.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-solim',
        title: "Solidariedade Imigrante (SOLIM)",
        category: "Comunidade & Apoio",
        lat: 38.7185,
        lng: -9.1354,
        distance: 'N/A',
        address: "Rua do Benformoso, 289, 1100-085 Lisboa",
        city: "Lisboa",
        website: "https://solimportugal.org",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-lisbon-project',
        title: "Lisbon Project",
        category: "Comunidade & Apoio",
        lat: 38.7369,
        lng: -9.1325,
        distance: 'N/A',
        address: "Rua Carvalho Araújo, 66-B, 1900-140 Lisboa",
        city: "Lisboa",
        website: "https://lisbonproject.org",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-casa-brasil',
        title: "Casa do Brasil de Lisboa",
        category: "Comunidade & Apoio",
        lat: 38.7128,
        lng: -9.1456,
        distance: 'N/A',
        address: "Rua Luz Soriano, 42, 1200-248 Lisboa",
        city: "Lisboa",
        website: "http://casadobrasillisboa.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-refugees-welcome',
        title: "Refugees Welcome Portugal",
        category: "Comunidade & Apoio",
        lat: 41.1825,
        lng: -8.6865,
        distance: 'N/A',
        address: "Rua de Alfredo Cunha 378, Sala 7, 4450-021 Matosinhos",
        city: "Matosinhos / Porto",
        website: "https://refugees-welcome.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-apirp',
        title: "APIRP – Apoio a Imigrantes e Refugiados",
        category: "Comunidade & Apoio",
        lat: 38.7935,
        lng: -9.1024,
        distance: 'N/A',
        address: "Avenida de São José, nº 6, 3º Esquerdo, 2685-108 Sacavém",
        city: "Loures",
        website: "https://www.apirp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-femafro',
        title: "FEMAFRO – Associação de Mulheres Negras",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Lisboa (Sede)",
        city: "Lisboa",
        website: "https://femafro.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-medicos-mundo',
        title: "Médicos do Mundo Portugal",
        category: "Saúde (SNS)",
        lat: 38.7042,
        lng: -9.1764,
        distance: 'N/A',
        address: "Avenida de Ceuta (Sul), Lote 4, Loja 1, 1300-125 Lisboa",
        city: "Lisboa",
        website: "https://medicosdomundo.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-caritas',
        title: "Cáritas Portuguesa",
        category: "Comunidade & Apoio",
        lat: 38.7394,
        lng: -9.1345,
        distance: 'N/A',
        address: "Praça Pasteur, 11 – 2º Esq., 1000-238 Lisboa",
        city: "Lisboa",
        website: "https://www.caritas.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-open-gate',
        title: "Open Gate Portugal",
        category: "Comunidade & Apoio",
        lat: 38.7295,
        lng: -9.1012,
        distance: 'N/A',
        address: "Rua 2 da Matinha, 5D, 1950-326 Lisboa",
        city: "Lisboa",
        website: "https://opengateportugal.com",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-adip',
        title: "ADIP – Associação Despertar Imigrantes",
        category: "Comunidade & Apoio",
        lat: 38.6294,
        lng: -9.1172,
        distance: 'N/A',
        address: "Rua Professor Egas Moniz, nº 24A, Salas B/C, 2845-384 Amora",
        city: "Seixal",
        website: "https://associacaoadip.com",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-renovar-mouraria',
        title: "Renovar a Mouraria",
        category: "Comunidade & Apoio",
        lat: 38.7174,
        lng: -9.1342,
        distance: 'N/A',
        address: "Beco do Rosendo, nº 8 e 10, 1100-460 Lisboa",
        city: "Lisboa",
        website: "https://renovaramouraria.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-escolhas',
        title: "Programa Escolhas (IPDJ)",
        category: "Comunidade & Apoio",
        lat: 38.7382,
        lng: -9.1594,
        distance: 'N/A',
        address: "Avenida Columbano Bordalo Pinheiro, 86, 1070-065 Lisboa",
        city: "Lisboa",
        website: "https://escolhas.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-mundo-feliz',
        title: "Mundo Feliz – Associação de Imigrantes",
        category: "Comunidade & Apoio",
        lat: 38.7064,
        lng: -9.2312,
        distance: 'N/A',
        address: "Rua Dr. Manuel de Arriaga, Nº 20A, 1495-019 Algés",
        city: "Oeiras",
        website: "https://www.mundofeliz.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-pao-pao',
        title: "Pão a Pão – Integração Alimentar",
        category: "Comunidade & Apoio",
        lat: 38.7235,
        lng: -9.1325,
        distance: 'N/A',
        address: "Mercado de Arroios, Rua de Arroios, Lisboa",
        city: "Lisboa",
        website: "https://paoapao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-pdh',
        title: "Plataforma de Direitos Humanos Portugal",
        category: "Comunidade & Apoio",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Lisboa",
        city: "Lisboa",
        website: "https://plataformadh.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-cvp-migrantes',
        title: "Cruz Vermelha Portuguesa – Apoio a Migrantes",
        category: "Comunidade & Apoio",
        lat: 38.7058,
        lng: -9.1624,
        distance: 'N/A',
        address: "Jardim 9 de Abril, 1 a 5, 1249-083 Lisboa",
        city: "Lisboa",
        website: "https://www.cruzvermelha.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-sos-racismo',
        title: "SOS Racismo Portugal",
        category: "Comunidade & Apoio",
        lat: 38.7061,
        lng: -9.1604,
        distance: 'N/A',
        address: "Rua das Janelas Verdes, 2, 1200-692 Lisboa",
        city: "Lisboa",
        website: "https://sosracismo.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-crescer',
        title: "CRESCER – Associação de Intervenção Comunitária",
        category: "Comunidade & Apoio",
        lat: 38.7045,
        lng: -9.1768,
        distance: 'N/A',
        address: "Bairro Qta Cabrinha 3 – E/F, 1300-906 Lisboa",
        city: "Lisboa",
        website: "https://crescer.org",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-aemirep',
        title: "AEMIREP – Empreendedorismo Imigrante",
        category: "Trabalho & Carreira",
        lat: 38.7754,
        lng: -9.1564,
        distance: 'N/A',
        address: "Rua Varela Silva, Lote 10, Loja B, 1750-403 Lisboa",
        city: "Lisboa",
        website: "https://aemirep.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-29',
        title: "CNAIM Lisboa",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Lisboa",
        city: "Lisboa",
        website: "https://aima.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-30',
        title: "CNAIM Porto",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Porto",
        city: "Porto",
        website: "https://aima.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-31',
        title: "CNAIM Faro",
        category: "Residência e Legalização",
        lat: 37.0179,
        lng: -7.9308,
        distance: 'N/A',
        address: "Faro",
        city: "Faro",
        website: "https://aima.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-32',
        title: "CLAIM – Centros Locais de Apoio à Integração de Migrantes",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rede nacional",
        city: "Nacional",
        website: "https://aima.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-33',
        title: "Centro de Emprego de Braga",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de São Marcos, 126",
        city: "Braga",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-34',
        title: "Centro de Emprego do Porto",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Entre Quintas, 4440-213 Alfena",
        city: "Porto",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-35',
        title: "Centro de Emprego de Guimarães",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua da Rainha D. Mafalda",
        city: "Guimarães",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-36',
        title: "Centro de Emprego de Viana do Castelo",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Largo de Camões",
        city: "Viana do Castelo",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-37',
        title: "Centro de Emprego de Aveiro",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua do Comércio",
        city: "Aveiro",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-38',
        title: "Centro de Emprego de Coimbra",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Visconde da Luz",
        city: "Coimbra",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-39',
        title: "Centro de Emprego de Leiria",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Carreira dos Rapazes",
        city: "Leiria",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-40',
        title: "Centro de Emprego de Viseu",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua do Comércio",
        city: "Viseu",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-41',
        title: "Centro de Emprego de Lisboa — Picoas",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Av. Fontes Pereira de Melo, 14",
        city: "Lisboa",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-42',
        title: "Centro de Emprego Almada / Seixal",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Queluz, Lt. 54 A",
        city: "Almada",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-43',
        title: "Centro de Emprego de Oeiras",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Manuel da Maia, 2",
        city: "Oeiras",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-44',
        title: "Centro de Emprego de Sintra",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Estrada de Mem Martins",
        city: "Sintra",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-45',
        title: "Centro de Emprego de Évora",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua do Cardeal D. Alexandre",
        city: "Évora",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-46',
        title: "Centro de Emprego de Beja",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua do Pará",
        city: "Beja",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-47',
        title: "Centro de Emprego de Portalegre",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Santo António",
        city: "Portalegre",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-48',
        title: "Centro de Emprego de Faro",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Conselheiro Bivar",
        city: "Faro",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-49',
        title: "Centro de Emprego de Loulé",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Av. 5 de Outubro, 3",
        city: "Loulé",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-50',
        title: "Centro de Emprego de Portimão",
        category: "Emprego e Formação",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua dos Campeões Olímpicos",
        city: "Portimão",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-51',
        title: "AIMA – Unidade de Lisboa (CNAIM)",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Álvaro Coutinho, 14–16",
        city: "Lisboa",
        website: "https://aima.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-52',
        title: "AIMA – Unidade do Porto (Norte)",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida de França, 316, Edifício Capitólio",
        city: "Porto",
        website: "https://aima.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-53',
        title: "AIMA – Unidade de Faro (Algarve)",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Loja do Cidadão de Faro, Mercado Municipal",
        city: "Faro",
        website: "https://aima.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-54',
        title: "ACM — Apoio ao Migrante",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "",
        city: "Nacional",
        website: "https://www.gov.pt/pt/servicos/centros-nacionais-de-apoio-a-integracao-de-migrantes-cnaim",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-55',
        title: "IRN – Conservatória Central de Lisboa",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de São Bento, 148",
        city: "Lisboa",
        website: "https://irn.justica.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-56',
        title: "IRN – Conservatória Central do Porto",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça de Gomes Teixeira",
        city: "Porto",
        website: "https://irn.justica.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-57',
        title: "IRN – Conservatória Central de Coimbra",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça 8 de Maio",
        city: "Coimbra",
        website: "https://irn.justica.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-58',
        title: "IRN – Conservatória Central de Évora",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça do Sertório",
        city: "Évora",
        website: "https://irn.justica.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-59',
        title: "IRN – Conservatória Central de Faro",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida da República, n.º 286",
        city: "Faro",
        website: "https://irn.justica.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-60',
        title: "Conservatória do Registo Civil de Braga",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de São Victor",
        city: "Braga",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-61',
        title: "Conservatória do Registo Civil de Guimarães",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Largo Oliveira Martins",
        city: "Guimarães",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-62',
        title: "Conservatória do Registo Civil de Viana do Castelo",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Av. dos Combatentes",
        city: "Viana do Castelo",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-63',
        title: "Conservatória do Registo Civil de Vila Nova de Gaia",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Santos Pousada",
        city: "Vila Nova de Gaia",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-64',
        title: "Conservatória do Registo Civil de Matosinhos",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Brito Capelo",
        city: "Matosinhos",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-65',
        title: "Conservatória do Registo Civil de Aveiro",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Largo da Praça do Peixe",
        city: "Aveiro",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-66',
        title: "Conservatória do Registo Civil de Leiria",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça Rodrigues Lobo",
        city: "Leiria",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-67',
        title: "Conservatória do Registo Civil de Viseu",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Largo da Sé",
        city: "Viseu",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-68',
        title: "Conservatória do Registo Civil de Lisboa (Douradores)",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua dos Douradores, 109",
        city: "Lisboa",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-69',
        title: "Conservatória do Registo Civil de Almada",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida Alfredo da Silva",
        city: "Almada",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-70',
        title: "Conservatória do Registo Civil de Sintra",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Dr. Alfredo da Costa",
        city: "Sintra",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-71',
        title: "Conservatória do Registo Civil de Cascais",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida Valbom",
        city: "Cascais",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-72',
        title: "Conservatória do Registo Civil de Évora – Central",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça do Sertório",
        city: "Évora",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-73',
        title: "Conservatória do Registo Civil de Beja",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua D. Pedro V",
        city: "Beja",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-74',
        title: "Conservatória do Registo Civil de Faro – Central",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida da República, 286",
        city: "Faro",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-75',
        title: "Conservatória do Registo Civil de Portimão",
        category: "Registos e Nacionalidade",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua do Comércio",
        city: "Portimão",
        website: "",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-76',
        title: "Finanças Braga",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça Conde de Agrolongo, 4700-223 Braga",
        city: "Braga",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-77',
        title: "Finanças Porto",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Cândido dos Reis, 55, 4050-151 Porto",
        city: "Porto",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-78',
        title: "Finanças Vila Nova de Gaia",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Almeida Garrett, 4400-208 Vila Nova de Gaia",
        city: "Vila Nova de Gaia",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-79',
        title: "Finanças Viana do Castelo",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça D. Afonso III, 4900-351 Viana do Castelo",
        city: "Viana do Castelo",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-80',
        title: "Finanças Guimarães",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Santo António, 4810-208 Guimarães",
        city: "Guimarães",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-81',
        title: "Finanças Coimbra",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida Fernão de Magalhães, 3030-144 Coimbra",
        city: "Coimbra",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-82',
        title: "Finanças Leiria",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua da Junqueira, 2410-328 Leiria",
        city: "Leiria",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-83',
        title: "Finanças Aveiro",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Dr. Mário Sacramento, 3810-192 Aveiro",
        city: "Aveiro",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-84',
        title: "Finanças Viseu",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Paio Galvão, 3520-300 Viseu",
        city: "Viseu",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-85',
        title: "Finanças Lisboa – Praça de Espanha",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Av. das Forças Armadas, 1500-264 Lisboa",
        city: "Lisboa",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-86',
        title: "Finanças Lisboa – Campo Grande",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Av. do Brasil, 53, 1700-089 Lisboa",
        city: "Lisboa",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-87',
        title: "Finanças Amadora",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Av. Doutor Miguel Bombarda, 2700-289 Amadora",
        city: "Amadora",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-88',
        title: "Finanças Sintra",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Largo Luís de Camões, 2710-129 Sintra",
        city: "Sintra",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-89',
        title: "Finanças Almada",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça da República, 2800-087 Almada",
        city: "Almada",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-90',
        title: "Finanças Évora",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Cândido dos Reis, 7000-099 Évora",
        city: "Évora",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-91',
        title: "Finanças Beja",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de D. Afonso III, 7800-217 Beja",
        city: "Beja",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-92',
        title: "Finanças Portalegre",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Santo António, 7300-533 Portalegre",
        city: "Portalegre",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-93',
        title: "Finanças Faro",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça da Liberdade, 8000-266 Faro",
        city: "Faro",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-94',
        title: "Finanças Portimão",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua 16 de Junho, 8500-556 Portimão",
        city: "Portimão",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-95',
        title: "Finanças Loulé",
        category: "Finanças",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida José da Costa Mealha, 8100-410 Loulé",
        city: "Loulé",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-96',
        title: "Segurança Social Braga",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Largo São Francisco, 4700-444 Braga",
        city: "Braga",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-97',
        title: "Segurança Social Porto – Central",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de Entre Quintas, 4050-213 Porto",
        city: "Porto",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-98',
        title: "Segurança Social Vila Nova de Gaia",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida da República, 4430-190 Vila Nova de Gaia",
        city: "Vila Nova de Gaia",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-99',
        title: "Segurança Social Guimarães",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua da Rainha D. Maria II, 4810-227 Guimarães",
        city: "Guimarães",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-100',
        title: "Segurança Social Viana do Castelo",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua da Junqueira, 4900-035 Viana do Castelo",
        city: "Viana do Castelo",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-101',
        title: "Segurança Social Coimbra",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Praça 8 de Maio, 3000-300 Coimbra",
        city: "Coimbra",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-102',
        title: "Segurança Social Aveiro",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de São João, 3800-256 Aveiro",
        city: "Aveiro",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-103',
        title: "Segurança Social Leiria",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Manuel da Silva Cruz, 2410-138 Leiria",
        city: "Leiria",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-104',
        title: "Segurança Social Viseu",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Dr. Alves da Veiga, 3500-713 Viseu",
        city: "Viseu",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-105',
        title: "Segurança Social Lisboa – Alvalade",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida de Roma, 1000-256 Lisboa",
        city: "Lisboa",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-106',
        title: "Segurança Social Amadora",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida Padre Cruz, 2700-559 Amadora",
        city: "Amadora",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-107',
        title: "Segurança Social Sintra",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Bernardino Machado, 2710-443 Sintra",
        city: "Sintra",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-108',
        title: "Segurança Social Almada",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua da Constituição, 2800-068 Almada",
        city: "Almada",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-109',
        title: "Segurança Social Cascais",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida 25 de Abril, 2750-800 Cascais",
        city: "Cascais",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-110',
        title: "Segurança Social Évora",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de São João Evangelista, 7000-678 Évora",
        city: "Évora",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-111',
        title: "Segurança Social Beja",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Fernando Caldeira, 7800-118 Beja",
        city: "Beja",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-112',
        title: "Segurança Social Portalegre",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Luís de Camões, 7300-533 Portalegre",
        city: "Portalegre",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-113',
        title: "Segurança Social Faro – Central",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida da República, 8000-078 Faro",
        city: "Faro",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-114',
        title: "Segurança Social Portimão",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua do Quartel, 8500-505 Portimão",
        city: "Portimão",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-115',
        title: "Segurança Social Loulé",
        category: "Segurança Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Padre Fernando Ferrão, 8100-282 Loulé",
        city: "Loulé",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-116',
        title: "Loja do Cidadão de Lisboa – Picoas",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Av. Fontes Pereira de Melo, 34 B",
        city: "Lisboa",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-117',
        title: "Loja do Cidadão de Almada",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Av. Dom João II, nº 18",
        city: "Almada",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-118',
        title: "Loja do Cidadão de Sintra",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua Dr. Alfredo da Costa, nº 2",
        city: "Sintra",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-119',
        title: "Loja do Cidadão de Cascais",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Largo da República, nº 1",
        city: "Cascais",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-120',
        title: "Loja do Cidadão do Porto – Aliados",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida dos Aliados, 11",
        city: "Porto",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-121',
        title: "Loja do Cidadão de Braga",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Largo São João do Souto",
        city: "Braga",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-122',
        title: "Loja do Cidadão de Guimarães",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua D. João I",
        city: "Guimarães",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-123',
        title: "Loja do Cidadão de Coimbra",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua do Brasil, nº 55",
        city: "Coimbra",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-124',
        title: "Loja do Cidadão de Aveiro",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Largo da Praça do Peixe",
        city: "Aveiro",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-125',
        title: "Loja do Cidadão de Évora",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua da República",
        city: "Évora",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-126',
        title: "Loja do Cidadão de Faro – Centro",
        category: "Residência e Legalização",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida da República, nº 286",
        city: "Faro",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-ref-1',
        title: "Conselho Português para os Refugiados (CPR)",
        category: "Apoio Humanitário e Emergência",
        lat: 38.7753,
        lng: -9.1158,
        distance: 'N/A',
        address: "Quinta do Mocho, Bobadela",
        city: "Lisboa",
        website: "https://cpr.pt",
        avgRating: 5.0,
        ratings: []
    },
    {
        id: 'p-serv-ref-2',
        title: "Banco Alimentar Contra a Fome (Lisboa)",
        category: "Bancos de Alimentos",
        lat: 38.7051,
        lng: -9.1912,
        distance: 'N/A',
        address: "Avenida de Ceuta (Norte), Armazém 1",
        city: "Lisboa",
        website: "https://www.bancoalimentar.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-ref-3',
        title: "Apoio Psicológico - Vítimas de Guerra/Trauma",
        category: "Apoio Psicológico Pós-Trauma",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Centro Nacional de Apoio à Integração de Migrantes (CNAIM)",
        city: "Lisboa",
        website: "https://www.acm.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-ref-4',
        title: "Ordem dos Psicólogos Portugueses",
        category: "Apoio Psicológico Pós-Trauma",
        lat: 38.7303,
        lng: -9.1468,
        distance: 'N/A',
        address: "Avenida Fontes Pereira de Melo, 19D",
        city: "Lisboa",
        website: "https://www.ordemdospsicologos.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-ref-5',
        title: "Saúde 24 (Apoio Médico e Psicológico)",
        category: "Saúde (SNS)",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Linha Telefónica: 808 24 24 24",
        city: "Nacional",
        website: "https://www.sns24.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-ref-6',
        title: "Serviço Jesuíta aos Refugiados (JRS)",
        category: "Apoio Humanitário e Emergência",
        lat: 38.7719,
        lng: -9.1506,
        distance: 'N/A',
        address: "Rua Rogério de Moura, Lote 59",
        city: "Lisboa",
        website: "https://www.jrsportugal.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-ref-7',
        title: "Cruz Vermelha Portuguesa",
        category: "Apoio Psicológico Pós-Trauma",
        lat: 38.7042,
        lng: -9.1627,
        distance: 'N/A',
        address: "Jardim 9 de Abril, 1 a 5",
        city: "Lisboa",
        website: "https://www.cruzvermelha.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-ref-8',
        title: "ACM – Alto Comissariado para as Migrações",
        category: "Comunidade & Apoio",
        lat: 38.7266,
        lng: -9.1351,
        distance: 'N/A',
        address: "Rua Álvaro Coutinho, n.º 14",
        city: "Lisboa",
        website: "https://www.acm.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-127',
        title: "Loja do Cidadão de Setúbal",
        category: "Residência e Legalização",
        lat: 38.5244,
        lng: -8.8931,
        distance: 'N/A',
        address: "Avenida Luísa Todi, n.º 125",
        city: "Setúbal",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-128',
        title: "Loja do Cidadão de Viseu",
        category: "Residência e Legalização",
        lat: 40.6566,
        lng: -7.9125,
        distance: 'N/A',
        address: "Rua Serpa Pinto, n.º 10",
        city: "Viseu",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-129',
        title: "Loja do Cidadão de Bragança",
        category: "Residência e Legalização",
        lat: 41.8058,
        lng: -6.7572,
        distance: 'N/A',
        address: "Praça do Município, n.º 1",
        city: "Bragança",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-130',
        title: "Loja do Cidadão de Castelo Branco",
        category: "Residência e Legalização",
        lat: 39.8222,
        lng: -7.4931,
        distance: 'N/A',
        address: "Campo da Feira",
        city: "Castelo Branco",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-131',
        title: "Loja do Cidadão de Santarém",
        category: "Residência e Legalização",
        lat: 39.2333,
        lng: -8.6833,
        distance: 'N/A',
        address: "Rua de São Bento",
        city: "Santarém",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-132',
        title: "Finanças de Setúbal",
        category: "Finanças & Impostos",
        lat: 38.5244,
        lng: -8.8931,
        distance: 'N/A',
        address: "Avenida Luísa Todi",
        city: "Setúbal",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-133',
        title: "Finanças de Viseu",
        category: "Finanças & Impostos",
        lat: 40.6566,
        lng: -7.9125,
        distance: 'N/A',
        address: "Rua Serpa Pinto",
        city: "Viseu",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-134',
        title: "Finanças de Faro",
        category: "Finanças & Impostos",
        lat: 37.0179,
        lng: -7.9308,
        distance: 'N/A',
        address: "Avenida da República",
        city: "Faro",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-135',
        title: "Segurança Social de Setúbal",
        category: "Segurança Social",
        lat: 38.5244,
        lng: -8.8931,
        distance: 'N/A',
        address: "Rua de Santo António",
        city: "Setúbal",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-136',
        title: "Segurança Social da Guarda",
        category: "Segurança Social",
        lat: 40.5372,
        lng: -7.2658,
        distance: 'N/A',
        address: "Rua do Encontro",
        city: "Guarda",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-137',
        title: "Segurança Social de Vila Real",
        category: "Segurança Social",
        lat: 41.3000,
        lng: -7.7333,
        distance: 'N/A',
        address: "Rua de São Domingos",
        city: "Vila Real",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-138',
        title: "Centro de Emprego de Setúbal",
        category: "Trabalho & Carreira",
        lat: 38.5244,
        lng: -8.8931,
        distance: 'N/A',
        address: "Rua de Goa",
        city: "Setúbal",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-139',
        title: "Centro de Emprego de Évora",
        category: "Trabalho & Carreira",
        lat: 38.5667,
        lng: -7.9000,
        distance: 'N/A',
        address: "Rua de São João Evangelista",
        city: "Évora",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-140',
        title: "Centro de Emprego de Faro",
        category: "Trabalho & Carreira",
        lat: 37.0179,
        lng: -7.9308,
        distance: 'N/A',
        address: "Avenida da República",
        city: "Faro",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-141',
        title: "Loja do Cidadão de Aveiro",
        category: "Residência e Legalização",
        lat: 40.6405,
        lng: -8.6537,
        distance: 'N/A',
        address: "Rua do Batalhão de Caçadores 10",
        city: "Aveiro",
        website: "https://www.portaldocidadao.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-142',
        title: "Finanças de Aveiro",
        category: "Finanças & Impostos",
        lat: 40.6405,
        lng: -8.6537,
        distance: 'N/A',
        address: "Rua do Batalhão de Caçadores 10",
        city: "Aveiro",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-143',
        title: "Segurança Social de Aveiro",
        category: "Segurança Social",
        lat: 40.6405,
        lng: -8.6537,
        distance: 'N/A',
        address: "Rua do Batalhão de Caçadores 10",
        city: "Aveiro",
        website: "https://www.seg-social.pt",
        avgRating: 0.0,
        ratings: []
    },
    {
        id: 'p-serv-144',
        title: "Centro de Emprego de Aveiro",
        category: "Trabalho & Carreira",
        lat: 40.6405,
        lng: -8.6537,
        distance: 'N/A',
        address: "Rua do Batalhão de Caçadores 10",
        city: "Aveiro",
        website: "https://www.iefp.pt",
        avgRating: 0.0,
        ratings: []
    }
];

export const PROTECTED_JOBS: JobPost[] = [
    {
        id: 'p-job-1',
        title: 'Técnico de Instalações Elétricas',
        location: 'Lisboa',
        sourceName: 'IEFP',
        sourceUrl: 'https://iefponline.iefp.pt',
        datePosted: 'Hoje',
        tags: ['Urgente', 'Full-time'],
        category: 'Emprego e Formação',
        workTopic: 'Construção Civil & Engenharia'
    },
    {
        id: 'p-job-2',
        title: 'Auxiliar de Cozinha',
        location: 'Porto',
        sourceName: 'NetEmpregos',
        sourceUrl: 'https://www.net-empregos.com',
        datePosted: 'Hoje',
        tags: ['Entrada Imediata'],
        category: 'Emprego e Formação',
        workTopic: 'Turismo, Hotelaria & Restauração'
    },
    {
        id: 'p-job-3',
        title: 'Operador de Logística',
        location: 'Santarém',
        sourceName: 'IEFP',
        sourceUrl: 'https://iefponline.iefp.pt',
        datePosted: 'Ontem',
        tags: ['Turnos', 'Cais'],
        category: 'Emprego e Formação',
        workTopic: 'Logística, Transportes & Armazém'
    },
    {
        id: 'p-job-4',
        title: 'Assistente Administrativo',
        location: 'Lisboa',
        sourceName: 'NetEmpregos',
        sourceUrl: 'https://www.net-empregos.com',
        datePosted: 'Hoje',
        tags: ['Híbrido'],
        category: 'Emprego e Formação',
        workTopic: 'Administrativo, Gestão & RH'
    },
    {
        id: 'p-job-5',
        title: 'Customer Support (English/Spanish)',
        location: 'Braga',
        sourceName: 'Indeed',
        sourceUrl: 'https://pt.indeed.com',
        datePosted: 'Hoje',
        tags: ['Remoto', 'Línguas'],
        category: 'Emprego e Formação',
        workTopic: 'Comércio, Vendas & Retalho'
    }
];
