import type { Stakeholder } from './types';

export const mockStakeholders: Stakeholder[] = [
  {
    id: 'STK-001',
    name: 'Conselho Nacional de Regulação Energética (CNRE)',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Regulador',
    camada1: 'Federal',
    camada2: 'Executivo',
    camada3: 'Energia',
    camada4: 'Administração Indireta',
    camada5: 'Sede Brasília',
    contatoPrincipal: 'Roberto Almeida',
    cargo: 'Diretor-Geral',
    email: 'roberto.almeida@cnre.gov.ficticio.lgpd',
    telefone: '+55 61 9999-0001',
    influenciaInstitucional: 5,
    exposicaoSBCE: 5,
    legitimidade: 5,
    urgencia: 5,
    capacidadeMobilizacao: 4,
    aberturaDialogo: 5,
    sensibilidadePolitica: 4,
    potencialBloqueio: 2,
    posicaoAtual: 'Defensor',
    jornadaEstagio: 'Defensor do SBCE',
    estrategia: 'Manter engajamento técnico de alto nível',
    proximaAcao: 'Reunião Bilateral sobre Diretrizes',
    objetivoAcao: 'Garantir alinhamento técnico e apoio político',
    ownerInterno: 'Equipe Especial - Energia',
    dataUltimoContato: '2026-05-01',
    tipoInteracaoUltimoContato: 'Reunião Presencial',
    resumoUltimoContato: 'Alinhamento geral sobre o cronograma de implementação do sistema. Feedback muito positivo.',
    proximoContatoPrevisto: '2026-05-15',
    temaPrincipal: 'Estruturação Regulatória',
    temaSBCESecundario: 'Transição Energética',
    janelaRegulatoria: 'Q3 2026',
    participacaoEventos: 'Fórum Nacional Preparatório',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Diário Oficial / Reunião Técnica'
  },
  {
    id: 'STK-002',
    name: 'Federação das Indústrias Sustentáveis (FIS)',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Regulado',
    camada1: 'Privado',
    camada2: 'Setor Produtivo',
    camada3: 'Indústria Transversal',
    camada4: 'Sede São Paulo',
    camada5: 'Departamento de Clima',
    contatoPrincipal: 'Carlos Mendes',
    cargo: 'Presidente',
    email: 'presidencia@fis.org.ficticio.lgpd',
    telefone: '+55 61 8888-0002',
    influenciaInstitucional: 5,
    exposicaoSBCE: 5,
    legitimidade: 4,
    urgencia: 4,
    capacidadeMobilizacao: 5,
    aberturaDialogo: 3,
    sensibilidadePolitica: 5,
    potencialBloqueio: 5,
    posicaoAtual: 'Neutro',
    jornadaEstagio: 'Abordado',
    estrategia: 'Monitorar preocupações com custos operacionais',
    proximaAcao: 'Reunião de alto nível sobre custo de conformidade',
    objetivoAcao: 'Apresentar pacote de mitigação para o setor produtivo',
    ownerInterno: 'Equipe Especial - Indústria',
    dataUltimoContato: '2026-04-20',
    tipoInteracaoUltimoContato: 'Call',
    resumoUltimoContato: 'Apresentação inicial de impactos na indústria. Demonstraram forte preocupação com os custos operacionais.',
    proximoContatoPrevisto: '2026-05-20',
    temaPrincipal: 'Competitividade',
    temaSBCESecundario: 'Custo de Conformidade',
    janelaRegulatoria: 'Q4 2026',
    participacaoEventos: 'Encontro Industrial Anual',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Cooperação Técnica'
  },
  {
    id: 'STK-003',
    name: 'Instituto de Preservação Ambiental (IPA)',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Regulador',
    camada1: 'Federal',
    camada2: 'Executivo',
    camada3: 'Meio Ambiente',
    camada4: 'Sede Brasília',
    camada5: 'Secretaria Executiva',
    contatoPrincipal: 'Juliana Castro',
    cargo: 'Secretária de Sustentabilidade',
    email: 'j.castro@ipa.gov.ficticio.lgpd',
    telefone: '+55 61 7777-0003',
    influenciaInstitucional: 5,
    exposicaoSBCE: 4,
    legitimidade: 5,
    urgencia: 5,
    capacidadeMobilizacao: 4,
    aberturaDialogo: 5,
    sensibilidadePolitica: 4,
    potencialBloqueio: 4,
    posicaoAtual: 'Aliado Ativo',
    jornadaEstagio: 'Aliado ativo',
    estrategia: 'Consolidar regras de governança',
    proximaAcao: 'Fechamento de Acordo de Cooperação',
    objetivoAcao: 'Consolidar regras de governança e monitoramento',
    ownerInterno: 'Equipe Especial - Meio Ambiente',
    dataUltimoContato: '2026-04-28',
    tipoInteracaoUltimoContato: 'Reunião Presencial',
    resumoUltimoContato: 'Discussão sobre metodologias. Aprovou a proposta inicial.',
    proximoContatoPrevisto: '2026-05-10',
    temaPrincipal: 'Metodologias Ambientais',
    temaSBCESecundario: 'Métricas de Monitoramento',
    janelaRegulatoria: 'Q2 2026',
    participacaoEventos: 'Simpósio Ambiental',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Reunião Técnica Oficial'
  },
  {
    id: 'STK-004',
    name: 'Secretaria de Fomento Econômico (SFE)',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Outro',
    camada1: 'Federal',
    camada2: 'Executivo',
    camada3: 'Econômico',
    camada4: 'Sede Brasília',
    camada5: 'Diretoria Técnica',
    contatoPrincipal: 'Fernando Silva',
    cargo: 'Vice-Presidente de Estratégia',
    email: 'fernando.silva@sfe.gov.ficticio.lgpd',
    telefone: '+55 61 6666-0004',
    influenciaInstitucional: 4,
    exposicaoSBCE: 5,
    legitimidade: 4,
    urgencia: 4,
    capacidadeMobilizacao: 3,
    aberturaDialogo: 4,
    sensibilidadePolitica: 5,
    potencialBloqueio: 3,
    posicaoAtual: 'Aliado Potencial',
    jornadaEstagio: 'Priorizado',
    estrategia: 'Evitar sobreposição de normas',
    proximaAcao: 'Mapear convergências e enviar ofício',
    objetivoAcao: 'Evitar sobreposição de normas de financiamento',
    ownerInterno: 'Equipe Especial - Estratégia',
    dataUltimoContato: '2026-04-10',
    tipoInteracaoUltimoContato: 'E-mail Oficial',
    resumoUltimoContato: 'Envio de material preliminar. Aguardando retorno.',
    proximoContatoPrevisto: '2026-05-25',
    temaPrincipal: 'Financiamento',
    temaSBCESecundario: 'Políticas Fiscais',
    janelaRegulatoria: 'Q3 2026',
    participacaoEventos: 'Conselho de Desenvolvimento',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Audiência Pública'
  },
  {
    id: 'STK-005',
    name: 'Banco Nacional de Financiamento (BNF)',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Intermediário',
    camada1: 'Público/Privado',
    camada2: 'Econômico',
    camada3: 'Financeiro',
    camada4: 'Sede Rio de Janeiro',
    camada5: 'Área de Sustentabilidade',
    contatoPrincipal: 'Mariana Costa',
    cargo: 'Diretora Executiva',
    email: 'm.costa@bnf.gov.ficticio.lgpd',
    telefone: '+55 21 5555-0005',
    influenciaInstitucional: 5,
    exposicaoSBCE: 3,
    legitimidade: 4,
    urgencia: 3,
    capacidadeMobilizacao: 5,
    aberturaDialogo: 5,
    sensibilidadePolitica: 3,
    potencialBloqueio: 4,
    posicaoAtual: 'Aliado Ativo',
    jornadaEstagio: 'Engajado',
    estrategia: 'Mobilizar fundos de garantia',
    proximaAcao: 'Workshop Técnico',
    objetivoAcao: 'Definir as regras do fundo de garantia estrutural',
    ownerInterno: 'Equipe Especial - Finanças',
    dataUltimoContato: '2026-04-25',
    tipoInteracaoUltimoContato: 'Reunião Híbrida',
    resumoUltimoContato: 'Alinhamento com diretoria técnica. Excelentes perspectivas de financiamento.',
    proximoContatoPrevisto: '2026-05-12',
    temaPrincipal: 'Fundo Garantidor',
    temaSBCESecundario: 'Linhas de Crédito',
    janelaRegulatoria: 'Q1 2027',
    participacaoEventos: 'Fórum de Inovação',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Relatório Executivo'
  },
  {
    id: 'STK-006',
    name: 'Associação dos Produtores de Base (APB)',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Regulado',
    camada1: 'Privado',
    camada2: 'Setor Produtivo',
    camada3: 'Agropecuária',
    camada4: 'Sede Brasília',
    camada5: 'Relações Governamentais',
    contatoPrincipal: 'Lucia Fernandes',
    cargo: 'Diretora de Relações Institucionais',
    email: 'lucia.f@apb.org.ficticio.lgpd',
    telefone: '+55 11 4444-0006',
    influenciaInstitucional: 4,
    exposicaoSBCE: 5,
    legitimidade: 4,
    urgencia: 5,
    capacidadeMobilizacao: 4,
    aberturaDialogo: 2,
    sensibilidadePolitica: 5,
    potencialBloqueio: 4,
    posicaoAtual: 'Oposição',
    jornadaEstagio: 'Feedback registrado',
    estrategia: 'Mitigar resistência setorial',
    proximaAcao: 'Responder carta de pleitos',
    objetivoAcao: 'Demonstrar abertura aos pontos técnicos levantados',
    ownerInterno: 'Equipe Especial - Agropecuária',
    dataUltimoContato: '2026-04-15',
    tipoInteracaoUltimoContato: 'Reunião Presencial',
    resumoUltimoContato: 'Setor muito resistente à regulação imediata. Enviaram ofício com 10 pleitos.',
    proximoContatoPrevisto: '2026-05-30',
    temaPrincipal: 'Metodologias Agrícolas',
    temaSBCESecundario: 'Custo Operacional',
    janelaRegulatoria: 'Q4 2026',
    participacaoEventos: 'Congresso Anual do Produtor',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Ofício nº 45/2026'
  },
  {
    id: 'STK-007',
    name: 'Sindicato dos Trabalhadores Industriais (STI)',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Legitimador',
    camada1: 'Sociedade Civil',
    camada2: 'Trabalhadores',
    camada3: 'Social',
    camada4: 'Sede São Paulo',
    camada5: 'Diretoria Executiva',
    contatoPrincipal: 'João Batista',
    cargo: 'Secretário-Geral',
    email: 'diretoria@sti.org.ficticio.lgpd',
    telefone: '+55 11 3333-0007',
    influenciaInstitucional: 3,
    exposicaoSBCE: 4,
    legitimidade: 5,
    urgencia: 3,
    capacidadeMobilizacao: 5,
    aberturaDialogo: 4,
    sensibilidadePolitica: 3,
    potencialBloqueio: 3,
    posicaoAtual: 'Neutro',
    jornadaEstagio: 'Identificado',
    estrategia: 'Abordagem focada em empregos',
    proximaAcao: 'Agendar primeiro call de aproximação',
    objetivoAcao: 'Explicar que o sistema preserva empregos na transição',
    ownerInterno: 'Equipe Especial - Social',
    temaPrincipal: 'Transição Justa',
    temaSBCESecundario: 'Empregabilidade',
    janelaRegulatoria: 'Q4 2026',
    participacaoEventos: 'Assembleia Trabalhista',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Nota Sindical'
  },
  {
    id: 'STK-008',
    name: 'Conselho Nacional do Clima (CNC)',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Outro',
    camada1: 'Federal',
    camada2: 'Executivo',
    camada3: 'Consultivo',
    camada4: 'Sede Brasília',
    camada5: 'Comitê Científico',
    contatoPrincipal: 'Marcos Nogueira',
    cargo: 'Coordenador Científico',
    email: 'marcos.n@cnc.gov.ficticio.lgpd',
    telefone: '+55 61 2222-0008',
    influenciaInstitucional: 3,
    exposicaoSBCE: 4,
    legitimidade: 5,
    urgencia: 2,
    capacidadeMobilizacao: 3,
    aberturaDialogo: 5,
    sensibilidadePolitica: 2,
    potencialBloqueio: 2,
    posicaoAtual: 'Aliado Potencial',
    jornadaEstagio: 'Aliado potencial',
    estrategia: 'Validação científica',
    proximaAcao: 'Reunião de nivelamento',
    objetivoAcao: 'Garantir validação técnica e evitar ruídos',
    ownerInterno: 'Equipe Especial - Meio Ambiente',
    dataUltimoContato: '2026-04-10',
    tipoInteracaoUltimoContato: 'Reunião Híbrida',
    resumoUltimoContato: 'Mostraram grande interesse em colaborar com o comitê científico.',
    proximoContatoPrevisto: '2026-05-20',
    temaPrincipal: 'Ciência e Tecnologia',
    temaSBCESecundario: 'Validação Científica',
    janelaRegulatoria: 'Q2 2026',
    participacaoEventos: 'Conferência Climática',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Portaria de Nomeação'
  },
  {
    id: 'STK-009',
    name: 'Federação dos Bancos Comerciais (FBC)',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Intermediário',
    camada1: 'Privado',
    camada2: 'Econômico',
    camada3: 'Financeiro',
    camada4: 'Sede São Paulo',
    camada5: 'Presidência',
    contatoPrincipal: 'Lucas Almeida',
    cargo: 'Presidente',
    email: 'diretoria@fbc.org.ficticio.lgpd',
    telefone: '+55 11 1111-0009',
    influenciaInstitucional: 5,
    exposicaoSBCE: 3,
    legitimidade: 4,
    urgencia: 4,
    capacidadeMobilizacao: 4,
    aberturaDialogo: 4,
    sensibilidadePolitica: 5,
    potencialBloqueio: 3,
    posicaoAtual: 'Aliado Ativo',
    jornadaEstagio: 'Engajado',
    estrategia: 'Mobilizar capital privado',
    proximaAcao: 'Criar GT conjunto para finanças sustentáveis',
    objetivoAcao: 'Mobilizar capital privado para a transição',
    ownerInterno: 'Equipe Especial - Finanças',
    dataUltimoContato: '2026-04-05',
    tipoInteracaoUltimoContato: 'Evento',
    resumoUltimoContato: 'Receptivos. Querem regras claras para contabilizar investimentos ESG.',
    proximoContatoPrevisto: '2026-05-15',
    temaPrincipal: 'Ativos Ambientais',
    temaSBCESecundario: 'Mercado Secundário',
    janelaRegulatoria: 'Q2 2026',
    participacaoEventos: 'Fórum Financeiro Anual',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Agenda FBC 2026'
  },
  {
    id: 'STK-010',
    name: 'Organização Não Governamental VerdeVida',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Legitimador',
    camada1: 'Sociedade Civil',
    camada2: 'Terceiro Setor',
    camada3: 'Meio Ambiente',
    camada4: 'Sede Rio de Janeiro',
    camada5: 'Campanhas',
    contatoPrincipal: 'Camila Rocha',
    cargo: 'Diretora de Campanhas',
    email: 'c.rocha@verdevida.org.ficticio.lgpd',
    telefone: '+55 11 0000-0010',
    influenciaInstitucional: 3,
    exposicaoSBCE: 4,
    legitimidade: 5,
    urgencia: 4,
    capacidadeMobilizacao: 5,
    aberturaDialogo: 2,
    sensibilidadePolitica: 4,
    potencialBloqueio: 4,
    posicaoAtual: 'Neutro',
    jornadaEstagio: 'Cético',
    estrategia: 'Garantir transparência de dados',
    proximaAcao: 'Enviar material com transparência de dados',
    objetivoAcao: 'Mitigar críticas sobre o modelo de verificação',
    ownerInterno: 'Equipe Especial - Comunicação',
    dataUltimoContato: '2026-04-12',
    tipoInteracaoUltimoContato: 'Call',
    resumoUltimoContato: 'Tom crítico. Preocupação com integridade do sistema e transparência.',
    proximoContatoPrevisto: '2026-05-18',
    temaPrincipal: 'Transparência',
    temaSBCESecundario: 'Integridade Ambiental',
    janelaRegulatoria: 'Contínuo',
    participacaoEventos: 'Protestos Virtuais / Painéis',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Relatório VerdeVida 2026'
  },
  {
    id: 'STK-011',
    name: 'Comitê Parlamentar de Desenvolvimento Sustentável',
    tipoRegistro: 'Instituição',
    papelSBCE: 'Outro',
    camada1: 'Federal',
    camada2: 'Legislativo',
    camada3: 'Político',
    camada4: 'Congresso Nacional',
    camada5: 'Câmara dos Deputados',
    contatoPrincipal: 'Deputado Henrique Soares',
    cargo: 'Presidente da Frente',
    email: 'dep.henrique@camara.gov.ficticio.lgpd',
    telefone: '+55 61 3215-0011',
    influenciaInstitucional: 5,
    exposicaoSBCE: 5,
    legitimidade: 5,
    urgencia: 5,
    capacidadeMobilizacao: 4,
    aberturaDialogo: 1,
    sensibilidadePolitica: 5,
    potencialBloqueio: 5,
    posicaoAtual: 'Oposição',
    jornadaEstagio: 'Opositor',
    estrategia: 'Articulação intensiva via Assessoria',
    proximaAcao: 'Articulação intensiva via Assessoria Parlamentar',
    objetivoAcao: 'Desbloquear a pauta na Comissão',
    ownerInterno: 'Equipe Especial - Legislativo',
    dataUltimoContato: '2026-04-22',
    tipoInteracaoUltimoContato: 'Audiência Pública',
    resumoUltimoContato: 'Forte oposição ao formato atual do texto. Pedido de vistas.',
    proximoContatoPrevisto: '2026-05-05',
    temaPrincipal: 'Custos Tributários',
    temaSBCESecundario: 'Tramitação Legislativa',
    janelaRegulatoria: 'Q2 2026',
    participacaoEventos: 'Comissão Especial',
    dataAtualizacao: '2026-05-06',
    atualizadoPor: 'DSMT',
    fonteInformacao: 'Notas Taquigráficas'
  }
];
