import { Course } from '../types';

export const IEFP_MASSIVE_DATABASE: Course[] = [
    // --- IEFP ORIGINAL ---
    { id: 'mx-1', title: 'Técnico de Cozinha e Pastelaria', description: 'Formação certificada pelo IEFP para restauração e hotelaria de luxo.', category: 'Emprego e Formação', type: 'Presencial', duration: '1500h', image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'mx-2', title: 'Operador de Empilhadores e Logística', description: 'Certificação obrigatória para trabalho em armazéns e centros de distribuição.', category: 'Emprego e Formação', type: 'Presencial', duration: '120h', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao-modular' },
    { id: 'mx-3', title: 'Técnico de Instalações Elétricas Industriais', description: 'Especialização em manutenção elétrica fabril e sistemas de potência.', category: 'Emprego e Formação', type: 'Híbrido', duration: '2200h', image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem' },
    { id: 'mx-4', title: 'Auxiliar de Saúde e Geriatria', description: 'Capacitação para apoio em lares, hospitais e cuidados domiciliários.', category: 'Saúde (SNS)', type: 'Presencial', duration: '1100h', image: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'mx-5', title: 'Português Língua de Acolhimento (PLA)', description: 'Curso essencial para integração de estrangeiros. Níveis A1 a B2.', category: 'Educação e Reconhecimento', type: 'Online / Presencial', duration: '150h', image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/portugues-lingua-de-acolhimento' },
    { id: 'mx-6', title: 'Desenvolvimento Web Full-Stack', description: 'Programação moderna (React, Node.js) com elevada procura no mercado IT.', category: 'Tecnologia & Ética Digital', type: 'Online', duration: '1200h', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-7', title: 'Cabeleireiro de Homem e Barbeiro', description: 'Técnicas modernas de corte e barbearia. Formação prática intensiva.', category: 'Saúde (SNS)', type: 'Presencial', duration: '800h', image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-8', title: 'Técnico de Redes Elétricas de Baixa e Média Tensão', description: 'Manutenção de infraestruturas elétricas públicas e privadas.', category: 'Emprego e Formação', type: 'Presencial', duration: '1400h', image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem' },
    { id: 'mx-9', title: 'Operador de Supermercado e Armazém', description: 'Logística de retalho, reposição e atendimento ao público.', category: 'Emprego e Formação', type: 'Presencial', duration: '300h', image: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-10', title: 'Técnico de Automação e Instrumentação', description: 'Programação de PLCs e controlo industrial avançado.', category: 'Tecnologia & Ética Digital', type: 'Presencial', duration: '3500h', image: 'https://images.unsplash.com/photo-1581092580497-e0d23cb611b8?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem' },

    // --- DGES / ENSINO SUPERIOR (RELEVANTES PARA IMIGRANTES) ---
    { id: 'dg-1', title: 'Licenciatura em Enfermagem', description: 'Acesso à carreira de enfermagem em Portugal. Elevada empregabilidade.', category: 'Saúde (SNS)', type: 'Presencial', duration: '4 Anos', image: 'https://images.unsplash.com/photo-1505751172107-57322a3e23dd?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=E' },
    { id: 'dg-2', title: 'Licenciatura em Engenharia Informática', description: 'Formação superior em software, redes e sistemas. Base do mercado tech.', category: 'Tecnologia & Ética Digital', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=E' },
    { id: 'dg-3', title: 'Licenciatura em Gestão de Empresas', description: 'Competências em administração, finanças e marketing.', category: 'Emprego e Formação', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=G' },
    { id: 'dg-4', title: 'Licenciatura em Serviço Social', description: 'Mediação social e apoio comunitário. Fundamental para integração.', category: 'Direitos & Apoio Social', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=S' },
    { id: 'dg-5', title: 'Licenciatura em Direito', description: 'Formação em leis portuguesas e europeias. Carreira jurídica.', category: 'Residência & Vistos', type: 'Presencial', duration: '4 Anos', image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=D' },
    { id: 'dg-6', title: 'Mestrado em Saúde Pública', description: 'Especialização para profissionais de saúde em gestão comunitária.', category: 'Saúde (SNS)', type: 'Pós-graduação', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=M' },
    { id: 'dg-7', title: 'Licenciatura em Turismo', description: 'Gestão hoteleira e animação turística. Principal setor de Portugal.', category: 'Emprego e Formação', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=T' },
    { id: 'dg-8', title: 'Licenciatura em Psicologia', description: 'Apoio à saúde mental e intervenção psicológica.', category: 'Saúde (SNS)', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=P' },
    { id: 'dg-9', title: 'Licenciatura em Contabilidade', description: 'Fiscalidade e gestão de contas para empresas e particulares.', category: 'Finanças & Impostos', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=C' },
    { id: 'dg-10', title: 'Mestrado Integrado em Arquitetura', description: 'Design de edifícios e planeamento urbano.', category: 'Emprego e Formação', type: 'Presencial', duration: '5 Anos', image: 'https://images.unsplash.com/photo-1503387762-592dea58ef23?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp?letra=A' },

    // --- CURSOS TÉCNICOS SUPERIORES (TeSP - DGES) ---
    { id: 'ts-1', title: 'TeSP em Cibersegurança', description: 'Proteção de sistemas e redes contra ataques digitais.', category: 'Tecnologia & Ética Digital', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'ts-2', title: 'TeSP em Energias Renováveis', description: 'Manutenção de sistemas solares e eólicos.', category: 'Emprego e Formação', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1466611653911-954ffea11271?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'ts-3', title: 'TeSP em Apoio à Infância', description: 'Educação em creches e jardins de infância.', category: 'Educação e Reconhecimento', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'ts-4', title: 'TeSP em Gestão de Redes Sociais', description: 'Marketing digital e comunicação corporativa.', category: 'Tecnologia & Ética Digital', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'ts-5', title: 'TeSP em Viticultura e Enologia', description: 'Produção de vinho e gestão de vinhas.', category: 'Emprego e Formação', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1510850463344-d9ca985597be?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },

    // --- OUTROS IEFP ADICIONAIS ---
    { id: 'mx-21', title: 'Condutor de Pesados de Mercadorias (CAM)', description: 'Certificação para transporte internacional de mercadorias.', category: 'Emprego e Formação', type: 'Presencial', duration: '140h', image: 'https://images.unsplash.com/photo-1519003722824-192d992a6023?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-22', title: 'Instalador de Ar Condicionado e Refrigeração', description: 'Técnico de climatização residencial e industrial.', category: 'Emprego e Formação', type: 'Presencial', duration: '800h', image: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-23', title: 'Secretariado e Apoio Administrativo', description: 'Gestão de escritório, arquivo e atendimento bilíngue.', category: 'Emprego e Formação', type: 'Híbrido', duration: '600h', image: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-24', title: 'Operador de Máquinas Agrícolas', description: 'Condução e manutenção de tratores e alfaias.', category: 'Emprego e Formação', type: 'Presencial', duration: '250h', image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-25', title: 'Técnico de Logística e Gestão de Stocks', description: 'Otimização de cadeias de abastecimento e inventários.', category: 'Emprego e Formação', type: 'Híbrido', duration: '900h', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    
    // --- NOVOS CURSOS V2026.GOLD (EXPANSÃO) ---
    { id: 'ts-6', title: 'TeSP em Marketing Digital', description: 'Estratégias de SEO, SEM e gestão de campanhas online.', category: 'Tecnologia & Ética Digital', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'ts-7', title: 'TeSP em Gestão de Redes e Sistemas', description: 'Configuração e manutenção de infraestruturas de rede corporativas.', category: 'Tecnologia & Ética Digital', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc51?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'ts-8', title: 'TeSP em Cozinha e Produção Alimentar', description: 'Gestão técnica de cozinhas e preparação de menus avançados.', category: 'Emprego e Formação', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'ts-9', title: 'TeSP em Automação e Robótica', description: 'Programação de robôs e sistemas automáticos industriais.', category: 'Tecnologia & Ética Digital', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'ts-10', title: 'TeSP em Design de Produto', description: 'Criação e modelação de novos produtos industriais e de consumo.', category: 'Emprego e Formação', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1581291417004-6e7398a1cf3d?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },

    { id: 'dg-11', title: 'Licenciatura em Engenharia Eletrotécnica', description: 'Sistemas de energia, eletrónica e telecomunicações.', category: 'Emprego e Formação', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'dg-12', title: 'Licenciatura em Engenharia Civil', description: 'Projeto e gestão de obras de construção civil e infraestruturas.', category: 'Emprego e Formação', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1503387762-592dea58ef23?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'dg-13', title: 'Licenciatura em Economia', description: 'Análise de mercados, políticas públicas e gestão financeira.', category: 'Finanças & Impostos', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1611974714851-4607376b636c?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'dg-14', title: 'Licenciatura em Comunicação Social', description: 'Jornalismo, assessoria de imprensa e produção de conteúdos.', category: 'Tecnologia & Ética Digital', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'dg-15', title: 'Licenciatura em Fisioterapia', description: 'Reabilitação física e promoção da saúde em contexto clínico.', category: 'Saúde (SNS)', type: 'Presencial', duration: '4 Anos', image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    { id: 'dg-16', title: 'Licenciatura em Marketing', description: 'Gestão de marcas, comportamento do consumidor e vendas.', category: 'Emprego e Formação', type: 'Presencial', duration: '3 Anos', image: 'https://images.unsplash.com/photo-1533750516457-a7f992034fce?w=400&q=50', isIefpSynced: false, link: 'https://www.dges.gov.pt/guias/indcst.asp' },
    
    { id: 'mx-26', title: 'Soldador Especializado', description: 'Técnicas de soldadura TIG, MIG/MAG para estruturas metálicas.', category: 'Emprego e Formação', type: 'Presencial', duration: '400h', image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-27', title: 'Mecatrónico Automóvel', description: 'Diagnóstico e reparação de sistemas eletrónicos em veículos.', category: 'Emprego e Formação', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-28', title: 'Técnico de Estética e Cosmetologia', description: 'Cuidados de rosto, corpo e tratamentos estéticos avançados.', category: 'Saúde (SNS)', type: 'Presencial', duration: '900h', image: 'https://images.unsplash.com/photo-1570172619245-728f1146522e?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-29', title: 'Auxiliar de Farmácia', description: 'Apoio na dispensa de medicamentos e gestão de stock farmacêutico.', category: 'Saúde (SNS)', type: 'Presencial', duration: '600h', image: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-30', title: 'Jardineiro e Espaços Verdes', description: 'Manutenção de jardins públicos, podas e sistemas de rega.', category: 'Emprego e Formação', type: 'Presencial', duration: '300h', image: 'https://images.unsplash.com/photo-1558904541-efa8c196b27d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-31', title: 'Técnico de Energias Renováveis (Solar)', description: 'Instalação de painéis fotovoltaicos e sistemas térmicos.', category: 'Emprego e Formação', type: 'Presencial', duration: '800h', image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-32', title: 'Carpinteiro de Limpos', description: 'Fabrico e montagem de mobiliário e acabamentos em madeira.', category: 'Emprego e Formação', type: 'Presencial', duration: '1100h', image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-33', title: 'Serralheiro Civil', description: 'Trabalho em ferro, alumínio e inox para construção.', category: 'Emprego e Formação', type: 'Presencial', duration: '1000h', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-34', title: 'Técnico de Frio e Climatização', description: 'Manutenção de ar condicionado e sistemas de refrigeração comercial.', category: 'Emprego e Formação', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-35', title: 'Canalizador e Sistemas de Aquecimento', description: 'Instalação de redes de águas, esgotos e aquecimento central.', category: 'Emprego e Formação', type: 'Presencial', duration: '900h', image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-36', title: 'Pintor de Construção Civil', description: 'Técnicas de pintura, envernizamento e revestimento de paredes.', category: 'Emprego e Formação', type: 'Presencial', duration: '400h', image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-37', title: 'Técnico de Manutenção de Estruturas Metálicas', description: 'Segurança e reparação de grandes infraestruturas metálicas.', category: 'Emprego e Formação', type: 'Presencial', duration: '700h', image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-38', title: 'Técnico de Gás e Redes Fluídas', description: 'Instalação certificada de redes de gás doméstico e industrial.', category: 'Emprego e Formação', type: 'Presencial', duration: '600h', image: 'https://images.unsplash.com/photo-1585713181935-d5f622cc2415?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-39', title: 'Operador de Máquinas de Movimentação de Terras', description: 'Condução de retroescavadoras e máquinas pesadas de obra.', category: 'Emprego e Formação', type: 'Presencial', duration: '300h', image: 'https://images.unsplash.com/photo-1579412691525-2d7f9b7ff331?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-40', title: 'Técnico de Gestão de Resíduos e Ambiente', description: 'Processamento de resíduos e políticas de sustentabilidade.', category: 'Residência & Vistos', type: 'Híbrido', duration: '500h', image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-41', title: 'Técnico de Som e Espetáculos', description: 'Operação de áudio para eventos, concertos e teatro.', category: 'Tecnologia & Ética Digital', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-42', title: 'Técnico de Multimédia', description: 'Criação de conteúdos digitais, vídeo e animação.', category: 'Tecnologia & Ética Digital', type: 'Híbrido', duration: '1400h', image: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    // --- TRANSIÇÃO ECOLÓGICA, CRISE CLIMÁTICA E REFUGIADOS (V2026.GOLD) ---
    { id: 'mx-43', title: 'Técnico de Instalação de Sistemas Solares Fotovoltaicos', description: 'Dimensionamento, montagem e manutenção de painéis fotovoltaicos residenciais e industriais em Portugal.', category: 'Emprego e Formação', type: 'Presencial', duration: '600h', image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'dg-17', title: 'Especialização em Hidrogénio Verde e Transição Energética', description: 'Curso técnico avançado abrangendo a cadeia de valor do hidrogénio verde, tecnologias de eletrólise e descarbonização industrial.', category: 'Emprego e Formação', type: 'Online', duration: '120h', image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=400&q=50', isIefpSynced: false, link: 'https://www.ipportalegre.pt/pt/oferta-formativa/pos-graduacoes/pg-hidrogenio-e-gases-renovaveis/' },
    { id: 'ts-11', title: 'TeSP em Tecnologias Ambientais e Energia Eólica', description: 'Gestão de aerogeradores, manutenção de parques eólicos e análise de impacto ambiental em comunidades.', category: 'Emprego e Formação', type: 'Politécnico', duration: '2 Anos', image: 'https://images.unsplash.com/photo-1466611653911-954ffea11271?w=400&q=50', isIefpSynced: false, link: 'https://www.ipleiria.pt/curso/energias-renovaveis-e-eficiencia-energetica/' },
    { id: 'dg-18', title: 'Direitos Humanos, Migração e Refugiados Climáticos', description: 'Enquadramento jurídica nacional e internacional para a proteção de populações deslocadas devido a desastres ambientais e alterações climáticas.', category: 'Direitos & Apoio Social', type: 'Online', duration: '80h', image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400&q=50', isIefpSynced: false, link: 'https://direito.uminho.pt/pt/Ensino/Pos-Graduacoes/Paginas/Direitos-Humanos.aspx' },
    { id: 'dg-19', title: 'Acolhimento de Populações e Intervenção de Emergência Climática', description: 'Formação humanitária para técnicos de serviço social e voluntários no planeamento de abrigos, logística de emergência e apoio psicossocial.', category: 'Ajuda Humanitária', type: 'Presencial', duration: '150h', image: 'https://images.unsplash.com/photo-1469571486090-76f1875e7d20?w=400&q=50', isIefpSynced: false, link: 'https://www.cruzvermelha.pt/formacao/cursos.html' },
    // --- CURSOS DE INTELIGÊNCIA ARTIFICIAL E NOVAS TECNOLOGIAS (IEFP CERTIFICADOS) ---
    { id: 'iefp-ia-1', title: 'Técnico de Inteligência Artificial e Data Science', description: 'Curso de especialização tecnológica focado em recolha de dados, modelação preditiva e implementação de algoritmos de Machine Learning no tecido empresarial.', category: 'Tecnologia & Ética Digital', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'iefp-ia-2', title: 'Introdução à Inteligência Artificial Generativa e Prompt Engineering', description: 'Formação modular direcionada para a otimização de fluxos de trabalho empresariais recorrendo a ferramentas de IA Generativa de texto e imagem.', category: 'Tecnologia & Ética Digital', type: 'Online', duration: '50h', image: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao-modular' },
    { id: 'iefp-ia-3', title: 'Técnico de Internet das Coisas (IoT) e Cidades Inteligentes', description: 'Desenvolvimento e programação de microcontroladores, sensores e integração de dados na nuvem para soluções de domótica e planeamento urbano.', category: 'Tecnologia & Ética Digital', type: 'Híbrido', duration: '800h', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'iefp-ia-4', title: 'Introdução ao Blockchain e Smart Contracts para Negócios', description: 'Formação modular sobre tecnologias descentralizadas, criptomoedas e segurança em transações de dados de nova geração.', category: 'Tecnologia & Ética Digital', type: 'Online', duration: '75h', image: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao-modular' }
];
