import { Course } from '../types';

export const IEFP_MASSIVE_DATABASE: Course[] = [
    // --- FORMAÇÃO PROFISSIONAL IEFP CERTIFICADA ---
    { id: 'mx-1', title: 'Técnico de Cozinha e Pastelaria', description: 'Formação certificada pelo IEFP para restauração e hotelaria de luxo.', category: 'Emprego e Formação', type: 'Presencial', duration: '1500h', image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'mx-2', title: 'Operador de Empilhadores e Logística', description: 'Certificação obrigatória para trabalho em armazéns e centros de distribuição.', category: 'Emprego e Formação', type: 'Presencial', duration: '120h', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao-modular' },
    { id: 'mx-3', title: 'Técnico de Instalações Elétricas Industriais', description: 'Especialização em manutenção elétrica fabril e sistemas de potência.', category: 'Emprego e Formação', type: 'Híbrido', duration: '2200h', image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem' },
    { id: 'mx-4', title: 'Auxiliar de Saúde e Geriatria', description: 'Capacitação para apoio em lares, hospitais e cuidados domiciliários.', category: 'Saúde (SNS)', type: 'Presencial', duration: '1100h', image: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'mx-5', title: 'Português Língua de Acolhimento (PLA)', description: 'Curso essencial para integração de estrangeiros. Níveis A1 a B2.', category: 'Educação e Reconhecimento', type: 'Online / Presencial', duration: '150h', image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/portugues-lingua-de-acolhimento' },

    { id: 'mx-6', title: 'Desenvolvimento Web Full-Stack', description: 'Programação moderna (React, Node.js) com elevada procura no mercado IT.', category: 'Tecnologia & Ética Digital', type: 'Online', duration: '1200h', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-7', title: 'Cabeleireiro de Homem e Barbeiro', description: 'Técnicas modernas de corte e barbearia. Formação prática intensiva.', category: 'Saúde (SNS)', type: 'Presencial', duration: '800h', image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-8', title: 'Técnico de Redes Elétricas de Baixa e Média Tensão', description: 'Manutenção de infraestruturas elétricas públicas e privadas.', category: 'Emprego e Formação', type: 'Presencial', duration: '1400h', image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem' },
    { id: 'mx-9', title: 'Operador de Supermercado e Armazém', description: 'Logística de retalho, reposição e atendimento ao público.', category: 'Emprego e Formação', type: 'Presencial', duration: '300h', image: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-10', title: 'Técnico de Automação e Instrumentação', description: 'Programação de PLCs e controlo industrial avançado.', category: 'Tecnologia & Ética Digital', type: 'Presencial', duration: '3500h', image: 'https://images.unsplash.com/photo-1581092580497-e0d23cb611b8?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem' },

    // --- FORMAÇÃO MODULAR E TÉCNICA ESPECIALIZADA ---
    { id: 'mx-21', title: 'Condutor de Pesados de Mercadorias (CAM)', description: 'Certificação para transporte internacional de mercadorias.', category: 'Emprego e Formação', type: 'Presencial', duration: '140h', image: 'https://images.unsplash.com/photo-1519003722824-192d992a6023?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-22', title: 'Instalador de Ar Condicionado e Refrigeração', description: 'Técnico de climatização residencial e industrial.', category: 'Emprego e Formação', type: 'Presencial', duration: '800h', image: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-23', title: 'Secretariado e Apoio Administrativo', description: 'Gestão de escritório, arquivo e atendimento bilíngue.', category: 'Emprego e Formação', type: 'Híbrido', duration: '600h', image: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-24', title: 'Operador de Máquinas Agrícolas', description: 'Condução e manutenção de tratores e alfaias.', category: 'Emprego e Formação', type: 'Presencial', duration: '250h', image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-25', title: 'Técnico de Logística e Gestão de Stocks', description: 'Otimização de cadeias de abastecimento e inventários.', category: 'Emprego e Formação', type: 'Híbrido', duration: '900h', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-26', title: 'Soldador Especializado', description: 'Técnicas de soldadura TIG, MIG/MAG para estruturas metálicas.', category: 'Emprego e Formação', type: 'Presencial', duration: '400h', image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-27', title: 'Mecatrónico Automóvel', description: 'Diagnóstico e reparação de sistemas eletrónicos em veículos.', category: 'Emprego e Formação', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-28', title: 'Técnico de Estética e Cosmetologia', description: 'Cuidados de rosto, corpo e tratamentos estéticos avançados.', category: 'Saúde (SNS)', type: 'Presencial', duration: '900h', image: 'https://images.unsplash.com/photo-1570172619245-728f1146522e?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-29', title: 'Auxiliar de Farmácia', description: 'Apoio na dispensa de medicamentos e gestão de stock farmacêutico.', category: 'Saúde (SNS)', type: 'Presencial', duration: '600h', image: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-30', title: 'Jardineiro e Espaços Verdes', description: 'Manutenção de jardins públicos, podas e sistemas de rega.', category: 'Emprego e Formação', type: 'Presencial', duration: '300h', image: 'https://images.unsplash.com/photo-1558904541-efa8c196b27d?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-31', title: 'Técnico de Energias Renováveis (Solar)', description: 'Instalação de painéis fotovoltaicos e sistemas térmicos.', category: 'Emprego e Formação', type: 'Presencial', duration: '800h', image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-32', title: 'Carpinteiro de Limpos', description: 'Fabrico e montagem de mobiliário e acabamentos em madeira.', category: 'Emprego and Formação', type: 'Presencial', duration: '1100h', image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-33', title: 'Serralheiro Civil', description: 'Trabalho em ferro, alumínio e inox para construção.', category: 'Emprego e Formação', type: 'Presencial', duration: '1000h', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-34', title: 'Técnico de Frio e Climatização', description: 'Manutenção de ar condicionado e sistemas de refrigeração comercial.', category: 'Emprego e Formação', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-35', title: 'Canalizador e Sistemas de Aquecimento', description: 'Instalação de redes de águas, esgotos e aquecimento central.', category: 'Emprego e Formação', type: 'Presencial', duration: '900h', image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-36', title: 'Pintor de Construção Civil', description: 'Técnicas de pintura, envernizamento e revestimento de paredes.', category: 'Emprego e Formação', type: 'Presencial', duration: '400h', image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-37', title: 'Técnico de Manutenção de Estruturas Metálicas', description: 'Segurança e reparação de grandes infraestruturas metálicas.', category: 'Emprego e Formação', type: 'Presencial', duration: '700h', image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-38', title: 'Técnico de Gás e Redes Fluídas', description: 'Instalação certificada de redes de gás doméstico e industrial.', category: 'Emprego e Formação', type: 'Presencial', duration: '600h', image: 'https://images.unsplash.com/photo-1585713181935-d5f622cc2415?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-39', title: 'Operador de Máquinas de Movimentação de Terras', description: 'Condução de retroescavadoras e máquinas pesadas de obra.', category: 'Emprego e Formação', type: 'Presencial', duration: '300h', image: 'https://images.unsplash.com/photo-1579412691525-2d7f9b7ff331?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-40', title: 'Técnico de Gestão de Resíduos e Ambiente', description: 'Processamento de resíduos e políticas de sustentabilidade.', category: 'Residência & Vistos', type: 'Híbrido', duration: '500h', image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-41', title: 'Técnico de Som e Espetáculos', description: 'Operação de áudio para eventos, concertos e teatro.', category: 'Tecnologia & Ética Digital', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-42', title: 'Técnico de Multimédia', description: 'Criação de conteúdos digitais, vídeo e animação.', category: 'Tecnologia & Ética Digital', type: 'Híbrido', duration: '1400h', image: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'mx-43', title: 'Técnico de Instalação de Sistemas Solares Fotovoltaicos', description: 'Dimensionamento, montagem e manutenção de painéis fotovoltaicos residenciais e industriais em Portugal.', category: 'Emprego e Formação', type: 'Presencial', duration: '600h', image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },

    // --- CURSOS DE INTELIGÊNCIA ARTIFICIAL E NOVAS TECNOLOGIAS (IEFP CERTIFICADOS) ---
    { id: 'iefp-ia-1', title: 'Técnico de Inteligência Artificial e Data Science', description: 'Curso de especialização tecnológica focado em recolha de dados, modelação preditiva e implementação de algoritmos de Machine Learning no tecido empresarial.', category: 'Tecnologia & Ética Digital', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'iefp-ia-2', title: 'Introdução à Inteligência Artificial Generativa e Prompt Engineering', description: 'Formação modular direcionada para a otimização de fluxos de trabalho empresariais recorrendo a ferramentas de IA Generativa de texto e imagem.', category: 'Tecnologia & Ética Digital', type: 'Online', duration: '50h', image: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao-modular' },
    { id: 'iefp-ia-3', title: 'Técnico de Internet das Coisas (IoT) e Cidades Inteligentes', description: 'Desenvolvimento e programação de microcontroladores, sensores e integração de dados na nuvem para soluções de domótica e planeamento urbano.', category: 'Tecnologia & Ética Digital', type: 'Híbrido', duration: '800h', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'iefp-ia-4', title: 'Introdução ao Blockchain e Smart Contracts para Negócios', description: 'Formação modular sobre tecnologias descentralizadas, criptomoedas e segurança em transações de dados de nova geração.', category: 'Tecnologia & Ética Digital', type: 'Online', duration: '75h', image: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao-modular' },

    // --- CURSOS DE HABITAÇÃO, EDIFÍCIOS E IMOBILIÁRIO (IEFP CERTIFICADOS) ---
    { id: 'iefp-hou-1', title: 'Técnico de Manutenção e Gestão de Edifícios Residenciais', description: 'Gestão técnica de infraestruturas habitacionais, manutenção preventiva predial e regulamentos de condomínio.', category: 'Habitação & Casa', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'iefp-hou-2', title: 'Mediação Imobiliária, Arrendamento e Gestão de Condomínios', description: 'Formação profissional em legislação de arrendamento urbano, contratos habitacionais e mediação imobiliária em Portugal.', category: 'Habitação & Casa', type: 'Híbrido', duration: '300h', image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'iefp-hou-3', title: 'Eficiência Energética e Reabilitação Sustentável de Habitações', description: 'Auditorias energéticas e soluções de isolamento térmico e reabilitação de habitações em Portugal.', category: 'Habitação & Casa', type: 'Online', duration: '200h', image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao-modular' },

    // --- CURSOS DE COMUNIDADE, ANIMAÇÃO E MEDIAÇÃO INTERCULTURAL (IEFP CERTIFICADOS) ---
    { id: 'iefp-com-1', title: 'Animação Sociocultural e Dinamização Comunitária', description: 'Planeamento e execução de projetos comunitários de inclusão social, mediação de bairros e eventos culturais.', category: 'Comunidade & Histórias', type: 'Presencial', duration: '1100h', image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-efa' },
    { id: 'iefp-com-2', title: 'Mediação Intercultural e Acolhimento Comunitário de Imigrantes', description: 'Competências de mediação linguística, diálogo multicultural e facilitação de integração nos centros de acolhimento locais.', category: 'Comunidade & Histórias', type: 'Híbrido', duration: '250h', image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'iefp-com-3', title: 'Comunicação Comunitária, Podcasts e Criação de Conteúdos Digitais', description: 'Técnicas de narrativa digital, entrevistas e comunicação para projetos sociais e comunidades migrantes.', category: 'Comunidade & Histórias', type: 'Online', duration: '150h', image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&q=50', isIefpSynced: true, link: 'https://www.iefp.pt/formacao-modular' }
];
