
export interface JobSource {
    id: string;
    name: string;
    url: string;
    category: string;
    trust_level: number; // 1-10 (10 = Oficial/Governamental)
}

export const JOB_SOURCES_DATABASE: JobSource[] = [
    { id: 'src-1', name: 'IEFP', url: 'https://iefponline.iefp.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-2', name: 'BEP - Bolsa de Emprego Público', url: 'https://www.bep.gov.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-3', name: 'Net-Empregos', url: 'https://www.net-empregos.com', category: 'Agregador', trust_level: 9 },
    { id: 'src-4', name: 'Sapo Emprego', url: 'https://emprego.sapo.pt', category: 'Agregador', trust_level: 9 },
    { id: 'src-5', name: 'LinkedIn', url: 'https://www.linkedin.com', category: 'Rede Social', trust_level: 9 },
    { id: 'src-6', name: 'Indeed', url: 'https://pt.indeed.com', category: 'Agregador', trust_level: 8 },
    { id: 'src-7', name: 'Jooble', url: 'https://pt.jooble.org', category: 'Agregador', trust_level: 8 },
    { id: 'src-8', name: 'Trovit', url: 'https://emprego.trovit.pt', category: 'Agregador', trust_level: 7 },
    { id: 'src-9', name: 'Mitula', url: 'https://emprego.mitula.pt', category: 'Agregador', trust_level: 7 },
    { id: 'src-10', name: 'Careerjet', url: 'https://www.careerjet.pt', category: 'Agregador', trust_level: 7 },
    { id: 'src-11', name: 'Expresso Emprego', url: 'https://expressoemprego.pt', category: 'Premium', trust_level: 9 },
    { id: 'src-12', name: 'Alerta Emprego', url: 'https://www.alertaemprego.pt', category: 'Agregador', trust_level: 8 },
    { id: 'src-13', name: 'Bons Empregos', url: 'https://www.bonsempregos.pt', category: 'Agregador', trust_level: 8 },
    { id: 'src-14', name: 'Empregos Online', url: 'https://www.empregosonline.pt', category: 'Agregador', trust_level: 8 },
    { id: 'src-15', name: 'Carga de Trabalhos', url: 'https://www.cargadetrabalhos.pt', category: 'Criativo/Tech', trust_level: 9 },
    { id: 'src-16', name: 'It\'s Informática', url: 'https://www.it-informatica.pt', category: 'Tech', trust_level: 9 },
    { id: 'src-17', name: 'Landing.jobs', url: 'https://landing.jobs', category: 'Tech', trust_level: 9 },
    { id: 'src-18', name: 'Teamlyzer', url: 'https://www.teamlyzer.com', category: 'Tech/Review', trust_level: 8 },
    { id: 'src-19', name: 'Glassdoor', url: 'https://www.glassdoor.com', category: 'Reviews/Jobs', trust_level: 8 },
    { id: 'src-20', name: 'Emprego XL', url: 'https://www.empregoxl.pt', category: 'Agregador', trust_level: 7 },
    { id: 'src-21', name: 'Jobatus', url: 'https://www.jobatus.pt', category: 'Agregador', trust_level: 7 },
    { id: 'src-22', name: 'beBee', url: 'https://pt.bebee.com', category: 'Rede Social', trust_level: 7 },
    { id: 'src-23', name: 'Talent.com', url: 'https://pt.talent.com', category: 'Agregador', trust_level: 8 },
    { id: 'src-24', name: 'SimplyHired', url: 'https://www.simplyhired.pt', category: 'Agregador', trust_level: 7 },
    { id: 'src-25', name: 'Adzuna', url: 'https://www.adzuna.pt', category: 'Agregador', trust_level: 7 },
    { id: 'src-26', name: 'Turismo de Portugal', url: 'https://emprego.turismodeportugal.pt', category: 'Oficial/Turismo', trust_level: 10 },
    { id: 'src-27', name: 'Base.gov (Contratos Públicos)', url: 'http://www.base.gov.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-28', name: 'EURES Portugal', url: 'https://ec.europa.eu/eures', category: 'Oficial/UE', trust_level: 10 },
    { id: 'src-29', name: 'Portal da Juventude', url: 'https://juventude.gov.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-30', name: 'StepStone', url: 'https://www.stepstone.pt', category: 'Internacional', trust_level: 8 },
    { id: 'src-31', name: 'Monster', url: 'https://www.monster.pt', category: 'Internacional', trust_level: 8 },
    { id: 'src-32', name: 'Dice (Tech)', url: 'https://www.dice.com', category: 'Tech', trust_level: 8 },
    { id: 'src-33', name: 'Stack Overflow Jobs', url: 'https://stackoverflow.com/jobs', category: 'Tech', trust_level: 9 },
    { id: 'src-34', name: 'Relocate.me', url: 'https://relocate.me', category: 'Tech/Expats', trust_level: 8 },
    { id: 'src-35', name: 'RemoteOK', url: 'https://remoteok.com', category: 'Remoto', trust_level: 8 },
    { id: 'src-36', name: 'We Work Remotely', url: 'https://weworkremotely.com', category: 'Remoto', trust_level: 9 },
    { id: 'src-37', name: 'Portal do Cidadão', url: 'https://eportugal.gov.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-38', name: 'Santa Casa da Misericórdia de Lisboa', url: 'https://www.scml.pt/recrutamento/', category: 'Social/Oficial', trust_level: 10 },
    { id: 'src-39', name: 'Cruz Vermelha Portuguesa', url: 'https://www.cruzvermelha.pt/recrutamento', category: 'Social/ONG', trust_level: 10 },
    { id: 'src-40', name: 'Carris (Recrutamento)', url: 'https://www.carris.pt/empresa/recrutamento/', category: 'Transportes/Oficial', trust_level: 10 },
    { id: 'src-41', name: 'CP - Comboios de Portugal', url: 'https://www.cp.pt/institucional/pt/empresa/recrutamento', category: 'Transportes/Oficial', trust_level: 10 },
    { id: 'src-42', name: 'TAP Air Portugal', url: 'https://recrutamento.tap.pt', category: 'Transportes', trust_level: 10 },
    { id: 'src-43', name: 'CTT (Recrutamento)', url: 'https://www.ctt.pt/grupo-ctt/carreiras/recrutamento', category: 'Logística', trust_level: 10 },
    { id: 'src-44', name: 'EDP (Carreiras)', url: 'https://jobs.edp.com', category: 'Energia', trust_level: 10 },
    { id: 'src-45', name: 'Galp (Carreiras)', url: 'https://galp.com/corp/pt/pessoas/carreiras', category: 'Energia', trust_level: 10 },
    { id: 'src-46', name: 'Sonae (Carreiras)', url: 'https://www.sonae.pt/pt/pessoas/carreiras/', category: 'Retail', trust_level: 10 },
    { id: 'src-47', name: 'Jerónimo Martins', url: 'https://www.jeronimomartins.com/pt/pessoas/carreiras/', category: 'Retail', trust_level: 10 },
    { id: 'src-48', name: 'Lidl (Recrutamento)', url: 'https://empregos.lidl.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-49', name: 'Continente (Recrutamento)', url: 'https://recrutamento.sonaemc.com', category: 'Retail', trust_level: 10 },
    { id: 'src-50', name: 'Pingo Doce (Carreiras)', url: 'https://www.pingodoce.pt/carreiras/', category: 'Retail', trust_level: 10 },
    { id: 'src-51', name: 'Auchan Recruta', url: 'https://recrutamento.auchan.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-52', name: 'Mercadona (Emprego)', url: 'https://www.mercadona.pt/pt/emprego', category: 'Retail', trust_level: 10 },
    { id: 'src-53', name: 'Fnac (Recrutamento)', url: 'https://recrutamento.fnac.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-54', name: 'Worten (Carreiras)', url: 'https://www.worten.pt/carreiras', category: 'Retail', trust_level: 10 },
    { id: 'src-55', name: 'IKEA Portugal Jobs', url: 'https://www.ikea.com/pt/pt/this-is-ikea/work-with-us/', category: 'Retail', trust_level: 10 },
    { id: 'src-56', name: 'Leroy Merlin (Emprego)', url: 'https://recrutamento.leroymerlin.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-57', name: 'Decathlon (Recrutamento)', url: 'https://myjob.decathlon.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-58', name: 'Inditex Carreiras', url: 'https://www.inditexcareers.com', category: 'Retail', trust_level: 10 },
    { id: 'src-59', name: 'H&M Recrutamento', url: 'https://career.hm.com/content/hmcareer/pt_pt.html', category: 'Retail', trust_level: 10 },
    { id: 'src-60', name: 'Primark Carreiras', url: 'https://pt.carreiras.primark.com', category: 'Retail', trust_level: 10 },
    { id: 'src-61', name: 'Teleperformance Portugal', url: 'https://jobs.teleperformance.pt', category: 'Contact Center', trust_level: 9 },
    { id: 'src-62', name: 'Concentrix Portugal', url: 'https://jobs.concentrix.com', category: 'Contact Center', trust_level: 9 },
    { id: 'src-63', name: 'Foundever Portugal', url: 'https://jobs.foundever.com', category: 'Contact Center', trust_level: 9 },
    { id: 'src-64', name: 'Majorel Portugal', url: 'https://majorel.com/portugal/careers/', category: 'Contact Center', trust_level: 9 },
    { id: 'src-65', name: 'Webhelp Portugal', url: 'https://webhelp.com/pt-pt/carreiras/', category: 'Contact Center', trust_level: 9 },
    { id: 'src-66', name: 'Randstad Portugal', url: 'https://www.randstad.pt/empregos/', category: 'Recrutamento', trust_level: 9 },
    { id: 'src-67', name: 'Adecco Portugal', url: 'https://www.adecco.pt/ofertas-de-trabalho/', category: 'Recrutamento', trust_level: 9 },
    { id: 'src-68', name: 'Kelly Services Portugal', url: 'https://www.kellyservices.pt', category: 'Recrutamento', trust_level: 9 },
    { id: 'src-69', name: 'Manpower Portugal', url: 'https://www.manpower.pt', category: 'Recrutamento', trust_level: 9 },
    { id: 'src-70', name: 'MIRA Central Hub', url: 'https://mira.pt', category: 'Oficial', trust_level: 10 }
];
