// ============================================================================
// 🛡️ MIRA SOBERANIA: BASE DE DADOS OFICIAL E PROTEGIDA DE FONTES DE EMPREGO
// ⚠️ ESTE ARQUIVO É ESTRITAMENTE PROTEGIDO. PROIBIDO APAGAR OU ALTERAR FONTES.
// ============================================================================

export interface JobSource {
    id: string;
    name: string;
    url: string;
    category: string;
    trust_level: number; // 1-10 (10 = Oficial/Governamental)
}

export const JOB_SOURCES_DATABASE: JobSource[] = [
    // ─── 🏛️ PORTAIS GOVERNAMENTAIS & OFICIAIS DE ESTADO ─────────────────────────
    { id: 'src-1', name: 'IEFP', url: 'https://iefponline.iefp.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-2', name: 'BEP - Bolsa de Emprego Público', url: 'https://www.bep.gov.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-3', name: 'Turismo de Portugal', url: 'https://emprego.turismodeportugal.pt', category: 'Oficial/Turismo', trust_level: 10 },
    { id: 'src-4', name: 'Base.gov (Contratos Públicos)', url: 'http://www.base.gov.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-5', name: 'EURES Portugal', url: 'https://ec.europa.eu/eures', category: 'Oficial/UE', trust_level: 10 },
    { id: 'src-6', name: 'Portal da Juventude', url: 'https://juventude.gov.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-7', name: 'Portal do Cidadão', url: 'https://eportugal.gov.pt', category: 'Oficial', trust_level: 10 },
    { id: 'src-8', name: 'Santa Casa da Misericórdia de Lisboa', url: 'https://www.scml.pt/recrutamento/', category: 'Social/Oficial', trust_level: 10 },
    { id: 'src-9', name: 'Cruz Vermelha Portuguesa', url: 'https://www.cruzvermelha.pt/recrutamento', category: 'Social/ONG', trust_level: 10 },
    { id: 'src-10', name: 'GEPE', url: 'http://www.gepe.pt/', category: 'Oficial/Apoio', trust_level: 10 },

    // ─── 🌐 AGREGADORES GERAIS & METABUSCA EM PORTUGAL ─────────────────────────
    { id: 'src-11', name: 'Net-Empregos', url: 'https://www.net-empregos.com/', category: 'Agregador Líder', trust_level: 9 },
    { id: 'src-12', name: 'Sapo Emprego', url: 'https://emprego.sapo.pt/', category: 'Agregador Líder', trust_level: 9 },
    { id: 'src-13', name: 'Alerta Emprego', url: 'https://www.alertaemprego.pt', category: 'Agregador', trust_level: 8 },
    { id: 'src-14', name: 'Emprego.pt', url: 'https://www.emprego.pt/', category: 'Agregador', trust_level: 8 },
    { id: 'src-15', name: 'Cantinho do Emprego', url: 'http://cantinhodoemprego.pt/', category: 'Agregador', trust_level: 8 },
    { id: 'src-16', name: 'Emprego Estágios', url: 'https://www.empregoestagios.com/', category: 'Agregador/Estágios', trust_level: 8 },
    { id: 'src-17', name: 'Expresso Emprego', url: 'https://expressoemprego.pt/', category: 'Premium/Geral', trust_level: 9 },
    { id: 'src-18', name: 'Jobrapido', url: 'https://pt.jobrapido.com/', category: 'Metabusca', trust_level: 8 },
    { id: 'src-19', name: 'Bons Empregos', url: 'https://www.bonsempregos.com/', category: 'Agregador', trust_level: 8 },
    { id: 'src-20', name: 'Careerjet', url: 'https://www.careerjet.pt/', category: 'Agregador', trust_level: 7 },
    { id: 'src-21', name: 'CustoJusto Emprego', url: 'https://www.custojusto.pt/portugal/emprego-oferta', category: 'Classificados', trust_level: 8 },
    { id: 'src-22', name: 'OLX Emprego', url: 'https://www.olx.pt/emprego/', category: 'Classificados', trust_level: 8 },
    { id: 'src-23', name: 'Empregos Online', url: 'http://www.empregosonline.pt/', category: 'Agregador', trust_level: 8 },
    { id: 'src-24', name: 'Ofertas Emprego Net', url: 'https://www.ofertas-emprego.net/', category: 'Agregador', trust_level: 8 },
    { id: 'src-25', name: 'Ofertas de Emprego PT', url: 'https://www.ofertasdeemprego.pt/', category: 'Agregador', trust_level: 8 },
    { id: 'src-26', name: 'Web Emprego', url: 'https://www.web-emprego.com/', category: 'Agregador', trust_level: 8 },
    { id: 'src-27', name: 'Emprego XL', url: 'https://www.empregoxl.com/', category: 'Agregador', trust_level: 7 },
    { id: 'src-28', name: 'Jobtide', url: 'https://jobtide.com', category: 'Agregador', trust_level: 7 },
    { id: 'src-29', name: 'Jobatus', url: 'https://www.jobatus.pt/i', category: 'Agregador', trust_level: 7 },
    { id: 'src-30', name: 'Feed Empregos', url: 'https://www.feedempregos.pt/search/label/Emprego', category: 'Agregador', trust_level: 8 },
    { id: 'src-31', name: 'Trovit Emprego', url: 'https://emprego.trovit.pt/', category: 'Metabusca', trust_level: 7 },
    { id: 'src-32', name: 'Mitula', url: 'https://emprego.mitula.pt', category: 'Metabusca', trust_level: 7 },
    { id: 'src-33', name: 'Jooble', url: 'https://pt.jooble.org/', category: 'Agregador', trust_level: 8 },
    { id: 'src-34', name: 'Talent.com', url: 'https://pt.talent.com', category: 'Agregador', trust_level: 8 },
    { id: 'src-35', name: 'SimplyHired', url: 'https://www.simplyhired.pt', category: 'Agregador', trust_level: 7 },
    { id: 'src-36', name: 'Adzuna', url: 'https://www.adzuna.pt', category: 'Agregador', trust_level: 7 },
    { id: 'src-37', name: 'Ofertas Emprego (Twitter / X)', url: 'https://twitter.com/ofertasemprego', category: 'Rede Social', trust_level: 7 },

    // ─── 💼 AGÊNCIAS DE RECRUTAMENTO & TRABALHO TEMPORÁRIO ──────────────────────
    { id: 'src-38', name: 'Randstad Portugal', url: 'https://www.randstad.pt/', category: 'Recrutamento', trust_level: 9 },
    { id: 'src-39', name: 'Adecco Portugal', url: 'https://www.adecco.pt/', category: 'Recrutamento', trust_level: 9 },
    { id: 'src-40', name: 'ManpowerGroup Portugal', url: 'https://www.manpowergroup.pt', category: 'Recrutamento', trust_level: 9 },
    { id: 'src-41', name: 'Kelly Services Portugal', url: 'https://trabalhotemporario.pt/empresas/kelly-services/', category: 'Recrutamento', trust_level: 9 },
    { id: 'src-42', name: 'Michael Page', url: 'https://www.michaelpage.pt/', category: 'Recrutamento Executivo', trust_level: 9 },
    { id: 'src-43', name: 'Hays Portugal', url: 'https://www.hays.pt/', category: 'Recrutamento Especializado', trust_level: 9 },
    { id: 'src-44', name: 'Eurofirms Portugal', url: 'https://www.eurofirms.pt/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-45', name: 'Eurofirms Group', url: 'https://www.eurofirms.com/pt/pt/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-46', name: 'Eulen Flexiplan', url: 'https://flexiplan.eulen.com/pt/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-47', name: 'Go Work', url: 'https://www.gowork.pt/pt/', category: 'Recrutamento/RH', trust_level: 9 },
    { id: 'src-48', name: 'Great Job', url: 'http://greatjob.pt/', category: 'Recrutamento', trust_level: 8 },
    { id: 'src-49', name: 'Great Job PT', url: 'https://www.greatjob.pt/pt/', category: 'Recrutamento', trust_level: 8 },
    { id: 'src-50', name: 'Gi Group Portugal', url: 'https://pt.gigroup.com/ofertas-de-emprego/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-51', name: 'Grupo Constant (Personal 7)', url: 'https://grupoconstant.com/pt-pt/personal-7/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-52', name: 'Multipessoal', url: 'https://multipessoal.pt/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-53', name: 'Multitempo', url: 'http://www.multitempo.pt/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-54', name: 'Slot Recursos Humanos', url: 'https://slot.pt/', category: 'Recrutamento/RH', trust_level: 9 },
    { id: 'src-55', name: 'Vertente Humana', url: 'https://www.vertentehumana.pt/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-56', name: 'Talenter', url: 'https://www.talenter.com/', category: 'Recrutamento/RH', trust_level: 9 },
    { id: 'src-57', name: 'Egor', url: 'https://egor.pt/candidatos/', category: 'Recrutamento/RH', trust_level: 9 },
    { id: 'src-58', name: 'Get The Job', url: 'https://jobs.getthejob.pt/careers', category: 'Recrutamento', trust_level: 9 },
    { id: 'src-59', name: 'Timing Portugal', url: 'https://www.timing.pt/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-60', name: 'Triângulu', url: 'https://www.triangulu.pt/ofertas/', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-61', name: 'Grupo T2', url: 'https://www.grupot2.pt/pt/viewsub/ofertas-de-emprego', category: 'Trabalho Temporário', trust_level: 9 },
    { id: 'src-62', name: 'Grupo RHmais', url: 'https://www.gruporhmais.pt/', category: 'Recrutamento/BPO', trust_level: 9 },
    { id: 'src-63', name: 'Psicotempos', url: 'http://www.psicotempos.pt/', category: 'Recrutamento', trust_level: 8 },
    { id: 'src-64', name: 'Outplex', url: 'http://outplex.pt/', category: 'Recrutamento', trust_level: 8 },
    { id: 'src-65', name: 'Cnorey', url: 'https://www.cnorey.com/', category: 'Recrutamento', trust_level: 8 },
    { id: 'src-66', name: 'ICOTE', url: 'http://www.icote.pt/', category: 'Recrutamento', trust_level: 8 },
    { id: 'src-67', name: 'Drivewiz RH', url: 'https://www.drivewiz.pt/servicos_recursos-humanos/', category: 'Recrutamento Especializado', trust_level: 8 },
    { id: 'src-68', name: 'Trivalor Recrutamento', url: 'https://recrutamento.trivalor.pt/', category: 'Recrutamento Serviços', trust_level: 9 },
    { id: 'src-69', name: 'Hospedeiras de Portugal', url: 'http://hospedeiras-portugal.pt', category: 'Eventos/Hotelaria', trust_level: 9 },
    { id: 'src-70', name: 'Bolsa de Empregabilidade', url: 'https://bolsadeempregabilidade.pt/', category: 'Turismo/Hotelaria', trust_level: 9 },

    // ─── 💻 TECNOLOGIA, DESIGN, SAÚDE & REMOTO ─────────────────────────────────
    { id: 'src-71', name: 'IT Jobs', url: 'https://www.itjobs.pt/', category: 'Tech', trust_level: 9 },
    { id: 'src-72', name: 'Landing.jobs', url: 'https://landing.jobs', category: 'Tech', trust_level: 9 },
    { id: 'src-73', name: 'Carga de Trabalhos', url: 'http://www.cargadetrabalhos.net/', category: 'Criativo/Comunicação', trust_level: 9 },
    { id: 'src-74', name: 'Emprego Saúde', url: 'http://www.empregosaude.pt/', category: 'Saúde', trust_level: 9 },
    { id: 'src-75', name: 'Turijobs Portugal', url: 'https://www.turijobs.pt/', category: 'Turismo/Hotelaria', trust_level: 9 },
    { id: 'src-76', name: 'Rumos Emprego', url: 'https://emprego.rumos.pt/', category: 'Tech/Formação', trust_level: 9 },
    { id: 'src-77', name: 'Formação 2.0', url: 'https://www.formacao20.com/', category: 'Formação/Emprego', trust_level: 8 },
    { id: 'src-78', name: 'It\'s Informática', url: 'https://www.it-informatica.pt', category: 'Tech', trust_level: 9 },
    { id: 'src-79', name: 'Teamlyzer', url: 'https://www.teamlyzer.com', category: 'Tech/Reviews', trust_level: 8 },
    { id: 'src-80', name: 'RemoteOK', url: 'https://remoteok.com', category: 'Remoto Global', trust_level: 9 },
    { id: 'src-81', name: 'We Work Remotely', url: 'https://weworkremotely.com', category: 'Remoto Global', trust_level: 9 },
    { id: 'src-82', name: 'Relocate.me', url: 'https://relocate.me', category: 'Tech/Expats', trust_level: 8 },
    { id: 'src-83', name: 'Dice (Tech)', url: 'https://www.dice.com', category: 'Tech', trust_level: 8 },
    { id: 'src-84', name: 'LinkedIn Portugal', url: 'https://pt.linkedin.com/', category: 'Rede Social Líder', trust_level: 9 },
    { id: 'src-85', name: 'Indeed Portugal', url: 'https://pt.indeed.com/', category: 'Agregador Global', trust_level: 8 },
    { id: 'src-86', name: 'Glassdoor Portugal', url: 'https://www.glassdoor.com/Job/portugal', category: 'Reviews/Vagas', trust_level: 8 },
    { id: 'src-87', name: 'beBee Jobs Portugal', url: 'https://bebee.com/pt/jobs', category: 'Agregador/Rede Social', trust_level: 8 },
    { id: 'src-88', name: 'StepStone', url: 'https://www.stepstone.pt', category: 'Internacional', trust_level: 8 },
    { id: 'src-89', name: 'Monster', url: 'https://www.monster.pt', category: 'Internacional', trust_level: 8 },

    // ─── 🏬 GRANDES EMPRESAS & REDES CORPORATIVAS EM PORTUGAL ──────────────────
    { id: 'src-90', name: 'BNP Paribas Careers', url: 'https://group.bnpparibas/en/careers', category: 'Banca/Finanças', trust_level: 10 },
    { id: 'src-91', name: 'Carris (Recrutamento)', url: 'https://www.carris.pt/empresa/recrutamento/', category: 'Transportes/Oficial', trust_level: 10 },
    { id: 'src-92', name: 'CP - Comboios de Portugal', url: 'https://www.cp.pt/institucional/pt/empresa/recrutamento', category: 'Transportes/Oficial', trust_level: 10 },
    { id: 'src-93', name: 'TAP Air Portugal', url: 'https://recrutamento.tap.pt', category: 'Transportes', trust_level: 10 },
    { id: 'src-94', name: 'CTT (Recrutamento)', url: 'https://www.ctt.pt/grupo-ctt/carreiras/recrutamento', category: 'Logística', trust_level: 10 },
    { id: 'src-95', name: 'EDP (Carreiras)', url: 'https://jobs.edp.com', category: 'Energia', trust_level: 10 },
    { id: 'src-96', name: 'Galp (Carreiras)', url: 'https://galp.com/corp/pt/pessoas/carreiras', category: 'Energia', trust_level: 10 },
    { id: 'src-97', name: 'Sonae (Carreiras)', url: 'https://www.sonae.pt/pt/pessoas/carreiras/', category: 'Retail', trust_level: 10 },
    { id: 'src-98', name: 'Jerónimo Martins', url: 'https://www.jeronimomartins.com/pt/pessoas/carreiras/', category: 'Retail', trust_level: 10 },
    { id: 'src-99', name: 'Lidl (Recrutamento)', url: 'https://empregos.lidl.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-100', name: 'Continente (Recrutamento)', url: 'https://recrutamento.sonaemc.com', category: 'Retail', trust_level: 10 },
    { id: 'src-101', name: 'Pingo Doce (Carreiras)', url: 'https://www.pingodoce.pt/carreiras/', category: 'Retail', trust_level: 10 },
    { id: 'src-102', name: 'Auchan Recruta', url: 'https://recrutamento.auchan.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-103', name: 'Mercadona (Emprego)', url: 'https://www.mercadona.pt/pt/emprego', category: 'Retail', trust_level: 10 },
    { id: 'src-104', name: 'Fnac (Recrutamento)', url: 'https://recrutamento.fnac.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-105', name: 'Worten (Carreiras)', url: 'https://www.worten.pt/carreiras', category: 'Retail', trust_level: 10 },
    { id: 'src-106', name: 'IKEA Portugal Jobs', url: 'https://www.ikea.com/pt/pt/this-is-ikea/work-with-us/', category: 'Retail', trust_level: 10 },
    { id: 'src-107', name: 'Leroy Merlin (Emprego)', url: 'https://recrutamento.leroymerlin.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-108', name: 'Decathlon (Recrutamento)', url: 'https://myjob.decathlon.pt', category: 'Retail', trust_level: 10 },
    { id: 'src-109', name: 'Inditex Carreiras', url: 'https://www.inditexcareers.com', category: 'Retail', trust_level: 10 },
    { id: 'src-110', name: 'H&M Recrutamento', url: 'https://career.hm.com/content/hmcareer/pt_pt.html', category: 'Retail', trust_level: 10 },
    { id: 'src-111', name: 'Primark Carreiras', url: 'https://pt.carreiras.primark.com', category: 'Retail', trust_level: 10 },
    { id: 'src-112', name: 'Teleperformance Portugal', url: 'https://jobs.teleperformance.pt', category: 'Contact Center', trust_level: 9 },
    { id: 'src-113', name: 'Concentrix Portugal', url: 'https://jobs.concentrix.com', category: 'Contact Center', trust_level: 9 },
    { id: 'src-114', name: 'Foundever Portugal', url: 'https://jobs.foundever.com', category: 'Contact Center', trust_level: 9 },
    { id: 'src-115', name: 'Majorel Portugal', url: 'https://majorel.com/portugal/careers/', category: 'Contact Center', trust_level: 9 },
    { id: 'src-116', name: 'Webhelp Portugal', url: 'https://webhelp.com/pt-pt/carreiras/', category: 'Contact Center', trust_level: 9 },
    { id: 'src-117', name: 'Plataforma Portuguesa das ONGD', url: 'https://www.plataformaongd.pt/oportunidades-de-emprego-e-voluntariado', category: 'Social/ONG/Voluntariado', trust_level: 10 }
];
