import { MapAlert } from '../types';

export const MASSIVE_SERVICES_DATABASE: MapAlert[] = [
    // ============================================================
    // 🏛️ AIMA – AGÊNCIA PARA A INTEGRAÇÃO, MIGRAÇÕES E ASILO (36 LOJAS)
    // ============================================================
    {
        id: 'p-aima-albufeira',
        title: "AIMA Albufeira",
        category: "Residência & Vistos",
        lat: 37.0891,
        lng: -8.2479,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Quinta da Bela Vista, Bloco A10, Loja D, 8200-137 Albufeira",
        city: "Albufeira",
        website: "https://aima.gov.pt",
        description: "Atendimento oficial da AIMA para concessão e renovação de autorizações de residência, reagrupamento familiar e emissão de títulos de residência no Algarve."
    },
    {
        id: 'p-aima-alverca',
        title: "AIMA Alverca",
        category: "Residência & Vistos",
        lat: 38.8986,
        lng: -9.0396,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Praceta Estanislau Raimundo Nogueira, 1 e 2, 2615-075 Alverca do Ribatejo",
        city: "Alverca",
        website: "https://aima.gov.pt",
        description: "Posto de atendimento da AIMA para concessão e renovação de autorizações de residência, biometria e processos de regularização documental."
    },
    {
        id: 'p-aima-angra',
        title: "AIMA Angra do Heroísmo",
        category: "Residência & Vistos",
        lat: 38.6534,
        lng: -27.2185,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Alto das Covas, 12, Sé, 9700-220 Angra do Heroísmo",
        city: "Angra do Heroísmo",
        website: "https://aima.gov.pt",
        description: "Delegação da AIMA na Ilha Terceira (Açores): apoio documental, vistos, prorrogações de permanência e integração de imigrantes no arquipélago."
    },
    {
        id: 'p-aima-aveiro',
        title: "AIMA Aveiro",
        category: "Residência & Vistos",
        lat: 40.6405,
        lng: -8.6537,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Dr. Orlando Oliveira, 41-47, 3800-004 Aveiro",
        city: "Aveiro",
        website: "https://aima.gov.pt",
        description: "Loja AIMA no distrito de Aveiro: atendimento presencial agendado para pedidos de autorização de residência e certificados CPLP."
    },
    {
        id: 'p-aima-beja',
        title: "AIMA Beja",
        category: "Residência & Vistos",
        lat: 38.0153,
        lng: -7.8652,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Dom Nuno Álvares Pereira, 53, 7800-053 Beja",
        city: "Beja",
        website: "https://aima.gov.pt",
        description: "Atendimento da AIMA para a região do Baixo Alentejo: processos de trabalho, vistos de residência e apoio a trabalhadores migrantes."
    },
    {
        id: 'p-aima-braga',
        title: "AIMA Braga",
        category: "Residência & Vistos",
        lat: 41.5503,
        lng: -8.4200,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua dos Granjinhos, 6, 4700-996 Braga",
        city: "Braga",
        website: "https://aima.gov.pt",
        description: "Centro de atendimento AIMA em Braga: tramitação de autorizações de residência para trabalho, estudo e reagrupamento familiar no Minho."
    },
    {
        id: 'p-aima-braganca',
        title: "AIMA Bragança",
        category: "Residência & Vistos",
        lat: 41.8058,
        lng: -6.7572,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Largo de São João, R/C Dto., 5301-864 Bragança",
        city: "Bragança",
        website: "https://aima.gov.pt",
        description: "Posto da AIMA em Trás-os-Montes: acolhimento, regularização documental e atendimento especializado para a comunidade estudantil e migrante."
    },
    {
        id: 'p-aima-cacem',
        title: "AIMA Cacém",
        category: "Residência & Vistos",
        lat: 38.7667,
        lng: -9.3000,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Praceta Duque de Saldanha, 17, 2735-330 Agualva-Cacém",
        city: "Sintra",
        website: "https://aima.gov.pt",
        description: "Loja AIMA no concelho de Sintra: renovação de títulos de residência, recolha biométrica e esclarecimento de processos pendentes."
    },
    {
        id: 'p-aima-cascais',
        title: "AIMA Cascais",
        category: "Residência & Vistos",
        lat: 38.6970,
        lng: -9.4223,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua da Misericórdia, 1, 2750-434 Cascais",
        city: "Cascais",
        website: "https://aima.gov.pt",
        description: "Posto de atendimento da AIMA em Cascais: receção de pedidos de autorização de residência para atividade profissional, investimento e estudo."
    },
    {
        id: 'p-aima-castelobranco',
        title: "AIMA Castelo Branco",
        category: "Residência & Vistos",
        lat: 39.8222,
        lng: -7.4909,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Prof. Dr. Faria de Vasconcelos, 6, R/C, 6000-266 Castelo Branco",
        city: "Castelo Branco",
        website: "https://aima.gov.pt",
        description: "Delegação da AIMA na Beira Baixa: apoio na emissão de cartões de residência, cartões de cidadão estrangeiro e extensão de vistos."
    },
    {
        id: 'p-aima-coimbra',
        title: "AIMA Coimbra",
        category: "Residência & Vistos",
        lat: 40.2033,
        lng: -8.4103,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Central, 16-20, 3000-617 Coimbra",
        city: "Coimbra",
        website: "https://aima.gov.pt",
        description: "Loja AIMA em Coimbra: regularização de estudantes internacionais da Universidade de Coimbra, investigadores, trabalhadores e respetivas famílias."
    },
    {
        id: 'p-aima-espinho',
        title: "AIMA Espinho",
        category: "Residência & Vistos",
        lat: 41.0075,
        lng: -8.6415,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua 32, n.º 834, 4500-191 Espinho",
        city: "Espinho",
        website: "https://aima.gov.pt",
        description: "Posto de atendimento da AIMA na Área Metropolitana do Porto Sul: renovação de documentos de permanência e agendamentos presenciais."
    },
    {
        id: 'p-aima-evora',
        title: "AIMA Évora",
        category: "Residência & Vistos",
        lat: 38.5714,
        lng: -7.9135,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Lino de Carvalho, 7 e 7A, 7005-467 Évora",
        city: "Évora",
        website: "https://aima.gov.pt",
        description: "Centro da AIMA para o Alentejo Central: instrução de pedidos de residência, proteção internacional e atendimento a migrantes."
    },
    {
        id: 'p-aima-faro',
        title: "AIMA Faro",
        category: "Residência & Vistos",
        lat: 37.0194,
        lng: -7.9304,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Largo Dr. Francisco Sá Carneiro, 8000-151 Faro",
        city: "Faro",
        website: "https://aima.gov.pt",
        description: "Loja AIMA Central do Algarve: emissão e entrega de títulos de residência, processos de reagrupamento familiar e atendimento ao público."
    },
    {
        id: 'p-aima-figueira',
        title: "AIMA Figueira da Foz",
        category: "Residência & Vistos",
        lat: 40.1500,
        lng: -8.8500,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida de Espanha, 380, 3080-271 Figueira da Foz",
        city: "Figueira da Foz",
        website: "https://aima.gov.pt",
        description: "Atendimento da AIMA no litoral centro: recolha de biometria para autorizações de residência e regularização de trabalhadores locais."
    },
    {
        id: 'p-aima-funchal',
        title: "AIMA Funchal",
        category: "Residência & Vistos",
        lat: 32.6500,
        lng: -16.9167,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Arriaga, 42-A, 9000-064 Funchal",
        city: "Funchal",
        website: "https://aima.gov.pt",
        description: "Delegação Regional da AIMA na Madeira: concessão de títulos de residência, processos CPLP e acolhimento de cidadãos estrangeiros na Região Autónoma."
    },
    {
        id: 'p-aima-guarda',
        title: "AIMA Guarda",
        category: "Residência & Vistos",
        lat: 40.5383,
        lng: -7.2661,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Paiva Couceiro, 22, 6300-593 Guarda",
        city: "Guarda",
        website: "https://aima.gov.pt",
        description: "Posto da AIMA na Beira Alta: pedidos de residência temporária e permanente, reagrupamento familiar e validação documental."
    },
    {
        id: 'p-aima-horta',
        title: "AIMA Horta",
        category: "Residência & Vistos",
        lat: 38.5333,
        lng: -28.6333,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua de São João, 46, 9900-129 Horta, Faial",
        city: "Horta",
        website: "https://aima.gov.pt",
        description: "Delegação da AIMA na Ilha do Faial (Açores): apoio à imigração, emissão de autorizações de residência e prorrogação de permanência."
    },
    {
        id: 'p-aima-leiria',
        title: "AIMA Leiria",
        category: "Residência & Vistos",
        lat: 39.7436,
        lng: -8.8071,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Largo Dr. Manuel de Arriaga, 1, 2400-177 Leiria",
        city: "Leiria",
        website: "https://aima.gov.pt",
        description: "Loja AIMA de Leiria: atendimento especializado para regularização de trabalhadores industriais, agrícolas e estudantes do Politécnico de Leiria."
    },
    {
        id: 'p-aima-lisboa-anjos',
        title: "AIMA Lisboa (Anjos - CNAIM)",
        category: "Residência & Vistos",
        lat: 38.7250,
        lng: -9.1350,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Álvaro Coutinho, 14, 1150-025 Lisboa",
        city: "Lisboa",
        website: "https://aima.gov.pt",
        description: "Principal Centro Nacional de Apoio à Integração de Migrantes em Lisboa: atendimento integrado com AIMA, Segurança Social, ACT, IEFP e apoio jurídico."
    },
    {
        id: 'p-aima-lisboa-aguiar',
        title: "AIMA Lisboa (A.A. Aguiar)",
        category: "Residência & Vistos",
        lat: 38.7300,
        lng: -9.1500,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida António Augusto de Aguiar, 20, 1069-119 Lisboa",
        city: "Lisboa",
        website: "https://aima.gov.pt",
        description: "Loja central da AIMA em Lisboa para atendimento presencial agendado, recolha de dados biométricos e entrega de títulos de residência."
    },
    {
        id: 'p-aima-odemira',
        title: "AIMA Odemira",
        category: "Residência & Vistos",
        lat: 37.5972,
        lng: -8.6428,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Sousa Prado, Sala 2, 7630-176 Odemira",
        city: "Odemira",
        website: "https://aima.gov.pt",
        description: "Posto de atendimento da AIMA no Litoral Alentejano: regularização, acolhimento e apoio específico aos trabalhadores agrícolas da região."
    },
    {
        id: 'p-aima-odivelas',
        title: "AIMA Odivelas",
        category: "Residência & Vistos",
        lat: 38.7933,
        lng: -9.1733,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Estrada da Paiã, Casal da Troca, 2675-626 Odivelas",
        city: "Odivelas",
        website: "https://aima.gov.pt",
        description: "Loja AIMA em Odivelas: renovação de autorizações de residência, reagrupamento familiar e atendimento por marcação prévia."
    },
    {
        id: 'p-aima-pontadelgada',
        title: "AIMA Ponta Delgada",
        category: "Residência & Vistos",
        lat: 37.7412,
        lng: -25.6756,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Marquês da Praia e Monforte, 10, 9500-089 Ponta Delgada",
        city: "Ponta Delgada",
        website: "https://aima.gov.pt",
        description: "Sede Regional da AIMA na Ilha de São Miguel (Açores): gestão de processos de legalização, títulos de residência e acolhimento de migrantes."
    },
    {
        id: 'p-aima-portalegre',
        title: "AIMA Portalegre",
        category: "Residência & Vistos",
        lat: 39.2917,
        lng: -7.4322,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida de Santo António, 12, 7300-074 Portalegre",
        city: "Portalegre",
        website: "https://aima.gov.pt",
        description: "Atendimento da AIMA no Alto Alentejo: instrução de processos de residência, prorrogações e pedidos de proteção internacional."
    },
    {
        id: 'p-aima-portimao',
        title: "AIMA Portimão",
        category: "Residência & Vistos",
        lat: 37.1383,
        lng: -8.5391,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Quinta do Morais, Lote 11, Fração A, 8500-774 Portimão",
        city: "Portimão",
        website: "https://aima.gov.pt",
        description: "Loja da AIMA no Barlavento Algarvio: emissão de autorizações de residência para trabalhadores dos setores da hotelaria, restauração e serviços."
    },
    {
        id: 'p-aima-porto-franca',
        title: "AIMA Porto (CNAIM Norte)",
        category: "Residência & Vistos",
        lat: 41.1600,
        lng: -8.6280,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida de França, 316, Edifício Capitólio, 4050-276 Porto",
        city: "Porto",
        website: "https://aima.gov.pt",
        description: "Centro Nacional de Apoio à Integração de Migrantes no Norte: serviços integrados de regularização, apoio jurídico, emprego e segurança social."
    },
    {
        id: 'p-aima-porto-seiva',
        title: "AIMA Porto (Seiva)",
        category: "Residência & Vistos",
        lat: 41.1500,
        lng: -8.6100,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua de Calouste Gulbenkian, 176, 4050-323 Porto",
        city: "Porto",
        website: "https://aima.gov.pt",
        description: "Posto de atendimento da AIMA no centro do Porto: recolha biométrica e tramitação de autorizações de residência temporárias e definitivas."
    },
    {
        id: 'p-aima-portosanto',
        title: "AIMA Porto Santo",
        category: "Residência & Vistos",
        lat: 33.0583,
        lng: -16.3333,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Henrique Vieira de Castro, 14, 9400-179 Vila Baleira",
        city: "Porto Santo",
        website: "https://aima.gov.pt",
        description: "Posto da AIMA na Ilha de Porto Santo (Madeira): atendimento de proximidade para prorrogação de vistos e títulos de residência."
    },
    {
        id: 'p-aima-santarem',
        title: "AIMA Santarém",
        category: "Residência & Vistos",
        lat: 39.2333,
        lng: -8.6833,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Largo do Carmo, 2000-118 Santarém",
        city: "Santarém",
        website: "https://aima.gov.pt",
        description: "Loja AIMA no Ribatejo: atendimento para concessão de residência, cartões de residência para familiares de cidadãos da UE e acordos CPLP."
    },
    {
        id: 'p-aima-queluz',
        title: "AIMA Queluz",
        category: "Residência & Vistos",
        lat: 38.7500,
        lng: -9.2500,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua 9 de Abril, 24, 2745-286 Queluz",
        city: "Sintra",
        website: "https://aima.gov.pt",
        description: "Posto AIMA em Queluz: renovações de residência, atualização de dados cadastrais e entrega de títulos emitidos."
    },
    {
        id: 'p-aima-setubal',
        title: "AIMA Setúbal",
        category: "Residência & Vistos",
        lat: 38.5244,
        lng: -8.8930,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Luísa Todi, 191, 2900-462 Setúbal",
        city: "Setúbal",
        website: "https://aima.gov.pt",
        description: "Centro da AIMA em Setúbal: tramitação de processos de residência para trabalhadores da Península de Setúbal, estudantes e famílias."
    },
    {
        id: 'p-aima-tavira',
        title: "AIMA Tavira",
        category: "Residência & Vistos",
        lat: 37.1261,
        lng: -7.6491,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Dr. Augusto Carlos Palma, 13, 8800-345 Tavira",
        city: "Tavira",
        website: "https://aima.gov.pt",
        description: "Posto de atendimento da AIMA no Sotavento Algarvio: instrução de pedidos de residência, prorrogação de permanência e atendimento agendado."
    },
    {
        id: 'p-aima-viana',
        title: "AIMA Viana do Castelo",
        category: "Residência & Vistos",
        lat: 41.6918,
        lng: -8.8344,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua José Espregueira, 145-147, 4900-459 Viana do Castelo",
        city: "Viana do Castelo",
        website: "https://aima.gov.pt",
        description: "Loja AIMA no Alto Minho: pedidos de autorização de residência para indústria naval, comércio, estudantes e reagrupamento familiar."
    },
    {
        id: 'p-aima-viseu',
        title: "AIMA Viseu",
        category: "Residência & Vistos",
        lat: 40.6610,
        lng: -7.9097,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Alberto Sampaio, 17, R/C, 3510-512 Viseu",
        city: "Viseu",
        website: "https://aima.gov.pt",
        description: "Loja da AIMA no distrito de Viseu: regularização de cidadãos estrangeiros, concessão de títulos de residência e informação aos imigrantes."
    },
    {
        id: 'p-aima-vilareal',
        title: "AIMA Vila Real",
        category: "Residência & Vistos",
        lat: 41.3000,
        lng: -7.7333,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Largo Conde de Amarante, 5000-529 Vila Real",
        city: "Vila Real",
        website: "https://aima.gov.pt",
        description: "Centro da AIMA em Trás-os-Montes e Alto Douro: apoio documental aos estudantes da UTAD, investigadores e trabalhadores da região."
    },

    // ============================================================
    // 🏥 HOSPITAIS CENTRAIS DO SERVIÇO NACIONAL DE SAÚDE (SNS)
    // ============================================================
    {
        id: 'p-hosp-stmaria',
        title: "Hospital de Santa Maria (CHULN)",
        category: "Saúde & Cuidados",
        lat: 38.7482,
        lng: -9.1608,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Professor Egas Moniz, 1649-035 Lisboa",
        city: "Lisboa",
        website: "https://www.ulssm.min-saude.pt",
        description: "Hospital universitário central do SNS em Lisboa: serviço de urgência geral 24h, consultas de todas as especialidades médicas, cirurgia e maternidade."
    },
    {
        id: 'p-hosp-sjoao',
        title: "Hospital de São João (CHUSJ)",
        category: "Saúde & Cuidados",
        lat: 41.1812,
        lng: -8.5985,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Alameda Professor Hernâni Monteiro, 4200-319 Porto",
        city: "Porto",
        website: "https://portal-chsj.min-saude.pt",
        description: "Hospital público de referência na Região Norte: urgência polivalente 24h, centro de trauma, pediatria, oncologia e internamento hospitalar."
    },
    {
        id: 'p-hosp-huc',
        title: "Hospitais da Universidade de Coimbra (CHUC)",
        category: "Saúde & Cuidados",
        lat: 40.2185,
        lng: -8.4124,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Praceta Professor Mota Pinto, 3000-075 Coimbra",
        city: "Coimbra",
        website: "https://www.ulscoimbra.min-saude.pt",
        description: "Complexo hospitalar de referência no Centro do país: urgências 24h, transplantação, cardiologia, neurocirurgia e investigação médica."
    },
    {
        id: 'p-hosp-braga',
        title: "Hospital de Braga",
        category: "Saúde & Cuidados",
        lat: 41.5683,
        lng: -8.3986,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Sete Fontes, Freguesia de São Victor, 4710-243 Braga",
        city: "Braga",
        website: "https://www.hospitaldebraga.pt",
        description: "Hospital central do Minho: serviço de urgência de adultos e pediátrica, maternidade, exames de diagnóstico e cirurgias programadas."
    },
    {
        id: 'p-hosp-faro',
        title: "Hospital de Faro (CHUA)",
        category: "Saúde & Cuidados",
        lat: 37.0245,
        lng: -7.9270,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Leão Penedo, 8000-386 Faro",
        city: "Faro",
        website: "https://www.chua.min-saude.pt",
        description: "Principal unidade hospitalar do Algarve: urgência central 24h, cuidados intensivos, cirurgia e atendimento a utentes nacionais e estrangeiros."
    },
    {
        id: 'p-hosp-gaiai',
        title: "Hospital de Gaia (CHVNGE)",
        category: "Saúde & Cuidados",
        lat: 41.1114,
        lng: -8.6014,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Conceição Fernandes, 4434-502 Vila Nova de Gaia",
        city: "Vila Nova de Gaia",
        website: "https://www.chvng.pt",
        description: "Hospital de Gaia e Espinho: serviço de urgência médico-cirúrgica, ortopedia, cardiologia e centro de ambulatório."
    },
    {
        id: 'p-hosp-setubal',
        title: "Hospital de Setúbal (São Bernardo)",
        category: "Saúde & Cuidados",
        lat: 38.5312,
        lng: -8.8821,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Camilo Castelo Branco, 2910-446 Setúbal",
        city: "Setúbal",
        website: "https://www.ulsa.min-saude.pt",
        description: "Hospital público de referência na Península de Setúbal: urgência de adultos e obstetrícia, medicina interna e especialidades cirúrgicas."
    },
    {
        id: 'p-hosp-vfx',
        title: "Hospital de Vila Franca de Xira",
        category: "Saúde & Cuidados",
        lat: 38.9612,
        lng: -8.9912,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Estrada dos Povos, 2600-001 Vila Franca de Xira",
        city: "Vila Franca de Xira",
        website: "https://www.hospvfxira.pt",
        description: "Unidade hospitalar moderna que serve os concelhos de Vila Franca de Xira, Alenquer, Arruda dos Vinhos, Azambuja e Benavente com urgência 24h."
    },
    {
        id: 'p-hosp-cascais',
        title: "Hospital de Cascais (Dr. José de Almeida)",
        category: "Saúde & Cuidados",
        lat: 38.7231,
        lng: -9.4312,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Brigadeiro Victor Novais Gonçalves, 2755-009 Alcabideche",
        city: "Cascais",
        website: "https://www.hospitaldecascais.pt",
        description: "Hospital público com gestão em parceria público-privada: urgências gerais e pediátricas 24h, bloco operatório e maternidade."
    },

    // ============================================================
    // 🩺 CENTROS DE SAÚDE / UNIDADES DE CUIDADOS PRIMÁRIOS (SNS)
    // ============================================================
    {
        id: 'p-cs-olivais',
        title: "Centro de Saúde dos Olivais",
        category: "Saúde & Cuidados",
        lat: 38.7612,
        lng: -9.1123,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Cidade de Bolama, 1800-078 Lisboa",
        city: "Lisboa",
        website: "https://www.sns.gov.pt",
        description: "Unidade de Cuidados de Saúde Primários em Lisboa: consultas de clínica geral, médico de família, vacinação de rotina e enfermagem."
    },
    {
        id: 'p-cs-bonfim',
        title: "Centro de Saúde do Bonfim",
        category: "Saúde & Cuidados",
        lat: 41.1512,
        lng: -8.5912,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua do Bonfim, 4300-069 Porto",
        city: "Porto",
        website: "https://www.sns.gov.pt",
        description: "Atendimento de saúde primária no centro do Porto: acompanhamento de doentes crónicos, planeamento familiar e emissão de atestados médicos."
    },
    {
        id: 'p-cs-braga',
        title: "Centro de Saúde de Braga (Infias)",
        category: "Saúde & Cuidados",
        lat: 41.5612,
        lng: -8.4112,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Praça da Justiça, 4710-410 Braga",
        city: "Braga",
        website: "https://www.sns.gov.pt",
        description: "Centro de Saúde em Braga: inscrição de novos utentes no SNS, vacinação internacional e consultas de medicina geral e familiar."
    },
    {
        id: 'p-cs-coimbra',
        title: "Centro de Saúde de Coimbra (Eiras)",
        category: "Saúde & Cuidados",
        lat: 40.2312,
        lng: -8.4212,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua do Valongo, 3020-478 Coimbra",
        city: "Coimbra",
        website: "https://www.sns.gov.pt",
        description: "Unidade de Saúde Familiar em Coimbra: cuidados de saúde primários, rastreios oncológicos e consultas de enfermagem comunitária."
    },
    {
        id: 'p-cs-setubal',
        title: "Centro de Saúde de Setúbal (São Sebastião)",
        category: "Saúde & Cuidados",
        lat: 38.5250,
        lng: -8.8910,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua de São Sebastião, 2900-614 Setúbal",
        city: "Setúbal",
        website: "https://www.sns.gov.pt",
        description: "Centro de Saúde em Setúbal: consultas para utentes sem médico de família, vacinação de crianças e adultos e acompanhamento pré-natal."
    },
    {
        id: 'p-cs-faro',
        title: "Centro de Saúde de Faro",
        category: "Saúde & Cuidados",
        lat: 37.0212,
        lng: -7.9312,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Brites de Almeida, 8000-233 Faro",
        city: "Faro",
        website: "https://www.sns.gov.pt",
        description: "Unidade de saúde primária em Faro: atendimento programado, vacinação, penso e tratamentos de enfermagem para residentes no Algarve."
    },

    // ============================================================
    // 💼 IEFP – INSTITUTO DO EMPREGO E FORMAÇÃO PROFISSIONAL
    // ============================================================
    {
        id: 'p-iefp-lisboa',
        title: "IEFP Centro de Emprego de Lisboa (Xabregas)",
        category: "Trabalho & Carreira",
        lat: 38.7250,
        lng: -9.1150,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua de Xabregas, 52, 1949-003 Lisboa",
        city: "Lisboa",
        website: "https://www.iefp.pt",
        description: "Centro de emprego e formação do IEFP em Lisboa: inscrição para emprego, subsídio de desemprego, cursos de formação e apoio ao empreendedorismo."
    },
    {
        id: 'p-iefp-porto',
        title: "IEFP Centro de Emprego do Porto",
        category: "Trabalho & Carreira",
        lat: 41.1550,
        lng: -8.6200,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua de António Patrício, 143, 4150-098 Porto",
        city: "Porto",
        website: "https://www.iefp.pt",
        description: "Serviço de emprego do IEFP no Porto: colocação profissional de candidatos, ofertas de trabalho e programas de estágios profissionais apoiados."
    },
    {
        id: 'p-iefp-braga',
        title: "IEFP Centro de Emprego de Braga",
        category: "Trabalho & Carreira",
        lat: 41.5500,
        lng: -8.4300,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua de Baixo, 4700-015 Braga",
        city: "Braga",
        website: "https://www.iefp.pt",
        description: "Centro do IEFP em Braga: orientação vocacional, cursos de aprendizagem qualificada e certificação escolar e profissional (RVCC)."
    },

    // ============================================================
    // 🏢 LOJAS DO CIDADÃO (BALCÃO ÚNICO DO ESTADO)
    // ============================================================
    {
        id: 'p-lc-laranjeiras',
        title: "Loja do Cidadão das Laranjeiras (IRN / SS / AT)",
        category: "Residência & Vistos",
        lat: 38.7485,
        lng: -9.1670,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Abranches Ferrão, 10, 1600-001 Lisboa",
        city: "Lisboa",
        website: "https://www.gov.pt",
        description: "Maior Loja do Cidadão do país: reúne balcões do IRN (Cartão de Cidadão/Passaporte), Segurança Social (NISS), Autoridade Tributária (NIF) e IMT."
    },
    {
        id: 'p-lc-porto',
        title: "Loja do Cidadão do Porto (IRN / SS / AT)",
        category: "Residência & Vistos",
        lat: 41.1650,
        lng: -8.5850,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida de Fernão de Magalhães, 1862, 4350-158 Porto",
        city: "Porto",
        website: "https://www.gov.pt",
        description: "Balcão multisserviços central do Porto com atendimento presencial do IRN, Finanças, Segurança Social, CTT e empresas de água e eletricidade."
    },

    // ============================================================
    // 🤝 ONGs & ORGANIZAÇÕES DE APOIO AO MIGRANTE
    // ============================================================
    {
        id: 'p-ong-jrs',
        title: "JRS Portugal (Serviço Jesuíta aos Refugiados)",
        category: "Direitos & Apoio Social",
        lat: 38.7845,
        lng: -9.1520,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Rogério de Moura, Lote 59, Lumiar, 1750-342 Lisboa",
        city: "Lisboa",
        website: "https://jrsportugal.pt",
        description: "Apoio humanitário de referência: acolhimento, apoio psicológico especializado, assistência social de emergência e acompanhamento jurídico gratuito."
    },
    {
        id: 'p-ong-cpr',
        title: "Conselho Português para os Refugiados (CPR)",
        category: "Direitos & Apoio Social",
        lat: 38.7562,
        lng: -9.1123,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Quinta do Pombeiro, Azinhaga do Pombeiro, s/n, 1900-793 Lisboa",
        city: "Lisboa",
        website: "https://cpr.pt",
        description: "Organização não governamental parceira do ACNUR: centros de acolhimento para requerentes de asilo, assistência jurídica e inserção na sociedade."
    },
    {
        id: 'p-ong-solim',
        title: "Solidariedade Imigrante (SOLIM)",
        category: "Direitos & Apoio Social",
        lat: 38.7128,
        lng: -9.1362,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua da Madalena, 8, 2.º andar, 1100-321 Lisboa",
        city: "Lisboa",
        website: "https://www.solimigrante.org/",
        description: "Associação cívica de defesa dos direitos dos imigrantes: apoio à regularização de residência, combate à exploração laboral e assessoria jurídica."
    },
    {
        id: 'p-ong-lp',
        title: "Lisbon Project",
        category: "Direitos & Apoio Social",
        lat: 38.7235,
        lng: -9.1440,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua de Santa Marta, 43, 1150-293 Lisboa",
        city: "Lisboa",
        website: "https://lisbonproject.org",
        description: "Comunidade de voluntariado para integração de migrantes e refugiados: aulas de português, mentoria profissional, assistência médica e eventos comunitários."
    },
    {
        id: 'p-ong-casabrasil',
        title: "Casa do Brasil de Lisboa",
        category: "Direitos & Apoio Social",
        lat: 38.7115,
        lng: -9.1465,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Luz Soriano, 42, 1200-248 Lisboa",
        city: "Lisboa",
        website: "https://casadobrasildelisboa.pt",
        description: "Associação fundada em 1992 que presta apoio social, jurídico e laboral a imigrantes de todas as nacionalidades, com ênfase na comunidade lusófona."
    },
    {
        id: 'p-ong-rw',
        title: "Refugees Welcome Portugal",
        category: "Direitos & Apoio Social",
        lat: 38.7350,
        lng: -9.1450,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida da República, 1050-189 Lisboa",
        city: "Lisboa",
        website: "https://refugees-welcome.pt",
        description: "Iniciativa de inovação social para inclusão habitacional de refugiados, promovendo alojamento em habitações partilhadas e mentoria de integração."
    },
    {
        id: 'p-ong-femafro',
        title: "FEMAFRO (Mulheres Negras e Afrodescendentes)",
        category: "Direitos & Apoio Social",
        lat: 38.6415,
        lng: -9.1234,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Praceta Antero de Quental, 15, 2855-214 Corroios",
        city: "Setúbal",
        website: "https://femafro.pt",
        description: "Associação de defesa dos direitos de mulheres negras, africanas e afrodescendentes: combate à discriminação, apoio psicológico e capacitação cívica."
    },
    {
        id: 'p-ong-mdm',
        title: "Médicos do Mundo Portugal",
        category: "Saúde & Cuidados",
        lat: 38.7050,
        lng: -9.1750,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida de Ceuta (Sul), Lote 4, Loja 1, 1300-125 Lisboa",
        city: "Lisboa",
        website: "https://medicosdomundo.pt",
        description: "ONG médica humanitária que garante cuidados de saúde primários gratuitos, consultas médicas e enfermagem a populações vulneráveis e migrantes."
    },
    {
        id: 'p-ong-caritas',
        title: "Cáritas Portuguesa",
        category: "Direitos & Apoio Social",
        lat: 38.7365,
        lng: -9.1325,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Praça Pasteur, 11, 2.º Esq., 1000-238 Lisboa",
        city: "Lisboa",
        website: "https://www.caritas.pt",
        description: "Rede nacional de solidariedade: apoio social de emergência, distribuição de refeições e bens essenciais, apoio habitacional e acolhimento familiar."
    },
    {
        id: 'p-ong-adip',
        title: "ADIP (Despertar Imigrantes em Portugal)",
        category: "Direitos & Apoio Social",
        lat: 38.7180,
        lng: -9.1360,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua da Palma, 268, 1100-394 Lisboa",
        city: "Lisboa",
        website: "https://associacaoadip.com",
        description: "Associação comunitária dedicada ao apoio documental na legalização de residência, aulas de português e integração no mercado de trabalho."
    },

    // ============================================================
    // ♿ ORGANIZAÇÕES DE APOIO A PCD (DIREITOS & INCLUSÃO)
    // ============================================================
    {
        id: '1263c23e-b716-4100-afa3-20382906f9e4',
        title: "APD — Associação Portuguesa de Deficientes",
        category: "Direitos & Apoio Social",
        lat: 38.7203,
        lng: -9.1541,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Largo do Rato, 1B, 1250-185 Lisboa",
        city: "Lisboa",
        website: "https://www.apd.org.pt",
        description: "Organização nacional de pessoas com deficiência motora: assessoria jurídica, promoção da acessibilidade urbana e inclusão profissional."
    },
    {
        id: '8b191c13-7d84-484b-a25e-04f85e4ae1bb',
        title: "ACAPO — Associação de Cegos e Amblíopes de Portugal",
        category: "Direitos & Apoio Social",
        lat: 38.7088,
        lng: -9.1534,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida D. Carlos I, 126, 9.º andar, 1200-651 Lisboa",
        city: "Lisboa",
        website: "https://www.acapo.pt",
        description: "Apoio e reabilitação para pessoas cegas ou com baixa visão: treino em Braille, tecnologias de apoio, orientação, mobilidade e formação."
    },
    {
        id: 'e7323863-718d-4e96-a83d-0ea2da484643',
        title: "FENACERCI — Federação Nacional das Cooperativas de Solidariedade Social",
        category: "Direitos & Apoio Social",
        lat: 38.7566,
        lng: -9.1622,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Augusto Macedo, 2A, 1600-794 Lisboa",
        city: "Lisboa",
        website: "https://www.fenacerci.pt",
        description: "Federação de cooperativas de apoio a pessoas com deficiência intelectual e multideficiência: centros de atividades ocupacionais e lares residenciais."
    },
    {
        id: 'f33e7d58-7cae-4f51-a90a-a0fdb9b8971f',
        title: "FPAS — Federação Portuguesa das Associações de Surdos",
        category: "Direitos & Apoio Social",
        lat: 38.7592,
        lng: -9.2241,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Praceta Miguel Cláudio, 3B, 2700-585 Amadora",
        city: "Amadora",
        website: "https://fpasurdos.pt",
        description: "Defesa dos direitos e cidadania da comunidade surda: promoção da Língua Gestual Portuguesa (LGP), acessibilidade e serviços de interpretação."
    },
    {
        id: '64a93864-4c40-42ae-ad8a-a4309c6f2a87',
        title: "FAPPC — Federação das Associações de Paralisia Cerebral",
        category: "Direitos & Apoio Social",
        lat: 38.7610,
        lng: -9.1610,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Rainha D. Amélia, 1600-676 Lisboa",
        city: "Lisboa",
        website: "https://www.fappc.pt",
        description: "Apoio clínico, reabilitação física, terapias ocupacionais e suporte familiar a pessoas com paralisia cerebral e perturbações do neurodesenvolvimento."
    },
    {
        id: '12b1d3ef-cf03-4f96-b08e-5bcfd30eb088',
        title: "FPDA — Federação Portuguesa de Autismo",
        category: "Direitos & Apoio Social",
        lat: 38.7090,
        lng: -9.1980,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua José Luís Garcia Rodrigues, Bairro Alto da Ajuda, 1300-565 Lisboa",
        city: "Lisboa",
        website: "https://www.fpda.pt",
        description: "Federação especializada no espetro do autismo: orientação diagnóstica, inclusão escolar e profissional, apoio psicopedagógico e apoio a famílias."
    },
    {
        id: 'ce0cfec9-234b-4c55-b0fc-fb0a3a782255',
        title: "FPDD — Federação Portuguesa de Desporto para Pessoas com Deficiência",
        category: "Direitos & Apoio Social",
        lat: 38.7890,
        lng: -9.1680,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Presidente Samora Machel, Lote 7, Loja Direita, 2620-061 Olival Basto",
        city: "Odivelas",
        website: "https://www.fpdd.org",
        description: "Promoção e desenvolvimento do desporto adaptado em Portugal: modalidades paralímpicas, atividade física terapêutica e inclusão pelo desporto."
    },
    {
        id: '5bcebfba-c8b1-4be5-94ca-ea4b348e3cf5',
        title: "FEDRA — Federação de Doenças Raras de Portugal",
        category: "Direitos & Apoio Social",
        lat: 38.7810,
        lng: -9.1120,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rotunda Nuno Rodrigues dos Santos, 1B, 8.º B, 2685-223 Portela LRS",
        city: "Loures",
        website: "https://www.fedra.pt",
        description: "Representação de doentes com patologias raras: encaminhamento hospitalar, apoio aos cuidadores e divulgação de avanços terapêuticos."
    },
    {
        id: '9142f9e6-ee39-444b-bce9-bfbcfeae1c2f',
        title: "ASBIHP — Associação Spina Bifida e Hidrocefalia de Portugal",
        category: "Direitos & Apoio Social",
        lat: 38.7450,
        lng: -9.1150,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Botelho de Vasconcelos, Lote 567, Letra D, 1900-637 Lisboa",
        city: "Lisboa",
        website: "https://www.asbihp.pt",
        description: "Apoio médico, clínico e social a portadores de Spina Bifida e Hidrocefalia, reabilitação física, fornecimento de materiais e apoio familiar."
    },
    {
        id: '72491b98-bc1c-4395-8fc0-4d3752e50529',
        title: "SPEM — Sociedade Portuguesa de Esclerose Múltipla",
        category: "Direitos & Apoio Social",
        lat: 38.7440,
        lng: -9.1020,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Zófimo Pedroso, 66, 1950-291 Lisboa",
        city: "Lisboa",
        website: "https://www.spem.pt",
        description: "Centro de reabilitação física, fisioterapia neurológica, apoio psicológico e jurídico a pessoas com Esclerose Múltipla e doenças desmielinizantes."
    },
    {
        id: '185038c1-4dfd-4e4f-b6e8-232537b819f7',
        title: "FORMEM — Formação Profissional e Emprego para Pessoas com Deficiência",
        category: "Direitos & Apoio Social",
        lat: 40.2250,
        lng: -8.4310,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Coronel Veiga Simão, Edifício CTVC, 3.º Piso, 3025-307 Coimbra",
        city: "Coimbra",
        website: "https://www.formem.org.pt",
        description: "Rede nacional para capacitação, qualificação profissional e inserção de pessoas com deficiência no mercado de trabalho ordinário."
    },
    {
        id: '1cbb66e3-f667-4a67-b501-ad26f5fa5018',
        title: "CNOD — Confederação Nacional de Organismos de Deficientes",
        category: "Direitos & Apoio Social",
        lat: 38.7490,
        lng: -9.1010,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida João Paulo II, Lote 528, 1.º A, 1950-430 Lisboa",
        city: "Lisboa",
        website: "https://cnod.pt",
        description: "Estrutura confederada que representa as organizações de pessoas com deficiência na negociação de políticas públicas de inclusão e direitos sociais."
    },
    {
        id: '7fc0c754-5c9c-473d-82d2-43093557fbcf',
        title: "Associação Salvador",
        category: "Direitos & Apoio Social",
        lat: 38.7300,
        lng: -9.1480,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Fontes Pereira de Melo, 14, 9.º andar, 1050-121 Lisboa",
        city: "Lisboa",
        website: "https://www.associacaosalvador.com",
        description: "Apoio a pessoas com deficiência motora através de bolsas de estudo, atribuição de equipamentos adaptados, desporto e mentoria para emprego."
    },
    {
        id: '41ebefd7-d703-4a11-8e50-9aebe24921b7',
        title: "CVI — Centro de Vida Independente",
        category: "Direitos & Apoio Social",
        lat: 38.7485,
        lng: -9.1005,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida João Paulo II, Lote 526, R/C, Loja A, 1950-159 Lisboa",
        city: "Lisboa",
        website: "https://www.vidaindependente.org",
        description: "Gestão de Centros de Apoio à Vida Independente (CAVI): assistência pessoal personalizada para autonomia e autodeterminação no dia a dia."
    },

    // ============================================================
    // 🏛️ INFRAESTRUTURA DE ESTADO (IRN / SEGURANÇA SOCIAL / FINANÇAS)
    // ============================================================
    {
        id: 'p-irn-campus',
        title: "IRN – Campus da Justiça (Nacionalidade & Registos)",
        category: "Residência & Vistos",
        lat: 38.7665,
        lng: -9.0965,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Avenida Dom João II, Lote 1.08.01, Edifício H, 1990-097 Lisboa",
        city: "Lisboa",
        website: "https://irn.justica.gov.pt",
        description: "Conservatória dos Registos Centrais e balcão do IRN no Parque das Nações: processos de nacionalidade portuguesa, certidões e registo civil."
    },
    {
        id: 'p-ss-sede',
        title: "Segurança Social (Sede Central – NISS)",
        category: "Direitos & Apoio Social",
        lat: 38.7450,
        lng: -9.1450,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua Rosa Araújo, 43, 1250-194 Lisboa",
        city: "Lisboa",
        website: "https://www.seg-social.pt",
        description: "Serviço de atendimento oficial da Segurança Social: atribuição de NISS para trabalhadores e estudantes, abonos de família e prestações sociais."
    },
    {
        id: 'p-at-financas',
        title: "Autoridade Tributária e Aduaneira (Finanças Central – NIF)",
        category: "Finanças & Impostos",
        lat: 38.7180,
        lng: -9.1410,
        distance: "...",
        ratings: [],
        avgRating: 5.0,
        address: "Rua da Alfândega, 5, 1100-016 Lisboa",
        city: "Lisboa",
        website: "https://www.portaldasfinancas.gov.pt",
        description: "Serviço de Finanças em Lisboa: emissão e validação de NIF, nomeação de representante fiscal, início de atividade e entrega de declarações de IRS."
    }
];
