import { MapAlert } from '../types';

export const NATIONALITY_ASSOCIATIONS_DATABASE: MapAlert[] = [
    // ============================================================
    // 🇸🇳 SENEGAL & ÁFRICA OCIDENTAL
    // ============================================================
    {
        id: 'assoc-sn-conquista-vontades',
        title: "Conquista Vontades – Associação dos Imigrantes Senegaleses em Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Senegalesa & Africana",
        description: "Apoio à legalização AIMA, reagrupamento familiar, apoio jurídico, saúde, formação e inserção laboral. Aberta a migrantes de todas as origens.",
        lat: 41.5454,
        lng: -8.4265,
        distance: "...",
        address: "Travessa do Bonfim, Nº 3 R/C / Atendimento Junta de Freguesia de Maximinos, 4700-015 Braga",
        city: "Braga",
        email: "atendimento.aisp@gmail.com",
        website: "https://www.facebook.com/ConquistaVontades/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇨🇻 CABO VERDE (LISBOA, SETÚBAL, COIMBRA, PORTO, AMADORA)
    // ============================================================
    {
        id: 'assoc-cv-acv-lisboa',
        title: "Associação Caboverdeana de Lisboa (ACV)",
        category: "Comunidade & Apoio",
        type: "Comunidade Cabo-Verdiana",
        description: "Polo histórico de acolhimento e integração da diáspora cabo-verdiana em Portugal. Apoio social, dinamização cultural e mediação cívica.",
        lat: 38.7235,
        lng: -9.1485,
        distance: "...",
        address: "Rua Duque de Palmela, n.º 2, 8.º andar, 1250-098 Lisboa",
        city: "Lisboa",
        phone: "(+351) 213 532 020",
        email: "secretariageral@acvlisboa.org",
        website: "https://acvlisboa.org",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cv-setubal-acvs',
        title: "ACVS – Associação Caboverdiana de Setúbal",
        category: "Comunidade & Apoio",
        type: "Comunidade Cabo-Verdiana",
        description: "IPSS de referência fundada em 1983. Apoio social e jurídico a imigrantes, inclusão comunitária e combate à exclusão social na Margem Sul.",
        lat: 38.5340,
        lng: -8.8780,
        distance: "...",
        address: "Rua do Antigo Olival, 8 - E11, Bairro da Bela Vista, 2910-060 Setúbal",
        city: "Setúbal",
        phone: "(+351) 265 771 002",
        email: "acvs@acvsetubal.org",
        website: "http://www.acvsetubal.org",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cv-coimbra-ccvc',
        title: "Casa de Cabo Verde em Coimbra (CCVC)",
        category: "Comunidade & Apoio",
        type: "Comunidade Cabo-Verdiana",
        description: "Acolhimento da comunidade cabo-verdiana na Região Centro, apoio a doentes evacuados ao abrigo de acordos de saúde, apoio a famílias e estudantes.",
        lat: 40.2033,
        lng: -8.4103,
        distance: "...",
        address: "Rua Padre António Vieira, Edifício AAC, 3000-315 Coimbra",
        city: "Coimbra",
        email: "aecvc@ci.uc.pt",
        website: "https://www.facebook.com/p/Casa-de-Cabo-Verde-em-Coimbra-100083236302482/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cv-coimbra-aecvc',
        title: "Associação de Estudantes Cabo-verdianos em Coimbra (AECVC)",
        category: "Comunidade & Apoio",
        type: "Comunidade Cabo-Verdiana & Estudantes",
        description: "Apoio na integração académica e universitária, habitação estudantil, vistos de estudo e acolhimento na Universidade de Coimbra.",
        lat: 40.2085,
        lng: -8.4250,
        distance: "...",
        address: "Edifício AAC, Rua Padre António Vieira, 3000-315 Coimbra",
        city: "Coimbra",
        email: "aecvc@ci.uc.pt",
        website: "https://www.facebook.com/AECVC.coimbra",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cv-porto',
        title: "Associação Cabo-Verdiana do Norte de Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Cabo-Verdiana",
        description: "Representação e assistência a cabo-verdianos e luso-descendentes na Área Metropolitana do Porto e Norte do país.",
        lat: 41.1485,
        lng: -8.6042,
        distance: "...",
        address: "Rua Formosa, 408, 1.º andar, 4000-249 Porto",
        city: "Porto",
        phone: "(+351) 222 005 321",
        website: "https://www.facebook.com/associacaocaboverdianadoporto/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cv-moinho-juventude',
        title: "Associação Cultural Moinho da Juventude",
        category: "Comunidade & Apoio",
        type: "Comunidade Cabo-Verdiana & Afrodescendente",
        description: "Intervenção comunitária na Cova da Moura: creche, formação profissional, mediação jurídica, apoio a mães migrantes e direitos cívicos.",
        lat: 38.7456,
        lng: -9.2152,
        distance: "...",
        address: "Bairro do Alto da Cova da Moura, 2700-000 Amadora",
        city: "Amadora",
        phone: "(+351) 214 971 748",
        email: "dir-acmj@moinhodajuventude.pt",
        website: "https://moinhodajuventude.pt",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇸🇹 SÃO TOMÉ E PRÍNCIPE
    // ============================================================
    {
        id: 'assoc-st-acosp',
        title: "ACOSP – Associação da Comunidade de S. Tomé e Príncipe em Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Santomense",
        description: "Porta-voz da comunidade santomense em território nacional. Auxílio a famílias, encaminhamento em juntas médicas e apoio à integração social.",
        lat: 38.7505,
        lng: -9.1980,
        distance: "...",
        address: "Estrada de Benfica, Edifício Castelo Norte, 1500-100 Lisboa",
        city: "Lisboa",
        email: "acosp@hotmail.com",
        website: "https://www.facebook.com/p/ACOSP-Associa%C3%A7%C3%A3o-da-Comunidade-de-S-Tom%C3%A9-e-Pr%C3%ADncipe-em-Portugal-100064619379893/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-st-aesp',
        title: "AESP – Associação dos Estudantes São-Tomenses em Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Santomense & Estudantes",
        description: "Apoio a jovens e estudantes são-tomenses em Portugal: regularização de vistos de estudo, bolsas, alojamento e vida comunitária.",
        lat: 38.7300,
        lng: -9.1400,
        distance: "...",
        address: "Avenida Professor Egas Moniz, Edifício Cantina Velha, 1649-004 Lisboa",
        city: "Lisboa",
        website: "https://www.facebook.com/aesp.portugal/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇦🇴 ANGOLA
    // ============================================================
    {
        id: 'assoc-ao-casadeangola',
        title: "Casa de Angola em Lisboa",
        category: "Comunidade & Apoio",
        type: "Comunidade Angolana",
        description: "Instituição histórica fundada em 1970. Espaço cultural e de convívio, apoio à integração da diáspora angolana e laços comunitários em Portugal.",
        lat: 38.7208,
        lng: -9.1552,
        distance: "...",
        address: "Travessa Fábrica das Sedas, 7, 1250-107 Lisboa (Rato)",
        city: "Lisboa",
        phone: "(+351) 213 863 111",
        email: "casadeangola1971@gmail.com",
        website: "https://www.facebook.com/casadeangolalisboa/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-ao-aaaa-setubal',
        title: "Associação de Angolanos e Amigos de Angola em Setúbal (AAAA)",
        category: "Comunidade & Apoio",
        type: "Comunidade Angolana",
        description: "Apoio social e integração de imigrantes de origem angolana e africana na península de Setúbal, apoio alimentar e orientação.",
        lat: 38.5244,
        lng: -8.8930,
        distance: "...",
        address: "Rua dos Trabalhadores do Mar, 2900-650 Setúbal",
        city: "Setúbal",
        website: "https://www.facebook.com/angolanosamigosdesetubal/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇬🇼 GUINÉ-BISSAU & ÁFRICA LUSÓFONA
    // ============================================================
    {
        id: 'assoc-gw-aigast',
        title: "AIGAST – Associação dos Imigrantes Guineenses Amigos Sul do Tejo",
        category: "Comunidade & Apoio",
        type: "Comunidade Guineense",
        description: "Mediação intercultural, apoio social, formação e apoio ao emprego para a comunidade guineense na Margem Sul (Baixa da Banheira / Moita).",
        lat: 38.6580,
        lng: -9.0430,
        distance: "...",
        address: "Mercado Municipal do Vale da Amoreira, L 8, 2835-240 Moita",
        city: "Setúbal",
        email: "aigast.associacao1@gmail.com",
        website: "https://www.facebook.com/associacaoaigast/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-gw-pdg',
        title: "Plataforma das Associações Guineenses na Diáspora (PDG)",
        category: "Comunidade & Apoio",
        type: "Comunidade Guineense",
        description: "Rede nacional e internacional que congrega associações guineenses em Portugal para representação institucional junto da AIMA e Estado.",
        lat: 38.7223,
        lng: -9.1393,
        distance: "...",
        address: "Lisboa / Nacional",
        city: "Lisboa",
        email: "diaspora@gb.imvf.org",
        website: "https://diasporagb.org",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇲🇿 MOÇAMBIQUE
    // ============================================================
    {
        id: 'assoc-mz-casademocambique',
        title: "Casa de Moçambique em Lisboa",
        category: "Comunidade & Apoio",
        type: "Comunidade Moçambicana",
        description: "Apoio social e comunitário aos moçambicanos em Portugal, promoção cultural, bolsas de estudo e cooperação solidária.",
        lat: 38.7265,
        lng: -9.1450,
        distance: "...",
        address: "Rua de Santa Marta, 1150-293 Lisboa",
        city: "Lisboa",
        email: "geral@casademocambique.com",
        website: "https://casademocambique.com",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇳🇵 NEPAL
    // ============================================================
    {
        id: 'assoc-np-nialp',
        title: "NIALP – Intercultural Association (CLAIM Martim Moniz)",
        category: "Residência & Vistos",
        type: "Comunidade Nepalesa & Sul-Asiática",
        description: "Centro Local de Apoio à Integração de Migrantes (CLAIM oficial AIMA). Apoio em tradução nepalesa/inglesa, agendamentos, NIF, NISS e acolhimento.",
        lat: 38.7153,
        lng: -9.1362,
        distance: "...",
        address: "R. do Arco do Marquês de Alegrete 4, Esc. 2.4, 1100-034 Lisboa (Martim Moniz)",
        city: "Lisboa",
        phone: "(+351) 218 864 503",
        email: "info@nialp.pt",
        website: "https://nialp.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-np-nrna',
        title: "NRNA Portugal – Non-Resident Nepali Association",
        category: "Comunidade & Apoio",
        type: "Comunidade Nepalesa",
        description: "Representação de direitos dos cidadãos nepaleses em Portugal, auxílio em situações de emergência, apoio laboral e ligação consular.",
        lat: 38.7180,
        lng: -9.1380,
        distance: "...",
        address: "Calçada de Santana, 1150-302 Lisboa",
        city: "Lisboa",
        email: "president.nrna@gmail.com",
        website: "https://nrnportugal.org",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇮🇳 ÍNDIA
    // ============================================================
    {
        id: 'assoc-in-comunidadehindu',
        title: "Comunidade Hindu de Portugal (Templo Radha Krishna)",
        category: "Comunidade & Apoio",
        type: "Comunidade Indiana & Hindu",
        description: "Centro comunitário e espiritual de apoio à comunidade indiana: assistência alimentar, ensino de línguas, apoio social a famílias migrantes.",
        lat: 38.7675,
        lng: -9.1605,
        distance: "...",
        address: "Alameda Mahatma Gandhi, 1600-500 Lisboa (Lumiar)",
        city: "Lisboa",
        phone: "(+351) 217 576 524",
        email: "secretaria@comunidadehindu.org",
        website: "https://www.comunidadehindu.org",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-in-bhoomi',
        title: "Bhoomi – Associação Cultural Indiana e Solidariedade Social",
        category: "Comunidade & Apoio",
        type: "Comunidade Indiana",
        description: "Apoio sociocultural, workshops de integração, orientação laboral e ajuda mútua para trabalhadores e famílias indianas em Portugal.",
        lat: 38.7300,
        lng: -9.1450,
        distance: "...",
        address: "Alameda D. Afonso Henriques, 74, 1000-123 Lisboa",
        city: "Lisboa",
        email: "admin@bhoomi-portugal.com",
        website: "https://bhoomi-portugal.com",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-in-sikh-temple',
        title: "Gurdwara Sikh Sangat Sahib (Comunidade Sikh de Portugal)",
        category: "Comunidade & Apoio",
        type: "Comunidade Sikh & Indiana",
        description: "Acolhimento comunitário e refeições diárias gratuitas (Langar comunitário) para trabalhadores migrantes e pessoas vulneráveis em Odivelas.",
        lat: 38.7905,
        lng: -9.1820,
        distance: "...",
        address: "Rua Actor Chaby Pinheiro / Rua José Duarte Lexim, 2675-234 Odivelas",
        city: "Odivelas",
        email: "gurdwaralisbon@gmail.com",
        website: "https://www.facebook.com/p/Gurdwara-Sahib-sikh-sangat-Lisbon-100064893701633/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-in-acli',
        title: "ACLI – Associação Cultural Luso-Indiana",
        category: "Comunidade & Apoio",
        type: "Comunidade Indiana",
        description: "Dinamização cultural e apoio comunitário à população de origem indiana e luso-indiana em Loures e Lisboa.",
        lat: 38.7880,
        lng: -9.1710,
        distance: "...",
        address: "Olival Basto, 2620-061 Loures",
        city: "Loures",
        website: "https://www.facebook.com/acliportugal/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇧🇩 BANGLADESH
    // ============================================================
    {
        id: 'assoc-bd-baitul-mukarram',
        title: "Centro Comunitário e Islâmico do Bangladesh (Baitul Mukarram)",
        category: "Comunidade & Apoio",
        type: "Comunidade Bangladesiana",
        description: "Centro comunitário de apoio à comunidade do Bangladesh na Mouraria: mediação linguística, apoio na procura de emprego e solidariedade social.",
        lat: 38.7160,
        lng: -9.1355,
        distance: "...",
        address: "Rua do Benformoso, 1100-394 Lisboa (Mouraria)",
        city: "Lisboa",
        phone: "(+351) 218 877 120",
        email: "masjid.cib@gmail.com",
        website: "https://www.facebook.com/baitulmukarramlisbon/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-bd-community-pt',
        title: "Associação da Comunidade do Bangladesh em Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Bangladesiana",
        description: "Representação associativa, acolhimento de novos residentes e defesa de direitos laborais dos imigrantes bengaleses.",
        lat: 38.7170,
        lng: -9.1360,
        distance: "...",
        address: "Martim Moniz, 1100-034 Lisboa",
        city: "Lisboa",
        website: "https://www.facebook.com/bangladeshcommunityinportugal/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇵🇰 PAQUISTÃO
    // ============================================================
    {
        id: 'assoc-pk-cultural-center',
        title: "Centro Cultural e Comunitário Paquistanês em Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Paquistanesa",
        description: "Apoio a trabalhadores paquistaneses, mediação cultural, ajuda na regularização documental e suporte a famílias.",
        lat: 38.7500,
        lng: -9.1600,
        distance: "...",
        address: "Rua da Palma, 268, 1100-394 Lisboa",
        city: "Lisboa",
        website: "https://www.facebook.com/pakistancommunityportugal/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇵🇭 FILIPINAS
    // ============================================================
    {
        id: 'assoc-ph-filcom',
        title: "AFP – Associação Filipino-Portuguesa",
        category: "Comunidade & Apoio",
        type: "Comunidade Filipina",
        description: "Rede de apoio mútuo para a comunidade filipina em Portugal: inserção no mercado de trabalho, contratos legais e eventos sociais.",
        lat: 38.7200,
        lng: -9.1450,
        distance: "...",
        address: "Rua da Madalena, 80, 1100-322 Lisboa",
        city: "Lisboa",
        website: "https://www.facebook.com/filipinoportuguese/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-ph-catholic',
        title: "Comunidade Católica Filipina em Lisboa",
        category: "Comunidade & Apoio",
        type: "Comunidade Filipina",
        description: "Espaço de acolhimento pastoral e suporte social com celebrações e apoio comunitário em Tagalo e Inglês.",
        lat: 38.7130,
        lng: -9.1600,
        distance: "...",
        address: "Basílica da Estrela, Praça da Estrela, 1200-667 Lisboa",
        city: "Lisboa",
        website: "https://www.facebook.com/filipinocommunitylisbon/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇨🇳 CHINA
    // ============================================================
    {
        id: 'assoc-cn-apcp',
        title: "Associação Geral dos Chineses em Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Chinesa",
        description: "Associação Geral dos Chineses em Portugal. Apoio a comerciantes e famílias, mediação com autoridades locais e preservação cultural.",
        lat: 38.7185,
        lng: -9.1350,
        distance: "...",
        address: "Rua da Palma, 268, 1.º andar, 1100-394 Lisboa (Martim Moniz)",
        city: "Lisboa",
        phone: "(+351) 218 860 188",
        website: "https://www.facebook.com/chinesesemportugal/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cn-norte',
        title: "Associação dos Comerciantes e Industriais Luso-Chineses do Norte",
        category: "Comunidade & Apoio",
        type: "Comunidade Chinesa",
        description: "Apoio a empresários e trabalhadores chineses no Grande Porto e Norte de Portugal (Varziela / Vila do Conde).",
        lat: 41.3450,
        lng: -8.7200,
        distance: "...",
        address: "Zona Industrial da Varziela, 4480-000 Vila do Conde",
        city: "Porto",
        website: "https://www.facebook.com/comercianteschinesesnorte/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇺🇦 UCRÂNIA (LISBOA, ALGARVE, VILA FRANCA DE XIRA, SANTARÉM)
    // ============================================================
    {
        id: 'assoc-ua-spilka',
        title: "Associação dos Ucranianos em Portugal (Spilka)",
        category: "Comunidade & Apoio",
        type: "Comunidade Ucraniana",
        description: "A principal instituição de apoio a ucranianos em Portugal. Aulas de Português (PLA), apoio jurídico, inserção escolar e apoio a refugiados.",
        lat: 38.7225,
        lng: -9.1380,
        distance: "...",
        address: "Rua Félix Correia, n.º 1, 1500-271 Lisboa",
        city: "Lisboa",
        phone: "(+351) 217 577 154",
        email: "ukrspilka@gmail.com",
        website: "https://spilka.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-ua-algarve',
        title: "Associação dos Ucranianos do Algarve",
        category: "Comunidade & Apoio",
        type: "Comunidade Ucraniana",
        description: "Apoio direto a refugiados e famílias ucranianas residentes no Algarve (Faro, Portimão, Albufeira, Loulé).",
        lat: 37.0185,
        lng: -7.9310,
        distance: "...",
        address: "Rua do Alportel, 8000-293 Faro",
        city: "Faro",
        email: "algarve@spilka.pt",
        website: "https://www.facebook.com/ucranianosdoalgarve/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-ua-vfx',
        title: "Associação de Apoio à Comunidade Ucraniana de VFX",
        category: "Comunidade & Apoio",
        type: "Comunidade Ucraniana",
        description: "Apoio a imigrantes e refugiados de Leste no concelho de Vila Franca de Xira e Grande Lisboa.",
        lat: 38.9550,
        lng: -8.9900,
        distance: "...",
        address: "Rua Dr. Manuel de Arriaga, 2600-186 Vila Franca de Xira",
        city: "Vila Franca de Xira",
        website: "https://www.facebook.com/associacaoucranianavfx/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-ua-humanitaria',
        title: "Associação Humanitária de Ajuda à Ucrânia",
        category: "Comunidade & Apoio",
        type: "Comunidade Ucraniana & Refugiados",
        description: "Assistência humanitária direta, encaminhamento para habitação e emprego e doação de bens essenciais para famílias ucranianas.",
        lat: 38.7300,
        lng: -9.1450,
        distance: "...",
        address: "Avenida Conde de Valbom, 1050-068 Lisboa",
        city: "Lisboa",
        email: "ajuda.ucrania@gmail.com",
        website: "https://www.facebook.com/ajudaucrania.pt/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇲🇩 MOLDÁVIA & ROMÉNIA
    // ============================================================
    {
        id: 'assoc-md-miorita',
        title: "Associação Cultural Miorita (Comunidade Moldava e Romena)",
        category: "Comunidade & Apoio",
        type: "Comunidade Moldava & Romena",
        description: "Apoio social e jurídico para regularização de cidadãos da Europa de Leste, celebrações comunitárias e apoio laboral em Setúbal.",
        lat: 38.5280,
        lng: -8.8910,
        distance: "...",
        address: "Avenida Alexandre Herculano, 2900-205 Setúbal",
        city: "Setúbal",
        phone: "(+351) 964 883 451",
        email: "associacao.miorita@gmail.com",
        website: "https://www.facebook.com/miorita.portugal/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-md-tezaur',
        title: "Associação Tezaur – Tradições Romenas e Moldavas",
        category: "Comunidade & Apoio",
        type: "Comunidade Moldava & Romena",
        description: "Preservação da língua e cultura moldava, apoio na integração de crianças e assistência à comunidade moldava no Barreiro e Setúbal.",
        lat: 38.6600,
        lng: -9.0700,
        distance: "...",
        address: "Rua Miguel Bombarda, 2830-355 Barreiro",
        city: "Setúbal",
        website: "https://www.facebook.com/tezaur.portugal/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-md-moldavo-cascais',
        title: "Centro Cultural Moldavo de Cascais",
        category: "Comunidade & Apoio",
        type: "Comunidade Moldava",
        description: "Atendimento e apoio social à integração de cidadãos moldavos e leste-europeus em Cascais e Grande Lisboa.",
        lat: 38.7210,
        lng: -9.3620,
        distance: "...",
        address: "Rua José Malhoa, 11, Trajouce, 2785-657 São Domingos de Rana",
        city: "Cascais",
        phone: "(+351) 963 800 299",
        email: "centroculturalmoldavo@gmail.com",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇧🇬 BULGÁRIA & 🇵🇱 POLÓNIA
    // ============================================================
    {
        id: 'assoc-bg-bulgari',
        title: "Búlgari – Associação dos Búlgaros em Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Búlgara",
        description: "Apoio à integração de famílias búlgaras na Área Metropolitana de Lisboa e concelho de Cascais.",
        lat: 38.7050,
        lng: -9.3980,
        distance: "...",
        address: "Estoril, 2765-000 Cascais",
        city: "Cascais",
        website: "https://www.facebook.com/bulgariancommunityportugal/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-pl-amizade',
        title: "Associação Amizade Portugal-Polónia",
        category: "Comunidade & Apoio",
        type: "Comunidade Polaca",
        description: "Apoio e aproximação cultural da comunidade polaca residente em Portugal, com sede no Minho / Braga.",
        lat: 41.5500,
        lng: -8.4200,
        distance: "...",
        address: "Braga, 4700-000 Braga",
        city: "Braga",
        website: "https://www.facebook.com/amizadeportugalpolonia/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇻🇪 VENEZUELA, 🇨🇴 COLÔMBIA & AMÉRICA LATINA
    // ============================================================
    {
        id: 'assoc-ve-venexos',
        email: "lisboa@venexos.org",
        title: "Venexos Portugal (Rede de Apoio a Venezuelanos)",
        category: "Comunidade & Apoio",
        type: "Comunidade Venezuelana",
        description: "Rede de apoio a refugiados e migrantes venezuelanos: equivalência de diplomas universitários, integração profissional e acolhimento.",
        lat: 38.7223,
        lng: -9.1393,
        distance: "...",
        address: "Avenida da Liberdade, 245, 1250-143 Lisboa",
        city: "Lisboa",
        website: "https://venexos.org",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-co-asocolombia',
        title: "Asocolombia – Comunidade Colombiana em Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Colombiana",
        description: "Apoio à integração, partilha de oportunidades e orientação comunitária para cidadãos colombianos e hispanofalantes.",
        lat: 38.7200,
        lng: -9.1400,
        distance: "...",
        address: "Rua do Alecrim, 26, 1200-018 Lisboa",
        city: "Lisboa",
        website: "https://www.facebook.com/colombianosenportugaloficial/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-latam-casa-america-latina',
        title: "Casa da América Latina",
        category: "Comunidade & Apoio",
        type: "Comunidades Latino-Americanas",
        description: "Polo de referência e cooperação para todas as nacionalidades da América Latina em Portugal (Brasil, Argentina, Chile, Colômbia, Peru, etc.).",
        lat: 38.6965,
        lng: -9.1985,
        distance: "...",
        address: "Avenida da Índia, 110, 1300-300 Lisboa",
        city: "Lisboa",
        phone: "(+351) 213 617 230",
        email: "info@casamericalatina.pt",
        website: "https://casamericalatina.pt",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🇬🇧 REINO UNIDO, 🇫🇷 FRANÇA & 🇮🇹 ITÁLIA (EXPATS & RESIDENTES)
    // ============================================================
    {
        id: 'assoc-uk-afpop',
        title: "afpop – Portugal Foreign Residents Association",
        category: "Comunidade & Apoio",
        type: "Residentes Estrangeiros / Expats",
        description: "A maior associação de residentes estrangeiros em Portugal. Apoio burocrático, fiscal, SNS e jurídico em língua inglesa e multilingue.",
        lat: 37.1350,
        lng: -8.5350,
        distance: "...",
        address: "Lote 6 Loja C, Urb. Quinta do Morais, Poço Fojo, 8501-917 Portimão",
        city: "Portimão",
        email: "info@afpop.com",
        website: "https://afpop.com",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-fr-afnp',
        title: "AFNP – Association des Français du Nord du Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Francesa & Francófona",
        description: "Apoio e acolhimento a famílias e trabalhadores francófonos no Porto e Norte de Portugal.",
        lat: 41.1500,
        lng: -8.6100,
        distance: "...",
        address: "Rua de Santa Catarina, 120, 4000-447 Porto",
        city: "Porto",
        email: "contact@afnp.fr",
        website: "https://afnp.fr",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-it-algarve',
        title: "Associazione Italiani in Algarve",
        category: "Comunidade & Apoio",
        type: "Comunidade Italiana",
        description: "Apoio à integração, apoio consular e atividades comunitárias para cidadãos italianos residentes no Algarve.",
        lat: 37.1380,
        lng: -8.0200,
        distance: "...",
        address: "Avenida 5 de Outubro, 76, 8135-100 Almancil",
        city: "Faro",
        website: "https://www.facebook.com/italianinalgarve/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🤝 ASSOCIAÇÕES MULTICULTURAIS INTEGRADAS
    // ============================================================
    {
        id: 'assoc-pt-amizade-gondomar',
        title: "AMIZADE – Associação de Imigrantes de Gondomar",
        category: "Comunidade & Apoio",
        type: "Apoio Multicultural",
        description: "Acolhimento e integração social de migrantes no Grande Porto: documentação, apoios sociais e apoio escolar.",
        lat: 41.1440,
        lng: -8.5320,
        distance: "...",
        address: "Gondomar, 4420-000 Porto",
        city: "Porto",
        email: "amizade_leste@hotmail.com",
        website: "https://www.facebook.com/amizadegondomar/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-pt-nasce-renasce',
        title: "Associação Nasce e Renasce (Mediação Intercultural)",
        category: "Comunidade & Apoio",
        type: "Apoio Multicultural & Famílias",
        description: "Apoio a famílias migrantes em contexto de vulnerabilidade, mediação escolar e inclusão social na Musgueira / Lumiar.",
        lat: 38.7750,
        lng: -9.1550,
        distance: "...",
        address: "Bairro da Musgueira, Lumiar, 1750-000 Lisboa",
        city: "Lisboa",
        website: "https://www.facebook.com/nasceerenasce/",
        ratings: [],
        avgRating: 5.0
    },

    // ============================================================
    // 🌟 ASSOCIAÇÕES & SERVIÇOS VERIFICADOS (MIRA 2026)
    // ============================================================
    {
        id: 'assoc-cv-coimbra-geral',
        title: "Associação dos Caboverdianos em Coimbra",
        category: "Comunidade & Apoio",
        type: "Comunidade Cabo-Verdiana",
        description: "Acolhimento comunitário, integração social e apoio a famílias cabo-verdianas no distrito de Coimbra.",
        lat: 40.2056,
        lng: -8.4195,
        distance: "...",
        address: "Coimbra, 3000 Coimbra",
        city: "Coimbra",
        email: "caboverdianoscoimbra@gmail.com",
        website: "https://www.facebook.com/caboverdianoscoimbra",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-proabracar',
        title: "Associação ProAbraçar – Apoio e Inclusão Social",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Migrantes",
        description: "Apoio social, ajuda alimentar e encaminhamento de migrantes e famílias em situação de vulnerabilidade.",
        lat: 38.7436,
        lng: -9.1602,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "geral@proabracar.pt",
        website: "https://proabracar.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-salvador-inclusao',
        title: "Associação Salvador – Apoio a Pessoas com Deficiência Motora",
        category: "Comunidade & Apoio",
        type: "Inclusão & Acessibilidade",
        description: "Projetos de integração social, emprego adaptado, desporto e apoio à vida ativa para pessoas com deficiência motora.",
        lat: 38.7185,
        lng: -9.1412,
        distance: "...",
        address: "Av. Fontes Pereira de Melo, 14, 1050-121 Lisboa",
        city: "Lisboa",
        email: "info@associacaosalvador.com",
        website: "https://associacaosalvador.com",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-banco-alimentar-fed',
        title: "Federação Portuguesa dos Bancos Alimentares contra a Fome",
        category: "Comunidade & Apoio",
        type: "Apoio Alimentar & Emergência",
        description: "Coordenação nacional dos Bancos Alimentares em Portugal. Apoio alimentar de emergência a famílias e migrantes.",
        lat: 38.736,
        lng: -9.183,
        distance: "...",
        address: "Av. de Ceuta, Estação de Alcântara-Terra, 1300-125 Lisboa",
        city: "Lisboa",
        email: "ba.federacao@bancoalimentar.pt",
        website: "https://bancoalimentar.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-asbihp-sede',
        title: "ASBIHP – Associação Spina Bífida e Hidrocefalia de Portugal",
        category: "Comunidade & Apoio",
        type: "Saúde & Apoio Especializado",
        description: "Apoio médico-social, psicológico, direitos civis e integração comunitária de portadores de Spina Bífida e Hidrocefalia.",
        lat: 38.756,
        lng: -9.155,
        distance: "...",
        address: "Rua do Lumiar, 1750-160 Lisboa",
        city: "Lisboa",
        email: "sede@asbihp.pt",
        website: "https://asbihp.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cpr-sede',
        title: "CPR – Conselho Português para os Refugiados (Sede)",
        category: "Residência & Vistos",
        type: "Asilo & Apoio Jurídico",
        description: "Apoio jurídico, acolhimento humanitário, integração de refugiados e requerentes de proteção internacional.",
        lat: 38.7845,
        lng: -9.102,
        distance: "...",
        address: "Bairro Armador, Zona M de Chelas, 1950-012 Lisboa",
        city: "Lisboa",
        email: "geral@cpr.pt",
        website: "https://cpr.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-casa-america-latina',
        title: "Casa da América Latina em Portugal",
        category: "Comunidade & Apoio",
        type: "Comunidade Latino-Americana",
        description: "Polo cultural, cooperação e integração dos cidadãos da América Latina em Portugal.",
        lat: 38.697,
        lng: -9.198,
        distance: "...",
        address: "Avenida da Índia, 110, 1300-300 Lisboa",
        city: "Lisboa",
        email: "geral@casamericalatina.pt",
        website: "https://casamericalatina.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-renovar-mouraria',
        title: "Associação Renovar a Mouraria",
        category: "Comunidade & Apoio",
        type: "Integração Comunitária Intercultural",
        description: "Apoio a imigrantes, aulas de português gratuitas, mediação intercultural e apoio social no centro de Lisboa.",
        lat: 38.716,
        lng: -9.135,
        distance: "...",
        address: "Beco do Rosendo, 8-10, Mouraria, 1100-460 Lisboa",
        city: "Lisboa",
        email: "geral@renovaramouraria.pt",
        website: "https://renovaramouraria.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-sos-racismo-lisboa',
        title: "SOS Racismo – Sede Nacional (Lisboa)",
        category: "Comunidade & Apoio",
        type: "Direitos Humanos & Apoio Antidiscriminação",
        description: "Apoio jurídico e acompanhamento de queixas contra discriminação racial, apoio a imigrantes e promoção da igualdade.",
        lat: 38.72,
        lng: -9.138,
        distance: "...",
        address: "Rua de São Bento, 1200-815 Lisboa",
        city: "Lisboa",
        email: "sosracismo@gmail.com",
        website: "https://sosracismo.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-sos-racismo-porto',
        title: "SOS Racismo – Delegação do Porto",
        category: "Comunidade & Apoio",
        type: "Direitos Humanos & Apoio Antidiscriminação",
        description: "Apoio jurídico e mediação no combate ao racismo e apoio à regularização de migrantes no Norte.",
        lat: 41.151,
        lng: -8.61,
        distance: "...",
        address: "Rua do Bonjardim, 4000-115 Porto",
        city: "Porto",
        email: "porto@sosracismo.pt",
        website: "https://sosracismo.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-femafro',
        title: "Femafro – Associação de Mulheres Negras, Africanas e Afrodescendentes",
        category: "Comunidade & Apoio",
        type: "Apoio Comunitário & Mulheres",
        description: "Promoção dos direitos humanos, igualdade de oportunidades e empoderamento de mulheres imigrantes e afrodescendentes.",
        lat: 38.73,
        lng: -9.14,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "femafroportugal@gmail.com",
        website: "https://femafro.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-mundo-feliz',
        title: "Associação Mundo Feliz – Apoio Social e Migrantes",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Integração",
        description: "Apoio de primeira linha a imigrantes, alimentação, vestuário e orientação documental.",
        lat: 38.715,
        lng: -9.13,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "geral@mundofeliz.pt",
        website: "https://mundofeliz.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-open-gate',
        title: "Open Gate Portugal – Associação de Integração e Acolhimento",
        category: "Comunidade & Apoio",
        type: "Acolhimento & Capacitação",
        description: "Workshops de integração, língua portuguesa, mentoria profissional e apoio prático à instalação de recém-chegados.",
        lat: 38.74,
        lng: -9.15,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "info@opengateportugal.com",
        website: "https://opengateportugal.com",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-plataforma-dh',
        title: "Plataforma Direitos Humanos em Portugal",
        category: "Comunidade & Apoio",
        type: "Direitos Humanos & Cidadania",
        description: "Rede de cooperação para a defesa dos direitos fundamentais dos migrantes e refugiados em território português.",
        lat: 38.725,
        lng: -9.145,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "geral@plataformadh.pt",
        website: "https://plataformadh.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cruz-vermelha-geral',
        title: "Cruz Vermelha Portuguesa – Sede Nacional",
        category: "Comunidade & Apoio",
        type: "Apoio Humanitário & Emergência",
        description: "Apoio humanitário integral, acolhimento de emergência, saúde e apoio a migrantes e refugiados em todo o território.",
        lat: 38.706,
        lng: -9.162,
        distance: "...",
        address: "Jardim 9 de Abril, 1 a 5, 1249-083 Lisboa",
        city: "Lisboa",
        email: "sede@cruzvermelha.org.pt",
        website: "https://cruzvermelha.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cruz-vermelha-coop',
        title: "Cruz Vermelha Portuguesa – Cooperação e Migrações",
        category: "Comunidade & Apoio",
        type: "Apoio Humanitário & Migrações",
        description: "Gabinete especializado em migrações, apoio a requerentes de asilo, reagrupamento familiar e proteção de vulneráveis.",
        lat: 38.7065,
        lng: -9.1625,
        distance: "...",
        address: "Jardim 9 de Abril, 1 a 5, 1249-083 Lisboa",
        city: "Lisboa",
        email: "cooperacao@cruzvermelha.org.pt",
        website: "https://cruzvermelha.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-cruz-vermelha-refugiados',
        title: "Cruz Vermelha Portuguesa – Acolhimento a Refugiados",
        category: "Comunidade & Apoio",
        type: "Asilo & Acolhimento",
        description: "Coordenação de centros de acolhimento e programas de integração para requerentes de proteção internacional.",
        lat: 38.707,
        lng: -9.163,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "joana.rodrigues@cruzvermelha.org.pt",
        website: "https://cruzvermelha.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-vida-independente',
        title: "Centro de Apoio à Vida Independente (CAVI)",
        category: "Comunidade & Apoio",
        type: "Apoio a Pessoas com Deficiência",
        description: "Assistência pessoal, autonomia e direitos das pessoas com deficiência em Portugal.",
        lat: 38.735,
        lng: -9.155,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "geral@vidaindependente.org",
        website: "https://vidaindependente.org",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-ocpm-patriarcado',
        title: "Obra Católica Portuguesa de Migrações (OCPM / Patriarcado de Lisboa)",
        category: "Comunidade & Apoio",
        type: "Apoio Pastoral & Social",
        description: "Acompanhamento social, acolhimento pastoral e apoio a comunidades migrantes de todas as nacionalidades.",
        lat: 38.775,
        lng: -9.115,
        distance: "...",
        address: "Mosteiro de São Vicente de Fora, 1100-472 Lisboa",
        city: "Lisboa",
        email: "info@patriarcado-lisboa.pt",
        website: "https://patriarcado-lisboa.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-casa-vera-cruz',
        title: "Centro Social Paroquial de Vera Cruz (Aveiro)",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Comunitário",
        description: "Apoio de proximidade, cantina social, creche e apoio a famílias migrantes em Aveiro.",
        lat: 40.643,
        lng: -8.655,
        distance: "...",
        address: "Rua do Gravato, 3800-192 Aveiro",
        city: "Aveiro",
        email: "casaveracruz@casaveracruz.pt",
        website: "https://casaveracruz.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-terceira',
        title: "Cáritas da Ilha Terceira (Açores)",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Alimentar",
        description: "Apoio social, ajuda alimentar de emergência e inserção comunitária no arquipélago dos Açores.",
        lat: 38.654,
        lng: -27.221,
        distance: "...",
        address: "Angra do Heroísmo, Ilha Terceira, Açores",
        city: "Angra do Heroísmo",
        email: "geral@caritasterceira.org",
        website: "https://caritasterceira.org",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-algarve',
        title: "Cáritas Diocesana do Algarve (Faro)",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Alimentar",
        description: "Atendimento social e distribuição alimentar para famílias migrantes em Faro e em todo o Algarve.",
        lat: 37.016,
        lng: -7.935,
        distance: "...",
        address: "Rua D. Jerónimo Osório, 15, 8000-313 Faro",
        city: "Faro",
        email: "geral@caritasalgarve.pt",
        website: "https://caritasalgarve.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-aveiro',
        title: "Cáritas Diocesana de Aveiro",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio social, distribuição de vestuário e apoio a migrantes no distrito de Aveiro.",
        lat: 40.641,
        lng: -8.651,
        distance: "...",
        address: "Rua do Carmo, 3800-126 Aveiro",
        city: "Aveiro",
        email: "aveiro@caritas.pt",
        website: "https://caritasaveiro.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-braganca',
        title: "Cáritas Diocesana de Bragança-Miranda",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio a famílias carenciadas e integração de novos residentes no nordeste transmontano.",
        lat: 41.806,
        lng: -6.757,
        distance: "...",
        address: "Rua dos Combatentes da Grande Guerra, 5300-112 Bragança",
        city: "Bragança",
        email: "caritasbraganca.direcao@sapo.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-beja',
        title: "Cáritas Diocesana de Beja",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio de emergência a trabalhadores agrícolas e famílias migrantes no Baixo Alentejo.",
        lat: 38.015,
        lng: -7.865,
        distance: "...",
        address: "Rua Dr. Afonso Costa, 7800-058 Beja",
        city: "Beja",
        email: "caritas@caritasbeja.pt",
        website: "https://caritasbeja.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-braga',
        title: "Cáritas Arquidiocesana de Braga",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio social integrado, cantina social, vestuário e apoio a imigrantes no Minho.",
        lat: 41.551,
        lng: -8.428,
        distance: "...",
        address: "Rua dos Falcões, 4700-036 Braga",
        city: "Braga",
        email: "caritas@caritasbraga.pt",
        website: "https://caritasbraga.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-funchal',
        title: "Cáritas Diocesana do Funchal (Madeira)",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio social e acompanhamento familiar a imigrantes na Região Autónoma da Madeira.",
        lat: 32.65,
        lng: -16.908,
        distance: "...",
        address: "Rua do Bispo, 9000-073 Funchal, Madeira",
        city: "Funchal",
        email: "caritasfunchal@netmadeira.com",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-coimbra',
        title: "Cáritas Diocesana de Coimbra",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Rede de centros sociais, apoio a refugiados e orientação comunitária em Coimbra.",
        lat: 40.211,
        lng: -8.429,
        distance: "...",
        address: "Rua D. Manuel I, 3030-320 Coimbra",
        city: "Coimbra",
        email: "caritas@caritascoimbra.pt",
        website: "https://caritascoimbra.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-evora',
        title: "Cáritas Arquidiocesana de Évora",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio social e combate à exclusão de comunidades vulneráveis no Alentejo Central.",
        lat: 38.572,
        lng: -7.907,
        distance: "...",
        address: "Rua da República, 7000-656 Évora",
        city: "Évora",
        email: "geral@caritasevora.pt",
        website: "https://caritasevora.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-lamego',
        title: "Cáritas Diocesana de Lamego",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio social de emergência e ajuda a famílias na diocese de Lamego.",
        lat: 41.097,
        lng: -7.81,
        distance: "...",
        address: "Lamego, 5100 Lamego",
        city: "Lamego",
        email: "caritas@diocese-lamego.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-guarda',
        title: "Cáritas Diocesana da Guarda",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Acolhimento humanitário e apoio de primeira necessidade na Beira Interior.",
        lat: 40.537,
        lng: -7.268,
        distance: "...",
        address: "Largo da Sé, 6300-725 Guarda",
        city: "Guarda",
        email: "direcao@caritasguarda.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-leiria',
        title: "Cáritas Diocesana de Leiria-Fátima",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio a refugiados, famílias migrantes e cantina social na Região de Leiria.",
        lat: 39.744,
        lng: -8.808,
        distance: "...",
        address: "Rua Francisco Pereira da Silva, 2415-381 Leiria",
        city: "Leiria",
        email: "leiria@caritas.pt",
        website: "https://caritasleiria.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-portalegre',
        title: "Cáritas Diocesana de Portalegre-Castelo Branco",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio social e inclusão de migrantes no Alto Alentejo e Beira Baixa.",
        lat: 39.293,
        lng: -7.432,
        distance: "...",
        address: "Portalegre, 7300 Portalegre",
        city: "Portalegre",
        email: "caritas.ptg@gmail.com",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-lisboa',
        title: "Cáritas Diocesana de Lisboa",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Centro de atendimento social, apoio alimentar e acolhimento a migrantes na Área Metropolitana de Lisboa.",
        lat: 38.749,
        lng: -9.143,
        distance: "...",
        address: "Estrada do Forte da Ameixoeira, 1750-112 Lisboa",
        city: "Lisboa",
        email: "geral@caritaslisboa.pt",
        website: "https://caritaslisboa.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-porto',
        title: "Cáritas Diocesana do Porto",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Atendimento social integrado, apoio a sem-abrigo e acolhimento a migrantes no Grande Porto.",
        lat: 41.159,
        lng: -8.609,
        distance: "...",
        address: "Rua de Santa Catarina, 4000-447 Porto",
        city: "Porto",
        email: "caritasporto.geral@caritas.pt",
        website: "https://caritasporto.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-setubal',
        title: "Cáritas Diocesana de Setúbal (São Francisco Xavier)",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio social, acompanhamento comunitário e integração na Península de Setúbal.",
        lat: 38.528,
        lng: -8.891,
        distance: "...",
        address: "Largo de São Francisco Xavier, 2900-616 Setúbal",
        city: "Setúbal",
        email: "geral@sfxavier.caritas-setubal.com",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-santarem',
        title: "Cáritas Diocesana de Santarém",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio social a famílias e apoio a migrantes agrícolas no Ribatejo.",
        lat: 39.236,
        lng: -8.686,
        distance: "...",
        address: "Rua Serpa Pinto, 2000-046 Santarém",
        city: "Santarém",
        email: "caritasdiocesanasantarem@caritas.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-viana',
        title: "Cáritas Diocesana de Viana do Castelo",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio comunitário, emergência social e vestuário no Alto Minho.",
        lat: 41.694,
        lng: -8.83,
        distance: "...",
        address: "Viana do Castelo, 4900 Viana do Castelo",
        city: "Viana do Castelo",
        email: "caritasvianacastelo@sapo.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-viseu',
        title: "Cáritas Diocesana de Viseu",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Atendimento social e distribuição de bens essenciais a migrantes e famílias no Dão-Lafões.",
        lat: 40.658,
        lng: -7.912,
        distance: "...",
        address: "Rua Almirante Afonso Cerqueira, 3510-044 Viseu",
        city: "Viseu",
        email: "geral@caritasviseu.pt",
        website: "https://caritasviseu.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'caritas-vila-real',
        title: "Cáritas Diocesana de Vila Real",
        category: "Comunidade & Apoio",
        type: "Apoio Social & Acolhimento",
        description: "Apoio social e programas de inclusão comunitária em Trás-os-Montes.",
        lat: 41.301,
        lng: -7.744,
        distance: "...",
        address: "Vila Real, 5000 Vila Real",
        city: "Vila Real",
        email: "caritas.vilareal@caritas.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'fed-fappc-cerebral',
        title: "FAPPC – Federação das Associações Portuguesas de Paralisia Cerebral",
        category: "Comunidade & Apoio",
        type: "Saúde & Apoio Especializado",
        description: "Representação nacional, defesa de direitos e apoio a cidadãos com paralisia cerebral e suas famílias.",
        lat: 38.752,
        lng: -9.149,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "direccao@fappc.pt",
        website: "https://fappc.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'fed-fedra-raras',
        title: "FEDRA – Federação das Doenças Raras de Portugal",
        category: "Comunidade & Apoio",
        type: "Saúde & Apoio Especializado",
        description: "Apoio a doentes e famílias com patologias raras, encaminhamento médico e suporte social.",
        lat: 38.741,
        lng: -9.148,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "fedra@fedra.pt",
        website: "https://fedra.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'fed-fenacerci-solidariedade',
        title: "FENACERCI – Federação Nacional de Cooperativas de Solidariedade Social",
        category: "Comunidade & Apoio",
        type: "Inclusão & Solidariedade Social",
        description: "Rede nacional de apoio a pessoas com deficiência intelectual e multideficiência.",
        lat: 38.746,
        lng: -9.141,
        distance: "...",
        address: "Rua Conde de Almoster, 90, 1500-197 Lisboa",
        city: "Lisboa",
        email: "fenacerci@fenacerci.pt",
        website: "https://fenacerci.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'fed-formem-emprego',
        title: "FORMEM – Federação Portuguesa de Emprego Protegido",
        category: "Comunidade & Apoio",
        type: "Formação & Emprego Inclusivo",
        description: "Qualificação profissional e integração no mercado de trabalho de pessoas com deficiência.",
        lat: 38.75,
        lng: -9.145,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "geral@formem.org.pt",
        website: "https://formem.org.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'fed-fpas-surdos',
        title: "FPAS – Federação Portuguesa das Associações de Surdos",
        category: "Comunidade & Apoio",
        type: "Comunidade Surda & LGP",
        description: "Defesa dos direitos das pessoas surdas, promoção da Língua Gestual Portuguesa (LGP) e acessibilidade.",
        lat: 38.738,
        lng: -9.142,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "fpas@fpasurdos.pt",
        website: "https://fpasurdos.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'fed-fpda-autismo',
        title: "FPDA – Federação Portuguesa de Autismo",
        category: "Comunidade & Apoio",
        type: "Saúde & Apoio Especializado",
        description: "Apoio especializado a pessoas no espetro do autismo, orientação familiar e defesa de direitos.",
        lat: 38.742,
        lng: -9.151,
        distance: "...",
        address: "Rua de São Tomé, 1100-563 Lisboa",
        city: "Lisboa",
        email: "fpda@fpda.pt",
        website: "https://fpda.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'fed-fpdd-desporto',
        title: "FPDD – Federação Portuguesa de Desporto para Pessoas com Deficiência",
        category: "Comunidade & Apoio",
        type: "Desporto Adaptado & Inclusão",
        description: "Desenvolvimento e prática de desporto adaptado para pessoas com deficiência motora, visual e intelectual.",
        lat: 38.761,
        lng: -9.152,
        distance: "...",
        address: "Complexo Desportivo do Jamor, 1495 Cruz Quebrada",
        city: "Lisboa",
        email: "secretaria@fpdd.org",
        website: "https://fpdd.org",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-spem-esclerose',
        title: "SPEM – Sociedade Portuguesa de Esclerose Múltipla (Lisboa)",
        category: "Comunidade & Apoio",
        type: "Saúde & Apoio Especializado",
        description: "Apoio médico, fisioterapia, apoio psicológico e jurídico para portadores de Esclerose Múltipla.",
        lat: 38.771,
        lng: -9.162,
        distance: "...",
        address: "Rua Silva e Albuquerque, 1700-360 Lisboa",
        city: "Lisboa",
        email: "lisboa-geral@spem.pt",
        website: "https://spem.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'claim-porto-itinerante',
        title: "CLAIM Porto Itinerante – Apoio Integrado a Migrantes",
        category: "Residência & Vistos",
        type: "Apoio Local ao Imigrante",
        description: "Atendimento itinerante e acompanhamento comunitário a migrantes no concelho do Porto.",
        lat: 41.1579,
        lng: -8.6291,
        distance: "...",
        address: "Porto, Portugal",
        city: "Porto",
        email: "claimportoitinerante@gmail.com",
        website: "https://aima.gov.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-sy-mezze',
        title: "Restaurante e Espaço Cultural Mezze (Pão a Pão)",
        category: "Comunidade & Apoio",
        type: "Emprego & Integração de Refugiados",
        description: "Projeto de empregabilidade e inclusão social e cultural de refugiados do Médio Oriente em Arroios.",
        lat: 38.732,
        lng: -9.134,
        distance: "...",
        address: "Mercado de Arroios, Rua Ângela Pinto, 40/23, 1900-069 Lisboa",
        city: "Lisboa",
        email: "geral@mezze.pt",
        website: "https://mezze.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'cnod-sede-lisboa',
        title: "CNOD – Confederação Nacional dos Organismos de Deficientes (Sede Lisboa)",
        category: "Comunidade & Apoio",
        type: "Defesa de Direitos PCD",
        description: "Confederação nacional representativa de pessoas com deficiência, reivindicação de direitos e acessibilidade.",
        lat: 38.735,
        lng: -9.145,
        distance: "...",
        address: "Rua do Telhal, 1150-346 Lisboa",
        city: "Lisboa",
        email: "cnod.sede@gmail.com",
        website: "https://cnod.org.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'cnod-porto',
        title: "CNOD – Confederação dos Organismos de Deficientes (Porto)",
        category: "Comunidade & Apoio",
        type: "Defesa de Direitos PCD",
        description: "Delegação regional do Porto da CNOD para apoio a munícipes com deficiência e mobilidade reduzida.",
        lat: 41.15,
        lng: -8.61,
        distance: "...",
        address: "Porto, Portugal",
        city: "Porto",
        email: "cnodporto@gmail.com",
        website: "https://cnod.org.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'cnod-coimbra',
        title: "CNOD – Confederação dos Organismos de Deficientes (Coimbra)",
        category: "Comunidade & Apoio",
        type: "Defesa de Direitos PCD",
        description: "Delegação da Região Centro da CNOD para promoção da inclusão social e laboral de pessoas com deficiência.",
        lat: 40.21,
        lng: -8.42,
        distance: "...",
        address: "Coimbra, Portugal",
        city: "Coimbra",
        email: "cnod.coimbra@gmail.com",
        website: "https://cnod.org.pt",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-ru-apir',
        title: "APIR – Associação Portuguesa de Imigrantes Russófonos",
        category: "Comunidade & Apoio",
        type: "Comunidade Russófona & Europa do Leste",
        description: "Apoio social, orientação jurídica, tradução e integração cívica para cidadãos e famílias russófonas em Portugal.",
        lat: 38.742,
        lng: -9.145,
        distance: "...",
        address: "Lisboa, Portugal",
        city: "Lisboa",
        email: "apirportugal@gmail.com",
        website: "https://www.facebook.com/apirportugal/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-ro-doina-algarve',
        title: "Associação Cultural Doina (Algarve)",
        category: "Comunidade & Apoio",
        type: "Comunidade Romena e Moldava",
        description: "Dinamização cultural, apoio social e aconselhamento comunitário para cidadãos romenos e moldavos no Algarve.",
        lat: 37.0194,
        lng: -7.9304,
        distance: "...",
        address: "Faro, Algarve, Portugal",
        city: "Faro",
        email: "doina.algarve@gmail.com",
        website: "https://www.facebook.com/associacaodoina/",
        ratings: [],
        avgRating: 5.0
    },
    {
        id: 'assoc-sy-pao-a-pao',
        title: "Pão a Pão – Associação de Apoio à Integração de Refugiados do Médio Oriente",
        category: "Comunidade & Apoio",
        type: "Apoio a Refugiados & Inclusão Laboral",
        description: "Inclusão socioprofissional de refugiados e migrantes do Médio Oriente através de projetos comunitários e restauração.",
        lat: 38.7325,
        lng: -9.1345,
        distance: "...",
        address: "Rua Ângela Pinto, 40, Arroios, 1900-069 Lisboa",
        city: "Lisboa",
        email: "associacao@paoapao.pt",
        website: "https://paoapao.pt",
        ratings: [],
        avgRating: 5.0
    }
];
