import { MapAlert, JobPost, UNIFIED_CATEGORIES } from '../types';
import { MASSIVE_SERVICES_DATABASE } from './massiveServicesDatabase';
import { NATIONALITY_ASSOCIATIONS_DATABASE } from './nationalityAssociationsDatabase';
import { JOB_SOURCES_DATABASE } from './jobSourcesDatabase';
import { HOUSING_SOURCES_DATABASE } from './housingSourcesDatabase';

export { JOB_SOURCES_DATABASE, HOUSING_SOURCES_DATABASE, NATIONALITY_ASSOCIATIONS_DATABASE };

export const PROTECTED_SERVICES: MapAlert[] = [
    ...MASSIVE_SERVICES_DATABASE,
    ...NATIONALITY_ASSOCIATIONS_DATABASE,

    // ============================================================
    // 🏛️ CNAIM – CENTROS NACIONAIS DE APOIO À INTEGRAÇÃO DE MIGRANTES (AIMA)
    // ============================================================
    {
        id: 'p-cnaim-lisboa',
        title: "CNAIM Lisboa – Centro Nacional de Apoio à Integração de Migrantes",
        category: "Residência & Vistos",
        lat: 38.7250,
        lng: -9.1350,
        distance: '...',
        address: "Rua Álvaro Coutinho, 14, 1150-025 Lisboa",
        city: "Lisboa",
        website: "https://aima.gov.pt",
        phone: "(+351) 21 810 61 00",
        email: "cnaim.lisboa@acm.gov.pt",
        schedule: "Segunda a Sexta-feira, 08h00–17h00",
        avgRating: 5.0,
        ratings: [],
        description: "Principal Centro Nacional de Apoio de Lisboa com balcões integrados da AIMA, Segurança Social, Autoridade para as Condições do Trabalho (ACT), IEFP e apoio jurídico gratuito."
    },
    {
        id: 'p-cnaim-norte',
        title: "CNAIM Norte – Centro Nacional de Apoio à Integração de Migrantes (Porto)",
        category: "Residência & Vistos",
        lat: 41.1600,
        lng: -8.6280,
        distance: '...',
        address: "Avenida de França, 316, Edifício Capitólio, 4050-276 Porto",
        city: "Porto",
        website: "https://aima.gov.pt",
        phone: "(+351) 22 207 38 10",
        email: "cnaim.norte@acm.gov.pt",
        schedule: "Segunda a Sexta-feira, 08h00–17h00",
        avgRating: 5.0,
        ratings: [],
        description: "Centro integrado de acolhimento e suporte ao migrante na Região Norte: apoio na regularização de permanência, saúde, educação, habitação e inserção socioprofissional."
    },
    {
        id: 'p-cnaim-algarve',
        title: "CNAIM Algarve – Centro Nacional de Apoio à Integração de Migrantes (Faro)",
        category: "Residência & Vistos",
        lat: 37.0194,
        lng: -7.9322,
        distance: '...',
        address: "Loja do Cidadão, Mercado Municipal, 1.º Piso, Largo Dr. Francisco Sá Carneiro, 8000-151 Faro",
        city: "Faro",
        website: "https://aima.gov.pt",
        phone: "(+351) 289 895 450",
        email: "cnaim.algarve@acm.gov.pt",
        schedule: "Segunda a Sexta-feira, 08h30–17h00",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento multidisciplinar no Algarve para apoio a famílias migrantes, mediação intercultural, pedidos de autorização de residência e direitos laborais."
    },
    {
        id: 'p-cnaim-alentejo',
        title: "CNAIM Alentejo – Centro Nacional de Apoio à Integração de Migrantes (Beja)",
        category: "Residência & Vistos",
        lat: 38.0154,
        lng: -7.8629,
        distance: '...',
        address: "Edifício Administrativo do Parque de Feiras e Exposições, Av. Salgueiro Maia, s/n, 7800-552 Beja",
        city: "Beja",
        website: "https://aima.gov.pt",
        phone: "(+351) 967 071 313",
        email: "cnaim.beja@acm.gov.pt",
        schedule: "Segunda a Sexta-feira, 09h00–12h30 e 14h00–17h30",
        avgRating: 5.0,
        ratings: [],
        description: "Polo de apoio aos cidadãos migrantes no Alentejo: orientação sobre legalização, contratos de trabalho agrícola e acesso aos serviços públicos de saúde e educação."
    },

    // ============================================================
    // 🌐 PORTAIS & INFRAESTRUTURAS CENTRAIS DE ESTADO
    // ============================================================
    {
        id: 'p-serv-irn-nacional',
        title: "IRN – Instituto dos Registos e do Notariado (Portal Oficial)",
        category: "Residência & Vistos",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua de São Bento, 148, 1200-821 Lisboa",
        city: "Lisboa",
        website: "https://irn.justica.gov.pt/",
        avgRating: 5.0,
        ratings: [],
        description: "Portal oficial do IRN: pedidos online de certidões de nascimento, casamento, agendamento de Cartão de Cidadão, passaporte e processos de nacionalidade portuguesa."
    },
    {
        id: 'p-serv-financas-nacional',
        title: "Portal das Finanças (Autoridade Tributária)",
        category: "Finanças & Impostos",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Rua do Comércio, 49, 1100-150 Lisboa",
        city: "Lisboa",
        website: "https://www.portaldasfinancas.gov.pt/",
        avgRating: 5.0,
        ratings: [],
        description: "Portal oficial dos serviços fiscais: atribuição de NIF, início de atividade independente (recibos verdes), validação de faturas no e-Fatura e declarações de IRS."
    },
    {
        id: 'p-serv-irn-siga',
        title: "IRN – Agendamentos Online (Portal SIGA)",
        category: "Residência & Vistos",
        lat: 38.7680,
        lng: -9.0980,
        distance: 'N/A',
        address: "Campus de Justiça, Edifício H, Av. D. João II, 1990-097 Lisboa",
        city: "Lisboa",
        website: "https://siga.marcacaoprevia.pt/",
        avgRating: 5.0,
        ratings: [],
        description: "Plataforma oficial do Estado Português para marcação de atendimento presencial no IRN, Segurança Social, Finanças e Lojas do Cidadão."
    },

    // ============================================================
    // 🤝 REDE NACIONAL DE SOLIDARIEDADE & APOIO SOCIAL
    // ============================================================
    {
        id: '917e2978-831e-4537-8e6f-fb9f8e438e3e',
        title: "Cruz Vermelha Portuguesa – Delegação de Braga",
        category: "Direitos & Apoio Social",
        lat: 41.5480,
        lng: -8.4120,
        distance: 'N/A',
        address: "Rua Bernardo Sequeira, 247, 4715-017 Braga",
        city: "Braga",
        website: "https://www.cruzvermelha.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Delegação de Braga da Cruz Vermelha: apoio alimentar de emergência, acolhimento de refugiados, formação de primeiros socorros e apoio social a famílias."
    },
    {
        id: 'p-serv-aaeif',
        title: "AAEIF – Associação de Apoio a Emigrantes, Imigrantes e Famílias",
        category: "Direitos & Apoio Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Atendimento Online",
        city: "Online",
        website: "https://www.aaeif.pt/",
        avgRating: 5.0,
        ratings: [],
        description: "Orientação civica e social para emigrante e imigrantes em Portugal, e informações sobre legalização."
    },
    {
        id: 'p-serv-portuando',
        title: "Portuando Brasil",
        category: "Direitos & Apoio Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida da Liberdade, 245, 1250-143 Lisboa",
        city: "Lisboa",
        website: "https://portuando-brasil.blogspot.com/",
        avgRating: 5.0,
        ratings: [],
        description: "Comunidade e portal informativo para imigrantes brasileiros em Portugal: guias práticos sobre obtenção de NIF, NISS, matrícula escolar e arrendamento habitacional."
    },
    {
        id: '25b306ac-7422-4a0b-93df-5ae666993130',
        title: "SEIVA – Associação ao Serviço da Vida",
        category: "Direitos & Apoio Social",
        lat: 41.1520,
        lng: -8.6250,
        distance: 'N/A',
        address: "Rua de Vilar, 130, 4050-625 Porto",
        city: "Porto",
        website: "https://seiva.co.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Intervenção social e comunitária no Porto: acompanhamento psicossocial, acolhimento de famílias em risco de exclusão social e programas educativos."
    },
    {
        id: 'p-serv-3',
        title: "ASI – Associação Solidariedade Internacional",
        category: "Direitos & Apoio Social",
        lat: 41.1250,
        lng: -8.6150,
        distance: 'N/A',
        address: "Rua das Pedras, 307 e Rua Diogo Cão, 257, 4400-249 Vila Nova de Gaia",
        city: "Vila Nova de Gaia",
        website: "https://www.asigv.org",
        avgRating: 5.0,
        ratings: [],
        description: "Acolhimento humanitário e solidariedade social em Gaia: mediação intercultural, distribuição alimentar e capacitação profissional para migrantes."
    },
    {
        id: 'p-serv-4',
        title: "UNIVERA – Centro Social e Paroquial da Vera Cruz",
        category: "Direitos & Apoio Social",
        lat: 40.6410,
        lng: -8.6510,
        distance: 'N/A',
        address: "Rua Campeão das Províncias, 1.º andar, 3800-124 Aveiro",
        city: "Aveiro",
        website: "https://www.cspveracruz.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Instituição de solidariedade social em Aveiro: cantina social, apoio alimentar, creche, centro de dia e gabinete de apoio à integração de migrantes."
    },
    {
        id: 'p-serv-5',
        title: "Casa Lusófona ONGD",
        category: "Direitos & Apoio Social",
        lat: 40.2100,
        lng: -8.4190,
        distance: 'N/A',
        address: "Avenida Sá da Bandeira, 115, 4.º piso, Loja 37/38, 3004-515 Coimbra",
        city: "Coimbra",
        website: "https://www.facebook.com/casalusofona/",
        avgRating: 5.0,
        ratings: [],
        description: "Apoio a estudantes e cidadãos da CPLP em Coimbra: cooperação para o desenvolvimento, orientação académica, apoio habitacional e dinamização cultural."
    },
    {
        id: 'p-serv-6',
        title: "InPulsar – Associação para o Desenvolvimento Comunitário",
        category: "Direitos & Apoio Social",
        lat: 39.7450,
        lng: -8.8050,
        distance: 'N/A',
        address: "Rua Dr. José Gonçalves, 55, Loja 3, Piso -1, 2410-121 Leiria",
        city: "Leiria",
        website: "http://www.inpulsar.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Associação de desenvolvimento comunitário em Leiria: apoio a populações vulneráveis, projetos de inclusão social de migrantes e aconselhamento cívico."
    },
    {
        id: 'p-serv-7',
        title: "Centro Social e Paroquial Costa da Caparica",
        category: "Direitos & Apoio Social",
        lat: 38.6430,
        lng: -9.2320,
        distance: 'N/A',
        address: "Avenida 1.º de Maio, 4, R/C, 2825-395 Costa da Caparica",
        city: "Almada",
        website: "https://www.cspcostacap.org",
        avgRating: 5.0,
        ratings: [],
        description: "Apoio social na Costa da Caparica: banco de alimentos, atendimento e acompanhamento social de famílias, centro de dia e atividades para crianças."
    },
    {
        id: 'p-serv-8',
        title: "Centro Cultural Moldavo",
        category: "Direitos & Apoio Social",
        lat: 38.7210,
        lng: -9.3620,
        distance: 'N/A',
        address: "Rua José Malhoa, 11, Trajouce, 2785-657 São Domingos de Rana",
        city: "Cascais",
        website: "https://ccmoldavo.pt/",
        avgRating: 5.0,
        ratings: [],
        description: "Associação de apoio e acolhimento à comunidade moldava, romena e eslava em Portugal: apoio na tradução de documentos, apoio jurídico e preservação cultural."
    },
    {
        id: 'p-serv-9',
        title: "BYP – Batoto Yetu Portugal",
        category: "Direitos & Apoio Social",
        lat: 38.7040,
        lng: -9.2780,
        distance: 'N/A',
        address: "Avenida João de Freitas Branco, 12, 2760-073 Caxias",
        city: "Oeiras",
        website: "https://batotoyetu.org",
        avgRating: 5.0,
        ratings: [],
        description: "Educação cultural e inclusão juvenil através da dança e música de matriz africana, valorização do património imaterial e mediação comunitária."
    },
    {
        id: 'p-serv-10',
        title: "AGUINENSO – Associação Guineense de Solidariedade Social",
        category: "Direitos & Apoio Social",
        lat: 38.7490,
        lng: -9.1010,
        distance: 'N/A',
        address: "Avenida João Paulo II, Lote 528, 2.º A, Bairro do Condado, 1950-430 Lisboa",
        city: "Lisboa",
        website: "https://aguinenso.org/",
        avgRating: 5.0,
        ratings: [],
        description: "Solidariedade social e acolhimento da comunidade guineense: apoio em processos da AIMA, auxílio a doentes evacuados e orientação para emprego e formação."
    },
    {
        id: 'p-serv-11',
        title: "Município de Odivelas – CLAIM (Apoio ao Imigrante)",
        category: "Residência & Vistos",
        lat: 38.7930,
        lng: -9.1750,
        distance: 'N/A',
        address: "Rua Alfredo Roque Gameiro, 18B, 2675-277 Odivelas",
        city: "Odivelas",
        website: "https://www.cm-odivelas.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Centro Local de Apoio à Integração de Migrantes de Odivelas: atendimento descentralizado para regularização, inscrição escolar, SNS e apoio social."
    },
    {
        id: 'p-serv-12',
        title: "Associação ProAbraçar",
        category: "Direitos & Apoio Social",
        lat: 39.2080,
        lng: -8.6250,
        distance: 'N/A',
        address: "Praceta do Chapim, 26, R/C, 2080-048 Almeirim",
        city: "Almeirim",
        website: "https://www.facebook.com/ProAbracar/",
        avgRating: 5.0,
        ratings: [],
        description: "Apoio social no Ribatejo: distribuição de alimentos, roupas e mobiliário para famílias em vulnerabilidade socioeconómica e imigrantes locais."
    },
    {
        id: 'p-serv-13',
        title: "Fábrica da Igreja de Nossa Senhora da Conceição",
        category: "Direitos & Apoio Social",
        lat: 38.5280,
        lng: -8.8870,
        distance: 'N/A',
        address: "Avenida Bento de Jesus Caraça, 77, 2910-430 Setúbal",
        city: "Setúbal",
        website: "https://www.patriarcado-lisboa.pt/",
        avgRating: 5.0,
        ratings: [],
        description: "Ação social e comunitária em Setúbal: cantina social, apoio a agregados familiares carenciados e distribuição de bens essenciais."
    },
    {
        id: 'p-serv-14',
        title: "Câmara Municipal de Beja – Divisão de Desenvolvimento Social (CLAIM)",
        category: "Residência & Vistos",
        lat: 38.0160,
        lng: -7.8640,
        distance: 'N/A',
        address: "Rua de Angola, 5, 7800-468 Beja",
        city: "Beja",
        website: "https://www.cm-beja.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Gabinete de apoio ao imigrante em Beja: auxílio no reagrupamento familiar, acesso a cuidados de saúde e mediação junto dos serviços públicos locais."
    },
    {
        id: 'p-serv-15',
        title: "Associação Caboverdiana de Sines e Santiago do Cacém",
        category: "Direitos & Apoio Social",
        lat: 37.9550,
        lng: -8.8680,
        distance: 'N/A',
        address: "Rua João Doroteia, Lote LE1, 7520-109 Sines",
        city: "Sines",
        website: "https://www.facebook.com/associacaocaboverdianasines/",
        avgRating: 5.0,
        ratings: [],
        description: "Polo comunitário no Litoral Alentejano: apoio social e jurídico a trabalhadores migrantes dos setores industrial e portuário de Sines."
    },
    {
        id: 'p-serv-16',
        title: "DOINA – Associação de Imigrantes Romenos e Moldavos do Algarve",
        category: "Direitos & Apoio Social",
        lat: 37.0860,
        lng: -8.0310,
        distance: 'N/A',
        address: "Avenida 5 de Outubro, 76, 8135-100 Almancil",
        city: "Loulé",
        website: "https://www.facebook.com/doina.algarve/",
        avgRating: 5.0,
        ratings: [],
        description: "Apoio a migrantes da Europa de Leste no Algarve: traduções juramentadas, regularização documental, cursos de português e assistência social."
    },
    {
        id: 'p-serv-17',
        title: "GRATO – Grupo de Apoio a Toxicodependentes",
        category: "Direitos & Apoio Social",
        lat: 37.1350,
        lng: -8.5380,
        distance: 'N/A',
        address: "Avenida Guanaré (Pavilhão Municipal), 8500-507 Portimão",
        city: "Portimão",
        website: "http://www.grato.pt/",
        avgRating: 5.0,
        ratings: [],
        description: "Apoio psicossocial, redução de danos e reinserção comunitária para pessoas em situação de vulnerabilidade e dependência no Algarve."
    },
    {
        id: 'p-serv-apirp',
        title: "APIRP – Apoio a Imigrantes e Refugiados",
        category: "Direitos & Apoio Social",
        lat: 38.7935,
        lng: -9.1024,
        distance: 'N/A',
        address: "Avenida de São José, 6, 3.º Esquerdo, 2685-108 Sacavém",
        city: "Loures",
        website: "https://www.apirp.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Orientação e acompanhamento em processos de autorização de residência, reagrupamento familiar e apoio no agendamento de serviços públicos."
    },
    {
        id: 'p-serv-open-gate',
        title: "Open Gate Portugal",
        category: "Direitos & Apoio Social",
        lat: 38.7295,
        lng: -9.1012,
        distance: 'N/A',
        address: "Rua 2 da Matinha, 5D, 1950-326 Lisboa",
        city: "Lisboa",
        website: "https://opengateportugal.com",
        avgRating: 5.0,
        ratings: [],
        description: "Capacitação e inserção socioprofissional de refugiados e requerentes de asilo através de programas de mentoria e preparação para o mercado de trabalho."
    },
    {
        id: 'p-serv-renovar-mouraria',
        title: "Renovar a Mouraria",
        category: "Direitos & Apoio Social",
        lat: 38.7174,
        lng: -9.1342,
        distance: 'N/A',
        address: "Beco do Rosendo, 8 e 10, 1100-460 Lisboa",
        city: "Lisboa",
        website: "https://renovaramouraria.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Associação local no coração de Lisboa: aulas gratuitas de Português para Estrangeiros (PLA), gabinete de apoio ao migrante e dinamização comunitária."
    },
    {
        id: 'p-serv-escolhas',
        title: "Programa Escolhas (IPDJ)",
        category: "Direitos & Apoio Social",
        lat: 38.7382,
        lng: -9.1594,
        distance: 'N/A',
        address: "Avenida Columbano Bordalo Pinheiro, 86, 1070-065 Lisboa",
        city: "Lisboa",
        website: "https://escolhas.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Programa governamental nacional de inclusão social de crianças e jovens de contextos socioeconómicos vulneráveis e comunidades de migrantes."
    },
    {
        id: 'p-serv-mundo-feliz',
        title: "Mundo Feliz – Associação de Imigrantes",
        category: "Direitos & Apoio Social",
        lat: 38.7064,
        lng: -9.2312,
        distance: 'N/A',
        address: "Rua Dr. Manuel de Arriaga, 20A, 1495-019 Algés",
        city: "Oeiras",
        website: "https://www.mundofeliz.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Apoio a famílias imigrantes em Oeiras e Lisboa: orientação para obtenção de NIF/NISS, equivalência de habilitações escolares e apoio comunitário."
    },
    {
        id: 'p-serv-pao-pao',
        title: "Pão a Pão – Integração Alimentar",
        category: "Direitos & Apoio Social",
        lat: 38.7350,
        lng: -9.1330,
        distance: 'N/A',
        address: "Mercado de Arroios, Rua de Arroios, 1170-023 Lisboa",
        city: "Lisboa",
        website: "https://paoapao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Inclusão social e laboral de refugiados do Médio Oriente através de formação culinária, partilha gastronómica e restauração solidária (Restaurante Mezze)."
    },
    {
        id: 'p-serv-pdh',
        title: "Plataforma de Direitos Humanos Portugal",
        category: "Direitos & Apoio Social",
        lat: 38.7223,
        lng: -9.1393,
        distance: 'N/A',
        address: "Avenida da Liberdade, 1100-001 Lisboa",
        city: "Lisboa",
        website: "https://plataformadh.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Rede confederada de defesa dos direitos cívicos, combate à xenofobia, monitorização de políticas de imigração e defesa da dignidade humana."
    },
    {
        id: 'p-serv-cvp-migrantes',
        title: "Cruz Vermelha Portuguesa – Gabinete de Apoio a Migrantes",
        category: "Direitos & Apoio Social",
        lat: 38.7058,
        lng: -9.1624,
        distance: 'N/A',
        address: "Jardim 9 de Abril, 1 a 5, 1249-083 Lisboa",
        city: "Lisboa",
        website: "https://www.cruzvermelha.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Acolhimento humanitário especializado: apoio a requerentes de asilo, proteção de menores não acompanhados, reunificação familiar e apoio médico de emergência."
    },
    {
        id: 'p-serv-sos-racismo',
        title: "SOS Racismo Portugal",
        category: "Direitos & Apoio Social",
        lat: 38.7061,
        lng: -9.1604,
        distance: 'N/A',
        address: "Rua das Janelas Verdes, 2, 1200-692 Lisboa",
        city: "Lisboa",
        website: "https://sosracismo.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Organização não governamental antirracista: gabinete de apoio jurídico gratuito a vítimas de discriminação racial, denúncia de abusos e ação cívica."
    },
    {
        id: 'p-serv-crescer',
        title: "CRESCER – Associação de Intervenção Comunitária",
        category: "Direitos & Apoio Social",
        lat: 38.7045,
        lng: -9.1768,
        distance: 'N/A',
        address: "Bairro Quinta da Cabrinha, Lote 3, Loja E/F, 1300-906 Lisboa",
        city: "Lisboa",
        website: "https://crescer.org",
        avgRating: 5.0,
        ratings: [],
        description: "Associação de intervenção social: capacitação para emprego através de projetos gastronómicos (É Um Restaurante), apoio habitacional e redução de riscos."
    },
    {
        id: 'p-serv-aemirep',
        title: "AEMIREP – Associação de Empreendedores Imigrantes",
        category: "Trabalho & Carreira",
        lat: 38.7754,
        lng: -9.1564,
        distance: 'N/A',
        address: "Rua Varela Silva, Lote 10, Loja B, 1750-403 Lisboa",
        city: "Lisboa",
        website: "https://aemirep.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Apoio a empreendedores e pequenas empresas de migrantes: consultoria para criação de negócios, acesso a financiamento, contabilidade e formação em gestão."
    },

    // ============================================================
    // 🏛️ CONSERVATÓRIAS DO REGISTO CIVIL (IRN)
    // ============================================================
    {
        id: 'p-serv-68',
        title: "Conservatória do Registo Civil de Lisboa (Douradores)",
        category: "Residência & Vistos",
        lat: 38.7125,
        lng: -9.1368,
        distance: 'N/A',
        address: "Rua dos Douradores, 109, 1100-204 Lisboa",
        city: "Lisboa",
        website: "https://irn.justica.gov.pt/Contactos-do-Registo/Registo-Civil-de-Lisboa",
        avgRating: 5.0,
        ratings: [],
        description: "Registo de atos de estado civil em Lisboa: declaração de nascimento, casamento, divórcio, óbito, emissão de certidões e instrução de processos de nacionalidade."
    },
    {
        id: 'p-serv-69',
        title: "Conservatória do Registo Civil de Almada",
        category: "Residência & Vistos",
        lat: 38.6790,
        lng: -9.1570,
        distance: 'N/A',
        address: "Avenida Alfredo da Silva, 2, 2800-008 Almada",
        city: "Almada",
        website: "https://irn.justica.gov.pt/Contactos-do-Registo/Registo-Civil-de-Almada",
        avgRating: 5.0,
        ratings: [],
        description: "Balcão do IRN em Almada: renovação e pedido de Cartão de Cidadão, certidões de nascimento, casamento civil e pedidos de aquisição de nacionalidade."
    },
    {
        id: 'p-serv-70',
        title: "Conservatória do Registo Civil de Sintra",
        category: "Residência & Vistos",
        lat: 38.8000,
        lng: -9.3800,
        distance: 'N/A',
        address: "Rua Dr. Alfredo da Costa, 42, 2710-523 Sintra",
        city: "Sintra",
        website: "https://irn.justica.gov.pt/Contactos-do-Registo/Registo-Civil-de-Sintra",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento do IRN no concelho de Sintra: emissão de documentos de identidade, pedidos de certidão de estado civil e instrução de processos de nacionalidade."
    },
    {
        id: 'p-serv-71',
        title: "Conservatória do Registo Civil de Cascais",
        category: "Residência & Vistos",
        lat: 38.6980,
        lng: -9.4210,
        distance: 'N/A',
        address: "Avenida Valbom, 25, 2750-508 Cascais",
        city: "Cascais",
        website: "https://irn.justica.gov.pt/Contactos-do-Registo/Registo-Civil-de-Cascais",
        avgRating: 5.0,
        ratings: [],
        description: "Serviços de registo civil em Cascais: emissão de Cartão de Cidadão, certidões permanentes de registo civil e celebração de casamentos."
    },
    {
        id: 'p-serv-72',
        title: "Conservatória do Registo Civil de Évora",
        category: "Residência & Vistos",
        lat: 38.5720,
        lng: -7.9080,
        distance: 'N/A',
        address: "Praça do Sertório, 7000-503 Évora",
        city: "Évora",
        website: "https://irn.justica.gov.pt/Contactos-do-Registo/Registo-Civil-de-Evora",
        avgRating: 5.0,
        ratings: [],
        description: "Conservatória central do distrito de Évora: atos de registo civil, processos de nacionalidade portuguesa e emissão de títulos de identidade."
    },
    {
        id: 'p-serv-73',
        title: "Conservatória do Registo Civil de Beja",
        category: "Residência & Vistos",
        lat: 38.0160,
        lng: -7.8650,
        distance: 'N/A',
        address: "Rua D. Pedro V, 14, 7800-476 Beja",
        city: "Beja",
        website: "https://irn.justica.gov.pt/Contactos-do-Registo/Registo-Civil-de-Beja",
        avgRating: 5.0,
        ratings: [],
        description: "Registo civil e notariado em Beja: certidões de nascimento, Cartão de Cidadão, registo predial e pedidos de nacionalidade no Baixo Alentejo."
    },
    {
        id: 'p-serv-74',
        title: "Conservatória do Registo Civil de Faro",
        category: "Residência & Vistos",
        lat: 37.0180,
        lng: -7.9310,
        distance: 'N/A',
        address: "Avenida da República, 286, 8000-079 Faro",
        city: "Faro",
        website: "https://irn.justica.gov.pt/Contactos-do-Registo/Registo-Civil-de-Faro",
        avgRating: 5.0,
        ratings: [],
        description: "Conservatória central do Algarve: tramitação de atos de registo civil, nacionalidade portuguesa, passaportes e certidões oficiais."
    },
    {
        id: 'p-serv-75',
        title: "Conservatória do Registo Civil de Portimão",
        category: "Residência & Vistos",
        lat: 37.1370,
        lng: -8.5370,
        distance: 'N/A',
        address: "Rua do Comércio, 12, 8500-539 Portimão",
        city: "Portimão",
        website: "https://irn.justica.gov.pt/Contactos-do-Registo/Registo-Civil-de-Portimao",
        avgRating: 5.0,
        ratings: [],
        description: "Serviço de registo civil em Portimão: emissão de documentos de identificação, certidões de nascimento e casamento no Barlavento Algarvio."
    },

    // ============================================================
    // 💶 SERVIÇOS DE FINANÇAS (AUTORIDADE TRIBUTÁRIA)
    // ============================================================
    {
        id: 'p-serv-76',
        title: "Serviço de Finanças de Braga",
        category: "Finanças & Impostos",
        lat: 41.5510,
        lng: -8.4230,
        distance: 'N/A',
        address: "Praça Conde de Agrolongo, 4700-223 Braga",
        city: "Braga",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento da Autoridade Tributária em Braga: emissão de NIF, senhas de acesso ao Portal das Finanças, liquidação de impostos e apoio fiscal."
    },
    {
        id: 'p-serv-77',
        title: "Serviço de Finanças do Porto (Central)",
        category: "Finanças & Impostos",
        lat: 41.1470,
        lng: -8.6140,
        distance: 'N/A',
        address: "Rua de Cândido dos Reis, 55, 4050-151 Porto",
        city: "Porto",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Serviço de Finanças central no Porto: obtenção de NIF, entrega de IRS, início e cessação de atividade profissional e esclarecimento de dívidas fiscais."
    },
    {
        id: 'p-serv-78',
        title: "Serviço de Finanças de Vila Nova de Gaia",
        category: "Finanças & Impostos",
        lat: 41.1310,
        lng: -8.6080,
        distance: 'N/A',
        address: "Rua Almeida Garrett, 17, 4400-208 Vila Nova de Gaia",
        city: "Vila Nova de Gaia",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento tributário em Gaia: emissão de certidões de não dívida, validação de faturas, registo de contratos de arrendamento e declaração de IRS."
    },
    {
        id: 'p-serv-79',
        title: "Serviço de Finanças de Viana do Castelo",
        category: "Finanças & Impostos",
        lat: 41.6930,
        lng: -8.8320,
        distance: 'N/A',
        address: "Praça D. Afonso III, 4900-351 Viana do Castelo",
        city: "Viana do Castelo",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Finanças em Viana do Castelo: atribuição de NIF para cidadãos estrangeiros, nomeação de representante fiscal e tributação do trabalho."
    },
    {
        id: 'p-serv-80',
        title: "Serviço de Finanças de Guimarães",
        category: "Finanças & Impostos",
        lat: 41.4420,
        lng: -8.2950,
        distance: 'N/A',
        address: "Rua de Santo António, 4810-208 Guimarães",
        city: "Guimarães",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento fiscal em Guimarães: emissão de NIF, início de atividade empresarial/independente e apoio presencial no Portal das Finanças."
    },
    {
        id: 'p-serv-81',
        title: "Serviço de Finanças de Coimbra",
        category: "Finanças & Impostos",
        lat: 40.2150,
        lng: -8.4310,
        distance: 'N/A',
        address: "Avenida Fernão de Magalhães, 3030-144 Coimbra",
        city: "Coimbra",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Finanças central em Coimbra: pedidos de NIF para estudantes internacionais e trabalhadores, IRS e validação de despesas dedutíveis."
    },
    {
        id: 'p-serv-82',
        title: "Serviço de Finanças de Leiria",
        category: "Finanças & Impostos",
        lat: 39.7460,
        lng: -8.8090,
        distance: 'N/A',
        address: "Rua da Junqueira, 2410-328 Leiria",
        city: "Leiria",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento tributário em Leiria: registo de contratos de trabalho e alojamento, senhas fiscais e liquidação de impostos."
    },
    {
        id: 'p-serv-83',
        title: "Serviço de Finanças de Aveiro",
        category: "Finanças & Impostos",
        lat: 40.6380,
        lng: -8.6490,
        distance: 'N/A',
        address: "Rua Dr. Mário Sacramento, 3810-192 Aveiro",
        city: "Aveiro",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Serviço de Finanças de Aveiro: atribuição de NIF presencial, certidões fiscais e esclarecimento de dúvidas sobre tributação de rendimentos."
    },
    {
        id: 'p-serv-84',
        title: "Serviço de Finanças de Viseu",
        category: "Finanças & Impostos",
        lat: 40.6590,
        lng: -7.9140,
        distance: 'N/A',
        address: "Rua Paio Galvão, 3520-300 Viseu",
        city: "Viseu",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Finanças de Viseu: apoio presencial agendado para emissão de NIF, início de atividade e cumprimento de obrigações tributárias."
    },
    {
        id: 'p-serv-85',
        title: "Serviço de Finanças de Lisboa (Praça de Espanha)",
        category: "Finanças & Impostos",
        lat: 38.7410,
        lng: -9.1610,
        distance: 'N/A',
        address: "Avenida das Forças Armadas, 1500-264 Lisboa",
        city: "Lisboa",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Serviço de Finanças em Lisboa: balcão de atendimento para emissão de NIF de cidadãos residentes e não residentes, declarações de IRS e e-Fatura."
    },
    {
        id: 'p-serv-132',
        title: "Serviço de Finanças de Setúbal",
        category: "Finanças & Impostos",
        lat: 38.5244,
        lng: -8.8931,
        distance: 'N/A',
        address: "Avenida Luísa Todi, 125, 2900-462 Setúbal",
        city: "Setúbal",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento da Autoridade Tributária em Setúbal: atribuição de NIF, declaração de rendimentos, recibos verdes e certidões fiscais."
    },
    {
        id: 'p-serv-133',
        title: "Serviço de Finanças de Viseu (Centro)",
        category: "Finanças & Impostos",
        lat: 40.6566,
        lng: -7.9125,
        distance: 'N/A',
        address: "Rua Serpa Pinto, 10, 3500-192 Viseu",
        city: "Viseu",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Balcão das Finanças no centro de Viseu: pedidos de NIF, início de atividade e suporte no preenchimento do IRS."
    },
    {
        id: 'p-serv-134',
        title: "Serviço de Finanças de Faro",
        category: "Finanças & Impostos",
        lat: 37.0179,
        lng: -7.9308,
        distance: 'N/A',
        address: "Praça da Liberdade, 8000-266 Faro",
        city: "Faro",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Finanças central em Faro: apoio fiscal para trabalhadores e empresas do Algarve, emissão de NIF e registo de contratos de arrendamento."
    },
    {
        id: 'p-serv-94',
        title: "Serviço de Finanças de Portimão",
        category: "Finanças & Impostos",
        lat: 37.1360,
        lng: -8.5360,
        distance: 'N/A',
        address: "Rua 16 de Junho, 8500-556 Portimão",
        city: "Portimão",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento tributário no Barlavento Algarvio: emissão de NIF, declaração periódica de IVA e esclarecimento sobre recibos de renda eletrónicos."
    },
    {
        id: 'p-serv-95',
        title: "Serviço de Finanças de Loulé",
        category: "Finanças & Impostos",
        lat: 37.1390,
        lng: -8.0220,
        distance: 'N/A',
        address: "Avenida José da Costa Mealha, 8100-410 Loulé",
        city: "Loulé",
        website: "https://www.portaldasfinancas.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Finanças no concelho de Loulé: apoio na inscrição de novos contribuintes, início de atividade independente e esclarecimentos fiscais."
    },

    // ============================================================
    // 🛡️ SEGURANÇA SOCIAL (INSTITUTO DA SEGURANÇA SOCIAL)
    // ============================================================
    {
        id: 'p-serv-96',
        title: "Segurança Social de Braga",
        category: "Direitos & Apoio Social",
        lat: 41.5520,
        lng: -8.4210,
        distance: 'N/A',
        address: "Largo São Francisco, 4700-444 Braga",
        city: "Braga",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Centro Distrital da Segurança Social em Braga: atribuição de NISS, pedidos de abono de família, subsídios de doença e apoio social."
    },
    {
        id: 'p-serv-97',
        title: "Segurança Social do Porto (Central)",
        category: "Direitos & Apoio Social",
        lat: 41.1500,
        lng: -8.6270,
        distance: 'N/A',
        address: "Rua de Entre Quintas, 4050-213 Porto",
        city: "Porto",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento central da Segurança Social no Porto: emissão e regularização de NISS, consultas contributivas e pedidos de proteção social."
    },
    {
        id: 'p-serv-98',
        title: "Segurança Social de Vila Nova de Gaia",
        category: "Direitos & Apoio Social",
        lat: 41.1290,
        lng: -8.6060,
        distance: 'N/A',
        address: "Avenida da República, 4430-190 Vila Nova de Gaia",
        city: "Vila Nova de Gaia",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Serviço de Segurança Social em Gaia: registo de trabalhadores dependentes e independentes, prestações familiares e Rendimento Social de Inserção."
    },
    {
        id: 'p-serv-99',
        title: "Segurança Social de Guimarães",
        category: "Direitos & Apoio Social",
        lat: 41.4440,
        lng: -8.2920,
        distance: 'N/A',
        address: "Rua da Rainha D. Maria II, 4810-227 Guimarães",
        city: "Guimarães",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento da Segurança Social em Guimarães: emissão de NISS, pedidos de parentalidade e esclarecimento sobre carreiras contributivas."
    },
    {
        id: 'p-serv-100',
        title: "Segurança Social de Viana do Castelo",
        category: "Direitos & Apoio Social",
        lat: 41.6950,
        lng: -8.8310,
        distance: 'N/A',
        address: "Rua da Junqueira, 4900-035 Viana do Castelo",
        city: "Viana do Castelo",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Centro da Segurança Social no Alto Minho: atribuição de NISS para cidadãos nacionais e estrangeiros e pedidos de pensões e subsídios."
    },
    {
        id: 'p-serv-105',
        title: "Segurança Social de Lisboa (Alvalade)",
        category: "Direitos & Apoio Social",
        lat: 38.7520,
        lng: -9.1430,
        distance: 'N/A',
        address: "Avenida de Roma, 1000-256 Lisboa",
        city: "Lisboa",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Serviço de atendimento oficial da Segurança Social em Lisboa: emissão de NISS, declarações de enquadramento e prestações de parentalidade."
    },
    {
        id: 'p-serv-106',
        title: "Segurança Social da Amadora",
        category: "Direitos & Apoio Social",
        lat: 38.7580,
        lng: -9.2310,
        distance: 'N/A',
        address: "Avenida Padre Cruz, 2700-559 Amadora",
        city: "Amadora",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento da Segurança Social na Amadora: pedidos de NISS, ação social familiar e esclarecimento de descontos contributivos."
    },
    {
        id: 'p-serv-107',
        title: "Segurança Social de Sintra",
        category: "Direitos & Apoio Social",
        lat: 38.7980,
        lng: -9.3820,
        distance: 'N/A',
        address: "Rua Bernardino Machado, 2710-443 Sintra",
        city: "Sintra",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Serviço de Segurança Social no concelho de Sintra: atribuição de NISS para trabalhadores e estudantes e apoio em prestações sociais."
    },
    {
        id: 'p-serv-108',
        title: "Segurança Social de Almada",
        category: "Direitos & Apoio Social",
        lat: 38.6810,
        lng: -9.1550,
        distance: 'N/A',
        address: "Rua da Constituição, 2800-068 Almada",
        city: "Almada",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Segurança Social na Margem Sul (Almada): emissão de NISS, pedidos de subsídio de desemprego e proteção social na parentalidade."
    },
    {
        id: 'p-serv-109',
        title: "Segurança Social de Cascais",
        category: "Direitos & Apoio Social",
        lat: 38.6990,
        lng: -9.4200,
        distance: 'N/A',
        address: "Avenida 25 de Abril, 2750-800 Cascais",
        city: "Cascais",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Balcão da Segurança Social em Cascais: inscrição de novos contribuintes, NISS, pensões e abonos de família."
    },
    {
        id: 'p-serv-110',
        title: "Segurança Social de Évora",
        category: "Direitos & Apoio Social",
        lat: 38.5700,
        lng: -7.9070,
        distance: 'N/A',
        address: "Rua de São João Evangelista, 7000-678 Évora",
        city: "Évora",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Centro Distrital de Évora: atribuição de NISS, assistência a famílias em risco de pobreza e prestações de segurança social."
    },
    {
        id: 'p-serv-111',
        title: "Segurança Social de Beja",
        category: "Direitos & Apoio Social",
        lat: 38.0170,
        lng: -7.8630,
        distance: 'N/A',
        address: "Rua Fernando Caldeira, 7800-118 Beja",
        city: "Beja",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Segurança Social em Beja: apoio a trabalhadores rurais e migrantes, emissão de NISS e gestão de pensões e subsídios."
    },
    {
        id: 'p-serv-112',
        title: "Segurança Social de Portalegre",
        category: "Direitos & Apoio Social",
        lat: 39.2930,
        lng: -7.4310,
        distance: 'N/A',
        address: "Rua Luís de Camões, 7300-533 Portalegre",
        city: "Portalegre",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Centro da Segurança Social no Alto Alentejo: atribuição de NISS, abono pré-natal e de família e suporte aos regimes contributivos."
    },
    {
        id: 'p-serv-135',
        title: "Segurança Social de Setúbal",
        category: "Direitos & Apoio Social",
        lat: 38.5244,
        lng: -8.8931,
        distance: 'N/A',
        address: "Rua de Santo António, 2900-614 Setúbal",
        city: "Setúbal",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento da Segurança Social em Setúbal: emissão de NISS, prestações por parentalidade, doença e subsídio de desemprego."
    },
    {
        id: 'p-serv-136',
        title: "Segurança Social da Guarda",
        category: "Direitos & Apoio Social",
        lat: 40.5372,
        lng: -7.2658,
        distance: 'N/A',
        address: "Rua do Encontro, 6300-705 Guarda",
        city: "Guarda",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Segurança Social na Beira Alta: pedidos de NISS, apoios à maternidade e infância e acompanhamento social no distrito da Guarda."
    },
    {
        id: 'p-serv-137',
        title: "Segurança Social de Vila Real",
        category: "Direitos & Apoio Social",
        lat: 41.3000,
        lng: -7.7333,
        distance: 'N/A',
        address: "Rua de São Domingos, 5000-529 Vila Real",
        city: "Vila Real",
        website: "https://www.seg-social.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento da Segurança Social em Vila Real: emissão de NISS para estudantes universitários (UTAD) e trabalhadores da região."
    },

    // ============================================================
    // 🏢 LOJAS DO CIDADÃO (REDE INTEGRADA NACIONAL)
    // ============================================================
    {
        id: 'p-serv-116',
        title: "Loja do Cidadão de Lisboa (Saldanha)",
        category: "Residência & Vistos",
        lat: 38.7340,
        lng: -9.1460,
        distance: 'N/A',
        address: "Avenida Fontes Pereira de Melo, 34B, 1050-121 Lisboa",
        city: "Lisboa",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Loja do Cidadão no centro financeiro de Lisboa: balcões do IRN (Cartão de Cidadão/Passaporte), Finanças (NIF), Segurança Social e CTT."
    },
    {
        id: 'p-serv-117',
        title: "Loja do Cidadão de Almada",
        category: "Residência & Vistos",
        lat: 38.6780,
        lng: -9.1580,
        distance: 'N/A',
        address: "Avenida Dom João II, 18, 2800-008 Almada",
        city: "Almada",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Balcão multisserviços em Almada: atendimento presencial do IRN, Finanças, Segurança Social, CTT e serviços municipais da Câmara de Almada."
    },
    {
        id: 'p-serv-118',
        title: "Loja do Cidadão de Sintra",
        category: "Residência & Vistos",
        lat: 38.7990,
        lng: -9.3810,
        distance: 'N/A',
        address: "Rua Dr. Alfredo da Costa, 2, 2710-523 Sintra",
        city: "Sintra",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Loja do Cidadão no concelho de Sintra: reúne num só local os balcões de identificação civil do IRN, Finanças e Segurança Social."
    },
    {
        id: 'p-serv-119',
        title: "Loja do Cidadão de Cascais",
        category: "Residência & Vistos",
        lat: 38.6970,
        lng: -9.4200,
        distance: 'N/A',
        address: "Largo da República, 1, 2750-508 Cascais",
        city: "Cascais",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento unificado do Estado em Cascais: emissão de documentos civis, registo fiscal, apoios da Segurança Social e SMAS de Cascais."
    },
    {
        id: 'p-serv-120',
        title: "Loja do Cidadão do Porto (Aliados)",
        category: "Residência & Vistos",
        lat: 41.1490,
        lng: -8.6110,
        distance: 'N/A',
        address: "Avenida dos Aliados, 11, 4000-065 Porto",
        city: "Porto",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Loja do Cidadão na emblemática Avenida dos Aliados no Porto: atendimento integrado do IRN, Finanças, Segurança Social e Águas do Porto."
    },
    {
        id: 'p-serv-121',
        title: "Loja do Cidadão de Braga",
        category: "Residência & Vistos",
        lat: 41.5510,
        lng: -8.4240,
        distance: 'N/A',
        address: "Largo São João do Souto, 4700-326 Braga",
        city: "Braga",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Polo central de serviços públicos de Braga: renovação de Cartão de Cidadão, Passaporte, registo predial, NIF e Segurança Social."
    },
    {
        id: 'p-serv-122',
        title: "Loja do Cidadão de Guimarães",
        category: "Residência & Vistos",
        lat: 41.4430,
        lng: -8.2930,
        distance: 'N/A',
        address: "Rua D. João I, 4810-225 Guimarães",
        city: "Guimarães",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Balcão multisserviços em Guimarães: reúne atendimentos da Autoridade Tributária, Segurança Social, IRN e Câmara Municipal."
    },
    {
        id: 'p-serv-123',
        title: "Loja do Cidadão de Coimbra",
        category: "Residência & Vistos",
        lat: 40.2070,
        lng: -8.4180,
        distance: 'N/A',
        address: "Rua do Brasil, 55, 3030-175 Coimbra",
        city: "Coimbra",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Loja do Cidadão de Coimbra: serviços integrados do IRN, Segurança Social, Finanças, CTT e Águas de Coimbra com atendimento presencial agendado."
    },
    {
        id: 'p-serv-124',
        title: "Loja do Cidadão de Aveiro",
        category: "Residência & Vistos",
        lat: 40.6420,
        lng: -8.6530,
        distance: 'N/A',
        address: "Largo da Praça do Peixe, 3800-243 Aveiro",
        city: "Aveiro",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Espaço de atendimento público em Aveiro: emissão de documentos de identidade e viagem, validação de NIF e gestão de pensões e subsídios."
    },
    {
        id: 'p-serv-125',
        title: "Loja do Cidadão de Évora",
        category: "Residência & Vistos",
        lat: 38.5710,
        lng: -7.9090,
        distance: 'N/A',
        address: "Rua da República, 7000-656 Évora",
        city: "Évora",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Loja do Cidadão em Évora: simplificação de contactos com o Estado com balcões de Finanças, Segurança Social, IRN e EDP/Distribuição."
    },
    {
        id: 'p-serv-126',
        title: "Loja do Cidadão de Faro (Centro)",
        category: "Residência & Vistos",
        lat: 37.0185,
        lng: -7.9315,
        distance: 'N/A',
        address: "Avenida da República, 286, 8000-079 Faro",
        city: "Faro",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Principal Loja do Cidadão do Algarve: acolhimento ao cidadão com balcões do IRN, Finanças, Segurança Social, CTT e Balcão do Emigrante."
    },
    {
        id: 'p-serv-127',
        title: "Loja do Cidadão de Setúbal",
        category: "Residência & Vistos",
        lat: 38.5244,
        lng: -8.8931,
        distance: 'N/A',
        address: "Avenida Luísa Todi, 125, 2900-462 Setúbal",
        city: "Setúbal",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Loja do Cidadão na baixa de Setúbal: emissão de Cartão de Cidadão, Passaporte, NIF, NISS e atendimento ao munícipe."
    },
    {
        id: 'p-serv-128',
        title: "Loja do Cidadão de Viseu",
        category: "Residência & Vistos",
        lat: 40.6566,
        lng: -7.9125,
        distance: 'N/A',
        address: "Rua Serpa Pinto, 10, 3500-192 Viseu",
        city: "Viseu",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento unificado do Estado em Viseu: balcões da Segurança Social, Finanças, Registo Civil e Predial do IRN."
    },
    {
        id: 'p-serv-129',
        title: "Loja do Cidadão de Bragança",
        category: "Residência & Vistos",
        lat: 41.8058,
        lng: -6.7572,
        distance: 'N/A',
        address: "Praça do Município, 1, 5300-245 Bragança",
        city: "Bragança",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Espaço público multisserviços em Bragança: atendimento presencial do IRN, Finanças, Segurança Social e Câmara Municipal."
    },
    {
        id: 'p-serv-130',
        title: "Loja do Cidadão de Castelo Branco",
        category: "Residência & Vistos",
        lat: 39.8222,
        lng: -7.4931,
        distance: 'N/A',
        address: "Campo da Feira, 6000-101 Castelo Branco",
        city: "Castelo Branco",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Loja do Cidadão na Beira Baixa: serviços integrados para resolução rápida de processos de identificação, impostos e segurança social."
    },
    {
        id: 'p-serv-131',
        title: "Loja do Cidadão de Santarém",
        category: "Residência & Vistos",
        lat: 39.2333,
        lng: -8.6833,
        distance: 'N/A',
        address: "Rua de São Bento, 2000-118 Santarém",
        city: "Santarém",
        website: "https://www.portaldocidadao.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Atendimento concentrado em Santarém: balcões do IRN, Autoridade Tributária, Segurança Social e serviços municipais."
    },

    // ============================================================
    // 🧠 SAÚDE, LINHAS DE APOIO & RESPOSTA DE EMERGÊNCIA
    // ============================================================
    {
        id: 'p-serv-ref-2',
        title: "Banco Alimentar Contra a Fome (Lisboa)",
        category: "Direitos & Apoio Social",
        lat: 38.7051,
        lng: -9.1912,
        distance: 'N/A',
        address: "Avenida de Ceuta (Norte), Armazém 1, 1300-125 Lisboa",
        city: "Lisboa",
        website: "https://www.bancoalimentar.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Organização solidária que recolhe excedentes e abastece centenas de instituições de solidariedade social com alimentos para famílias carenciadas."
    },
    {
        id: 'p-serv-ref-3',
        title: "AIMA – Apoio Psicológico (Vítimas de Guerra/Trauma)",
        category: "Saúde & Cuidados",
        lat: 38.7250,
        lng: -9.1350,
        distance: 'N/A',
        address: "Rua Álvaro Coutinho, 14, 1150-025 Lisboa",
        city: "Lisboa",
        website: "https://aima.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Gabinete especializado de apoio à saúde mental para pessoas refugiadas, requerentes de asilo e migrantes em situação de stress pós-traumático."
    },
    {
        id: 'p-serv-ref-4',
        title: "Ordem dos Psicólogos Portugueses",
        category: "Saúde & Cuidados",
        lat: 38.7303,
        lng: -9.1468,
        distance: 'N/A',
        address: "Avenida Fontes Pereira de Melo, 19D, 1050-116 Lisboa",
        city: "Lisboa",
        website: "https://www.ordemdospsicologos.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Associação profissional pública: diretório oficial de psicólogos credenciados em Portugal, guias de saúde mental e linhas de apoio psicológico de emergência."
    },
    {
        id: 'p-serv-ref-5',
        title: "SNS 24 (Apoio Médico e Psicológico)",
        category: "Saúde & Cuidados",
        lat: 38.7562,
        lng: -9.1415,
        distance: 'N/A',
        address: "Parque de Saúde de Lisboa, Av. do Brasil, 53, 1749-002 Lisboa",
        city: "Lisboa",
        phone: "(+351) 808 24 24 24",
        website: "https://www.sns24.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Linha telefónica gratuita 24h do SNS: triagem médica de sintomas, encaminhamento para urgências hospitalares, apoio psicológico e renovação de receitas médicas."
    },
    {
        id: 'p-serv-ref-8',
        title: "AIMA – Sede Central",
        category: "Residência & Vistos",
        lat: 38.7266,
        lng: -9.1351,
        distance: 'N/A',
        address: "Rua Álvaro Coutinho, 14, 1150-025 Lisboa",
        city: "Lisboa",
        website: "https://aima.gov.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Sede nacional da Agência para a Integração, Migrações e Asilo (AIMA): coordenação de políticas públicas migratórias, asilo e acolhimento em Portugal."
    },
    {
        id: 'p-serv-138',
        title: "IEFP Centro de Emprego de Setúbal",
        category: "Trabalho & Carreira",
        lat: 38.5244,
        lng: -8.8931,
        distance: 'N/A',
        address: "Rua de Goa, 12, 2900-394 Setúbal",
        city: "Setúbal",
        website: "https://www.iefp.pt",
        avgRating: 5.0,
        ratings: [],
        description: "Centro de emprego e formação do IEFP na Península de Setúbal: inscrição e encaminhamento para ofertas de emprego, apoio ao desemprego e formação profissional."
    }
];

export { PROTECTED_JOBS } from './massiveJobsDatabase';
